function study = run_routeA_focused_vsh_v2_external240_baseline()
% Run the 19-point external-240-kW baseline through the formal runner.

scriptDir = fileparts(mfilename('fullpath'));
sharedDir = fullfile(scriptDir, '..', 'RouteA_GasMixture_Derived');
addpath(scriptDir, sharedDir);

[cases, reference] = routeA_focused_external240kw_case_factory();
resultFile = fullfile(scriptDir, '..', '..', '02_结果', ...
    'RouteA_Cathode_cEGR_Focused', 'outputs', '20260820_vsh_validation', ...
    'RouteA_VSH_V2_external240_baseline_600s_20260820.mat');
cfg = struct( ...
    'modelId', "self_humidifying", ...
    'calculationType', "steady", ...
    'cases', cases, ...
    'researchDuration_s', 600, ...
    'tailLogicalWindow_s', [540 600], ...
    'steadyWindowDuration_s', 60, ...
    'retainSimulationOutputs', false, ...
    'executionMode', "parallel", ...
    'parallel', struct('poolProfile', "local", 'workerCount', 4, ...
        'showProgress', true, 'useFastRestart', false), ...
    'resultFile', string(resultFile), ...
    'externalCalibrationReference', reference);

study = run_routeA_focused_study(cfg);
routeA_focused_study = study; %#ok<NASGU>
save(resultFile, 'routeA_focused_study', '-v7.3');
assignin('base', 'routeA_focused_v2_study', study);
calibration = study.external240Calibration;
fprintf('V2_DONE cases=%d completed=%d passed=%d result=%s\n', ...
    numel(study.cases), sum([study.cases.simCompleted]), ...
    sum([study.cases.passed]), resultFile);
if isstruct(calibration)
    disp(calibration);
end
end
