function screen = routeA_focused_hydraulic_screen_assessment(study, contract)
% Assess only whether the fixed-boundary screen reached its declared inputs.

if ~isstruct(study) || ~isfield(study, 'cases')
    error('RouteA:HydraulicScreenStudy', 'Study results must contain cases.');
end
if ~isstruct(contract) || ~isscalar(contract)
    error('RouteA:HydraulicScreenContract', 'Contract must be a scalar struct.');
end

cases = study.cases;
rows = repmat(rowTemplate(), numel(cases), 1);
for idx = 1:numel(cases)
    rows(idx) = makeRow(cases(idx));
end

targetFlow = [rows.targetFreshAirMdot_kg_s];
observedFlow = [rows.observedFreshAirMdot_kg_s];
outletError = [rows.outletPressureError_kPa];
channelDrop = [rows.channelDrop_kPa];
finiteRows = isfinite(targetFlow) & isfinite(observedFlow) & ...
    isfinite(outletError) & isfinite(channelDrop);
orderedDrop = channelDrop;
if any(finiteRows)
    [~, order] = sort(targetFlow(finiteRows));
    orderedDrop = channelDrop(finiteRows);
    orderedDrop = orderedDrop(order);
end

acceptance = getField(contract, 'acceptance', struct());
outletTolerance_kPa = getField(acceptance, ...
    'outletPressureTolerance_kPa', 3);
flowTolerance = getField(acceptance, 'flowRelativeTolerance', 0.01);
requireMonotonic = logical(getField(acceptance, ...
    'requireMonotonicChannelDrop', true));
flowError = observedFlow - targetFlow;
relativeFlowError = abs(flowError) ./ max(abs(targetFlow), eps);
screen = struct( ...
    'schemaVersion', "RouteA_HydraulicScreenAssessment_v01", ...
    'scope', "model_only_fixed_boundary_hydraulic_response", ...
    'contract', contract, ...
    'rows', rows, ...
    'allCasesCompleted', all([rows.simCompleted]), ...
    'flowTrackingPassed', all(finiteRows) && ...
        all(relativeFlowError(finiteRows) <= flowTolerance), ...
    'outletTrackingPassed', all(finiteRows) && ...
        all(abs(outletError(finiteRows)) <= outletTolerance_kPa), ...
    'pressureDirectionPassed', all([rows.pressureDirectionPassed]), ...
    'channelDropMonotonic', ~requireMonotonic || ...
        numel(orderedDrop) <= 1 || all(diff(orderedDrop) >= -1e-6), ...
    'endpointLogSlope', endpointLogSlope(targetFlow, channelDrop), ...
    'behaviorPassed', false, ...
    'conclusionBoundary', ...
        "executed_model_response_only;_not_a_device_pressure-loss_validation");
screen.behaviorPassed = screen.allCasesCompleted && ...
    screen.flowTrackingPassed && screen.outletTrackingPassed && ...
    screen.pressureDirectionPassed && screen.channelDropMonotonic;
end

function row = makeRow(caseResult)
row = rowTemplate();
row.caseId = string(getField(caseResult, 'caseId', ""));
row.simCompleted = logical(getField(caseResult, 'simCompleted', false));
row.targetFreshAirMdot_kg_s = getNestedField(caseResult, ...
    {'caseCfg', 'air', 'targetMdot_kg_s'}, NaN);
row.observedFreshAirMdot_kg_s = getNestedField(caseResult, ...
    {'performance', 'cathode', 'compressorInletMassFlow_kg_s'}, NaN);
row.targetOutletPressure_MPa = getNestedField(caseResult, ...
    {'caseCfg', 'cathode', 'outletPressure_MPa_abs'}, NaN);
row.observedInletPressure_MPa = getNestedField(caseResult, ...
    {'pressureObservations', 'chain', 'stackCathodeChannelPressure_MPa'}, NaN);
row.observedOutletPressure_MPa = getNestedField(caseResult, ...
    {'pressureObservations', 'chain', 'cathodeOutletPressure_MPa'}, NaN);
row.channelDrop_kPa = 1e3 * getNestedField(caseResult, ...
    {'pressureObservations', 'chain', ...
    'stackCathodeChannelToCathodeOutletDrop_MPa'}, NaN);
row.outletPressureError_kPa = 1e3 * ...
    (row.observedOutletPressure_MPa - row.targetOutletPressure_MPa);
row.pressureDirectionPassed = logical(getField(caseResult, ...
    'pressureDirectionPassed', false));
end

function slope = endpointLogSlope(flow, drop)
valid = isfinite(flow) & isfinite(drop) & flow > 0 & drop > 0;
if nnz(valid) < 2
    slope = NaN;
    return;
end
flow = flow(valid);
drop = drop(valid);
[flow, order] = sort(flow);
drop = drop(order);
slope = log(drop(end) / drop(1)) / log(flow(end) / flow(1));
end

function row = rowTemplate()
row = struct( ...
    'caseId', "", ...
    'simCompleted', false, ...
    'targetFreshAirMdot_kg_s', NaN, ...
    'observedFreshAirMdot_kg_s', NaN, ...
    'targetOutletPressure_MPa', NaN, ...
    'observedInletPressure_MPa', NaN, ...
    'observedOutletPressure_MPa', NaN, ...
    'channelDrop_kPa', NaN, ...
    'outletPressureError_kPa', NaN, ...
    'pressureDirectionPassed', false);
end

function value = getNestedField(source, path, default)
value = source;
for idx = 1:numel(path)
    if ~isstruct(value) || ~isfield(value, path{idx})
        value = default;
        return;
    end
    value = value.(path{idx});
end
end

function value = getField(source, name, default)
if isstruct(source) && isfield(source, name)
    value = source.(name);
else
    value = default;
end
end
