function assessment = routeA_focused_external240kw_calibration_assessment(study, reference)
% Assess pressure and polarization gates for the external 240 kW case.
%
% This evaluates only the declared external-case boundary.  It deliberately
% does not infer compressor efficiency, intercooler heat transfer, or a
% material-independent electrochemical parameter from the lumped model.

if ~isstruct(study) || ~isfield(study, 'cases')
    error('RouteA:External240kWAssessmentStudy', ...
        'study must be a focused-study result with a cases field.');
end
if ~isstruct(reference) || ~isfield(reference, 'currentDensity_A_cm2')
    error('RouteA:External240kWAssessmentReference', ...
        'reference must come from routeA_focused_external240kw_case_factory.');
end

rows = repmat(rowTemplate(), numel(study.cases), 1);
for idx = 1:numel(study.cases)
    item = study.cases(idx);
    row = rowTemplate();
    row.caseId = string(getField(item, 'caseId', ""));
    row.simCompleted = logical(getField(item, 'simCompleted', false));
    row.localNumericsPassed = logical(getField(item, 'passed', false));
    row.errorId = string(getField(item, 'errorId', ""));
    row.j_A_cm2 = currentDensityFromCase(item);
    refIndex = find(abs(reference.currentDensity_A_cm2 - row.j_A_cm2) < 1e-10, 1);
    if isempty(refIndex)
        rows(idx) = row;
        continue;
    end
    row.referenceCellVoltage_V = reference.cellVoltage_V(refIndex);
    row.referenceFreshAirMdot_kg_s = reference.freshAirMdot_kg_s(refIndex);
    row.isTraining = any(abs( ...
        reference.trainingCurrentDensity_A_cm2 - row.j_A_cm2) < 1e-10);
    row.isPressureAnchor = any(abs( ...
        reference.pressureAnchorJ_A_cm2 - row.j_A_cm2) < 1e-10);
    if row.isPressureAnchor
        anchorIndex = find(abs( ...
            reference.pressureAnchorJ_A_cm2 - row.j_A_cm2) < 1e-10, 1);
        row.referenceInletPressure_MPa = ...
            reference.pressureAnchorInlet_MPa_abs(anchorIndex);
        row.referenceOutletPressure_MPa = ...
            reference.pressureAnchorOutlet_MPa_abs(anchorIndex);
        row.referenceCathodeInletTemperature_C = ...
            reference.cathodeInletTemperatureReference_C(anchorIndex);
        row.referenceCathodeOutletTemperature_C = ...
            reference.cathodeOutletTemperatureReference_C(anchorIndex);
    end
    row = collectObserved(row, item);
    rows(idx) = row;
end

pressureRows = rows([rows.isPressureAnchor] & [rows.simCompleted]);
validationRows = rows(~[rows.isTraining] & [rows.simCompleted]);
allVoltageRows = rows([rows.simCompleted]);

assessment = struct();
assessment.schemaVersion = "RouteA_Focused_External240kW_CalibrationAssessment_v02";
assessment.scope = "external_240kW_no_cEGR_0p1_to_1p9_Acm2";
assessment.rows = rows;
assessment.gates = struct( ...
    'outletPressureTolerance_kPa', 3, ...
    'outletPressureRelativeTolerance', .02, ...
    'inletPressureTolerance_kPa', 10, ...
    'inletPressureRelativeTolerance', .05, ...
    'cellVoltageValidationRMSE_V', .050, ...
    'cellVoltageMaximumError_V', .080);
assessment.numerical = numericalSummary(rows);
assessment.pressureMeasurementContract = getField(reference, ...
    'pressureMeasurementContract', struct());
assessment.pressure = pressureSummary(pressureRows, assessment.gates, ...
    assessment.pressureMeasurementContract);
assessment.electrical = electricalSummary(validationRows, allVoltageRows, ...
    assessment.gates);
assessment.temperature = temperatureSummary(rows);
assessment.gasTemperature = gasTemperatureSummary(pressureRows);
assessment.passed = assessment.numerical.passed && assessment.pressure.passed && ...
    assessment.electrical.passed && assessment.temperature.passed;
assessment.conclusionBoundary = ...
    "semi_quantitative_only_for_declared_external_case;_not_a_BOP_efficiency_or_material-property_identification";
end

function row = collectObserved(row, item)
if ~isfield(item, 'performance') || ~isstruct(item.performance)
    return;
end
performance = item.performance;
if isfield(performance, 'electrical')
    row.observedCellVoltage_V = getField(performance.electrical, ...
        'cellVoltage_V', NaN);
end
if isfield(performance, 'cathode')
    row.observedFreshAirMdot_kg_s = getField(performance.cathode, ...
        'compressorInletMassFlow_kg_s', NaN);
end
if isfield(performance, 'control')
    row.outletPressureTarget_MPa = getField(performance.control, ...
        'cathodeOutletPressureTarget_MPa_abs', NaN);
    row.humidifierEnabled = getField(performance.control, ...
        'humidifierEnabled', NaN);
end
if isfield(performance, 'pressure') && isstruct(performance.pressure) && ...
        isfield(performance.pressure, 'chain')
    chain = performance.pressure.chain;
    row.observedInletPressure_MPa = getField(chain, ...
        'stackCathodeChannelPressure_MPa', NaN);
    row.observedOutletPressure_MPa = getField(chain, ...
        'cathodeOutletPressure_MPa', NaN);
    row.observedChannelDrop_kPa = 1e3 * getField(chain, ...
        'stackCathodeChannelToCathodeOutletDrop_MPa', NaN);
    row.observedCathodeInletTemperature_C = getField(chain, ...
        'compressorAfterIntercoolerTemperature_K', NaN) - 273.15;
    row.observedCathodeOutletTemperature_C = getField(chain, ...
        'cathodeOutletTemperature_K', NaN) - 273.15;
end
if isfield(performance, 'thermal')
    row.observedStackTemperature_C = getField(performance.thermal, ...
        'stackTemperature_C', NaN);
    row.stackTemperatureSet_C = getField(performance.thermal, ...
        'stackTemperatureSet_C', NaN);
end
row.cellVoltageError_V = row.observedCellVoltage_V - row.referenceCellVoltage_V;
row.inletPressureError_kPa = 1e3 * (row.observedInletPressure_MPa - ...
    row.referenceInletPressure_MPa);
row.outletPressureError_kPa = 1e3 * (row.observedOutletPressure_MPa - ...
    row.referenceOutletPressure_MPa);
end

function summary = numericalSummary(rows)
completed = [rows.simCompleted];
summary = struct( ...
    'casesRequested', numel(rows), ...
    'casesCompleted', sum(completed), ...
    'allCaseLocalNumericsPassed', all([rows.localNumericsPassed]), ...
    'humidifierDisabledEverywhere', all([rows.humidifierEnabled] == 0), ...
    'passed', false);
summary.passed = summary.casesCompleted == summary.casesRequested && ...
    summary.allCaseLocalNumericsPassed && summary.humidifierDisabledEverywhere;
end

function summary = pressureSummary(rows, gates, measurementContract)
% blockedReason is reserved for the comparison-eligibility contract. It
% stays empty when the tap mapping is eligible, even if another pressure or
% top-level assessment gate later fails.
summary = struct( ...
    'anchorCount', numel(rows), ...
    'referenceMappingStatus', "not_declared", ...
    'comparisonEligible', false, ...
    'blockedReason', "", ...
    'inletRMSE_kPa', NaN, ...
    'outletRMSE_kPa', NaN, ...
    'inletWithinTolerance', false, ...
    'outletWithinTolerance', false, ...
    'channelDropMonotonicWithFreshAirFlow', false, ...
    'channelDropAbsoluteErrorWithin10kPa', false, ...
    'passed', false);
if isstruct(measurementContract)
    summary.referenceMappingStatus = string(getField(measurementContract, ...
        'status', "not_declared"));
    summary.comparisonEligible = logical(getField(measurementContract, ...
        'modelComparisonEligible', false));
end
if ~summary.comparisonEligible
    summary.blockedReason = "external_pressure_tap_mapping_not_confirmed";
end
if isempty(rows)
    return;
end
inletError = [rows.inletPressureError_kPa];
outletError = [rows.outletPressureError_kPa];
channelDrop = [rows.observedChannelDrop_kPa];
referenceDrop = 1e3 * ([rows.referenceInletPressure_MPa] - ...
    [rows.referenceOutletPressure_MPa]);
inletLimit = max(gates.inletPressureTolerance_kPa, ...
    gates.inletPressureRelativeTolerance * 1e3 * [rows.referenceInletPressure_MPa]);
outletLimit = max(gates.outletPressureTolerance_kPa, ...
    gates.outletPressureRelativeTolerance * 1e3 * [rows.referenceOutletPressure_MPa]);
summary.inletRMSE_kPa = rms(inletError);
summary.outletRMSE_kPa = rms(outletError);
summary.inletWithinTolerance = all(abs(inletError) <= inletLimit);
summary.outletWithinTolerance = all(abs(outletError) <= outletLimit);
[~, order] = sort([rows.referenceFreshAirMdot_kg_s]);
orderedDrop = channelDrop(order);
summary.channelDropMonotonicWithFreshAirFlow = all(diff(orderedDrop) >= -1e-6);
summary.channelDropAbsoluteErrorWithin10kPa = ...
    all(abs(channelDrop - referenceDrop) <= 10);
summary.passed = summary.comparisonEligible && ...
    summary.inletWithinTolerance && summary.outletWithinTolerance && ...
    summary.channelDropMonotonicWithFreshAirFlow && ...
    summary.channelDropAbsoluteErrorWithin10kPa;
end

function summary = electricalSummary(validationRows, allRows, gates)
summary = struct( ...
    'validationCount', numel(validationRows), ...
    'validationRMSE_mV', NaN, ...
    'validationMaximumAbsoluteError_mV', NaN, ...
    'polarizationMonotonicDecreasing', false, ...
    'passed', false);
if isempty(validationRows) || isempty(allRows)
    return;
end
validationError = [validationRows.cellVoltageError_V];
summary.validationRMSE_mV = 1e3 * rms(validationError);
summary.validationMaximumAbsoluteError_mV = 1e3 * max(abs(validationError));
[~, order] = sort([allRows.j_A_cm2]);
orderedVoltage = [allRows(order).observedCellVoltage_V];
summary.polarizationMonotonicDecreasing = all(diff(orderedVoltage) <= 1e-6);
summary.passed = summary.validationRMSE_mV <= 1e3 * ...
    gates.cellVoltageValidationRMSE_V && ...
    summary.validationMaximumAbsoluteError_mV <= 1e3 * ...
    gates.cellVoltageMaximumError_V && summary.polarizationMonotonicDecreasing;
end

function summary = temperatureSummary(rows)
observed = [rows.observedStackTemperature_C];
setpoint = [rows.stackTemperatureSet_C];
summary = struct( ...
    'count', numel(rows), ...
    'maximumAbsoluteSetpointDeviation_C', NaN, ...
    'passed', false, ...
    'scope', "fixed_stack_temperature_writeback_only");
if isempty(rows) || any(~isfinite(observed)) || any(~isfinite(setpoint))
    return;
end
summary.maximumAbsoluteSetpointDeviation_C = max(abs(observed - setpoint));
summary.passed = summary.maximumAbsoluteSetpointDeviation_C <= 1;
end

function summary = gasTemperatureSummary(rows)
% The inlet reference is the imposed gas-temperature boundary. It is a
% write-back check, whereas wet-in is an approximate outlet comparison and
% remains diagnostic until its thermal tap contract is independently known.
summary = struct( ...
    'anchorCount', numel(rows), ...
    'inletBoundaryRMSE_C', NaN, ...
    'outletComparisonRMSE_C', NaN, ...
    'outletComparisonMaximumAbsoluteError_C', NaN, ...
    'outletComparisonStatus', ...
        "approximate_stack_outlet_measurement_diagnostic_only", ...
    'passed', false);
if isempty(rows)
    return;
end
inletReference = [rows.referenceCathodeInletTemperature_C];
inletObserved = [rows.observedCathodeInletTemperature_C];
outletReference = [rows.referenceCathodeOutletTemperature_C];
outletObserved = [rows.observedCathodeOutletTemperature_C];
if all(isfinite(inletReference)) && all(isfinite(inletObserved))
    summary.inletBoundaryRMSE_C = rms(inletObserved - inletReference);
end
if all(isfinite(outletReference)) && all(isfinite(outletObserved))
    outletError = outletObserved - outletReference;
    summary.outletComparisonRMSE_C = rms(outletError);
    summary.outletComparisonMaximumAbsoluteError_C = max(abs(outletError));
end
end

function j = currentDensityFromCase(item)
j = NaN;
if ~isfield(item, 'caseCfg') || ~isstruct(item.caseCfg)
    return;
end
caseIdJ = currentDensityFromCaseId(item);
if isfinite(caseIdJ)
    j = caseIdJ;
    return;
end
if isfield(item.caseCfg, 'external240ReferenceCurrentDensity_A_cm2')
    j = double(item.caseCfg.external240ReferenceCurrentDensity_A_cm2);
    return;
end
if isfield(item.caseCfg, 'focused') && isstruct(item.caseCfg.focused) && ...
        isfield(item.caseCfg.focused, 'externalReferenceCurrentDensity_A_cm2')
    j = double(item.caseCfg.focused.externalReferenceCurrentDensity_A_cm2);
    return;
end
if ~isfield(item.caseCfg, 'boundary') || ~isstruct(item.caseCfg.boundary) || ...
        ~isfield(item.caseCfg.boundary, 'profile')
    j = currentDensityFromCaseId(item);
    return;
end
area_cm2 = 380;
if isfield(item.caseCfg, 'stack') && isstruct(item.caseCfg.stack) && ...
        isfield(item.caseCfg.stack, 'area_cm2')
    area_cm2 = item.caseCfg.stack.area_cm2;
end
j = double(item.caseCfg.boundary.profile) / double(area_cm2);
end

function j = currentDensityFromCaseId(item)
j = NaN;
if ~isfield(item, 'caseId')
    return;
end
token = regexp(char(string(item.caseId)), 'j([0-9]+)p([0-9]+)', ...
    'tokens', 'once');
if isempty(token)
    return;
end
j = str2double([token{1} '.' token{2}]);
end

function row = rowTemplate()
row = struct( ...
    'caseId', "", ...
    'simCompleted', false, ...
    'localNumericsPassed', false, ...
    'errorId', "", ...
    'j_A_cm2', NaN, ...
    'isTraining', false, ...
    'isPressureAnchor', false, ...
    'referenceCellVoltage_V', NaN, ...
    'referenceFreshAirMdot_kg_s', NaN, ...
    'referenceInletPressure_MPa', NaN, ...
    'referenceOutletPressure_MPa', NaN, ...
    'observedCellVoltage_V', NaN, ...
    'observedFreshAirMdot_kg_s', NaN, ...
    'observedInletPressure_MPa', NaN, ...
    'observedOutletPressure_MPa', NaN, ...
    'observedChannelDrop_kPa', NaN, ...
    'outletPressureTarget_MPa', NaN, ...
    'humidifierEnabled', NaN, ...
    'observedStackTemperature_C', NaN, ...
    'stackTemperatureSet_C', NaN, ...
    'referenceCathodeInletTemperature_C', NaN, ...
    'referenceCathodeOutletTemperature_C', NaN, ...
    'observedCathodeInletTemperature_C', NaN, ...
    'observedCathodeOutletTemperature_C', NaN, ...
    'cellVoltageError_V', NaN, ...
    'inletPressureError_kPa', NaN, ...
    'outletPressureError_kPa', NaN);
end

function value = getField(s, name, default)
if isstruct(s) && isfield(s, name) && ~isempty(s.(name))
    value = s.(name);
else
    value = default;
end
end
