function [cases, reference] = routeA_focused_external240kw_case_factory(jQuery, overrides)
% Build reproducible self-humidifying external-240-kW cases.
%
% The factory is a case-definition layer, not a runner.  It keeps the
% external measurements and the deliberately limited interpolation rules in
% one auditable place before run_routeA_focused_study executes the cases.

if nargin < 1 || isempty(jQuery)
    jQuery = referenceData().currentDensity_A_cm2;
end
if nargin < 2 || isempty(overrides)
    overrides = struct();
end
if ~isnumeric(jQuery) || ~isvector(jQuery) || any(~isfinite(jQuery))
    error('RouteA:External240kWCurrentDensity', ...
        'jQuery must be a finite numeric vector in A/cm^2.');
end
if ~isstruct(overrides) || ~isscalar(overrides)
    error('RouteA:External240kWOverrides', ...
        'overrides must be a scalar struct.');
end

reference = referenceData();
jQuery = double(jQuery(:).');
if any(jQuery < reference.currentDensity_A_cm2(1) - 1e-12) || ...
        any(jQuery > reference.currentDensity_A_cm2(end) + 1e-12)
    error('RouteA:External240kWRange', ...
        'External-240-kW calibration cases are limited to 0.1 to 1.9 A/cm^2.');
end

defaults = calibrationDefaults(overrides);
startupRampDuration_s = 60;
cases = struct([]);
for idx = 1:numel(jQuery)
    j = jQuery(idx);
    dataIndex = nearestDataIndex(reference.currentDensity_A_cm2, j);
    if abs(reference.currentDensity_A_cm2(dataIndex) - j) > 1e-10
        error('RouteA:External240kWDiscreteCurrentDensity', ...
            'j=%.6g A/cm^2 is not one of the 19 measured current-density points.', j);
    end

    current_A = reference.stackCurrent_A(dataIndex);
    freshAirMdot_kg_s = reference.freshAirMdot_kg_s(dataIndex);
    stackTemperature_C = interp1(reference.temperatureReferenceJ_A_cm2, ...
        reference.temperatureReference_C, j, 'linear');
    cathodeGasTemperature_C = interp1( ...
        reference.cathodeInletTemperatureReferenceJ_A_cm2, ...
        reference.cathodeInletTemperatureReference_C, j, 'linear');
    outletPressure_MPa = interp1(reference.pressureAnchorJ_A_cm2, ...
        reference.pressureAnchorOutlet_MPa_abs, j, 'linear');

    caseCfg = routeA_focused_case_template();
    caseCfg.caseId = "external240_j" + jLabel(j);
    caseCfg.description = "External 240 kW self-humidifying no-cEGR cold case";
    caseCfg.external240ReferenceCurrentDensity_A_cm2 = j;
    caseCfg.boundary = struct( ...
        'type', "Current", ...
        'profile', current_A, ...
        'minValue', 0, ...
        'maxValue', max(reference.stackCurrent_A));
    caseCfg.air.modeId = 1;
    % The measured value is a steady boundary.  Start air flow from zero
    % during the cold-start establishment period so the cEGR ratio has no
    % artificial nonzero denominator before the physical gas flow exists.
    caseCfg.air.targetMdot_kg_s = struct( ...
        'kind', "ramp", 'start_value', 0, 'end_value', freshAirMdot_kg_s, ...
        'start_s', 0, 'end_s', startupRampDuration_s);
    caseCfg.cathode.outletPressure_MPa_abs = outletPressure_MPa;
    caseCfg.cathode.humidifierEnabled = 0;
    caseCfg.cegr.enabled = logical(defaults.cegrEnabled);
    caseCfg.cegr.targetRatio = defaults.cegrTargetRatio;
    if caseCfg.cegr.enabled && caseCfg.cegr.targetRatio > 0
        % Passive return must establish with the same cold-start flow ramp
        % as fresh air; a nonzero ratio at zero compressor flow is invalid.
        caseCfg.cegr.profile = struct( ...
            'kind', "ramp", 'start_value', 0, ...
            'end_value', caseCfg.cegr.targetRatio, ...
            'start_s', 0, 'end_s', startupRampDuration_s);
    else
        caseCfg.cegr.profile = 0;
    end
    caseCfg.thermal.stackTemperatureSet_C = stackTemperature_C;
    caseCfg.environment = struct( ...
        'ambientTemperature_C', defaults.ambientTemperature_C, ...
        'ambientPressure_MPa_abs', defaults.ambientPressure_MPa_abs, ...
        'ambientRelativeHumidity', defaults.ambientRelativeHumidity);
    caseCfg.architecture.id = ...
        "Passive_SelfHumidifying_StackOutletIdealTee_CompressorInlet";
    caseCfg.focused.stackTemperature_C = stackTemperature_C;
    caseCfg.focused.cathodeGasTemperature_C = cathodeGasTemperature_C;
    caseCfg.focused.stackIo_A_cm2 = defaults.stackIo_A_cm2;
    caseCfg.focused.stackAlpha = defaults.stackAlpha;
    caseCfg.focused.cathodeChannelDpNominal_MPa = ...
        defaults.cathodeChannelDpNominal_MPa;
    caseCfg.focused.intercoolerDpNominal_MPa = ...
        defaults.intercoolerDpNominal_MPa;
    caseCfg.focused.cathodeChannelMdotNominal_kg_s = ...
        defaults.cathodeChannelMdotNominal_kg_s;
    caseCfg.focused.cathodeChannelFlowArea_m2 = ...
        defaults.cathodeChannelFlowArea_m2;
    caseCfg.focused.cathodeChannelLaminarFraction = ...
        defaults.cathodeChannelLaminarFraction;
    caseCfg.focused.exhaustBackpressureValveMaxArea_m2 = ...
        defaults.exhaustBackpressureValveMaxArea_m2;
    caseCfg.focused.exhaustBackpressureValveOpenMinArea_m2 = ...
        defaults.exhaustBackpressureValveOpenMinArea_m2;
    caseCfg.focused.exhaustBackpressureValveKi_area_per_MPa_s = ...
        defaults.exhaustBackpressureValveKi_area_per_MPa_s;
    if idx == 1
        cases = repmat(caseCfg, numel(jQuery), 1);
    end
    cases(idx) = caseCfg;
end

reference.requestedCurrentDensity_A_cm2 = jQuery;
reference.pressureMeasurementContract = pressureMeasurementContract();
reference.caseDefinition = struct( ...
    'parameterLayer', "external_case", ...
    'modelId', "self_humidifying", ...
    'humidifierEnabled', false, ...
    'freshAirBoundary', "measured_fresh_air_mass_flow", ...
    'currentBoundary', "0_to_measured_721A_only", ...
    'freshAirHumidity', "derived_from_ambient_20C_101p325kPa_50pctRH", ...
    'temperaturePolicy', ...
        "stack_temperature_from_recommended_coolant_mean;_cathode_inlet_temperature_from_direct_240kW_dry_out_anchors", ...
    'thermalComparisonPolicy', ...
        "wet_in_temperature_is_an_approximate_cathode_outlet_diagnostic_not_a_heat_management_calibration_gate", ...
    'pressurePolicy', ...
        "five_stack_inlet_outlet_absolute_pressure_anchor_setpoints", ...
    'cegrPolicy', "disabled_unless_explicitly_requested_for_screening");
end

function reference = referenceData()
reference = struct();
reference.source = struct( ...
    'electricalAndFlow', ...
        "00_支撑材料/01_项目系统实验数据/240kw电堆数据.txt", ...
    'thermalBoundarySchedule', ...
        "00_支撑材料/01_项目系统实验数据/电堆信息及推荐测试工况.xlsx (Sheet1)", ...
    'stackInletOutletTemperatureAnchors', ...
        "00_支撑材料/01_项目系统实验数据/240kw电堆数据.txt");
reference.currentDensity_A_cm2 = [ ...
    0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 1.1 1.2 1.3 1.4 1.5 ...
    1.6 1.7 1.8 1.9];
reference.stackCurrent_A = [ ...
    38 76 114 152 190 228 266 303 341 380 418 456 494 532 570 608 646 ...
    685 721];
reference.cellVoltage_V = [ ...
    .824 .792 .765 .758 .748 .737 .729 .720 .712 .705 .696 .686 .678 .670 ...
    .659 .655 .648 .643 .639];
reference.freshAirMdot_kg_s = 1e-3 * [ ...
    33.96 72.43 86.55 75.77 106.63 117.93 131.58 143.25 157.25 170.39 ...
    179.54 187.93 198.64 207.58 215.21 229.61 244.24 258.10 271.82];
reference.pressureAnchorJ_A_cm2 = [0.1 0.4 0.8 1.3 1.9];
reference.pressureAnchorInlet_MPa_abs = [ ...
    .1400000 .1570000 .1963158 .2247368 .2465414];
reference.pressureAnchorOutlet_MPa_abs = [ ...
    .1300000 .1425263 .1752632 .1961842 .2096992];
reference.pressureAnchorDrop_MPa = ...
    reference.pressureAnchorInlet_MPa_abs - ...
    reference.pressureAnchorOutlet_MPa_abs;
% Fixed stack-temperature boundary: use the recommended coolant mean
% temperature, T_water_in + DeltaT_water/2. This is a declared lumped
% thermal-boundary approximation, not a resolved coolant-loop model.
reference.temperatureReferenceJ_A_cm2 = [ ...
    0 .1 .2 .3 .4 .5 .6 .7 .8 .9 1.0 1.1 1.2 1.3 1.4 1.5 1.6 1.7 ...
    1.8 1.9 2.0 2.1 2.2];
reference.temperatureReference_C = [ ...
    60 61.5 64 65.5 68 70.5 74 77.5 80 80 80 80 80 80 80 80 80 80 ...
    80 80 80 80 80];
% Five direct 240 kW gas-temperature anchors. The source identifies dry
% outlet and wet inlet as adjacent to the cathode inlet and outlet; use
% inlet anchors to set the gas boundary and outlet anchors only for the
% resulting gas-path comparison.
reference.cathodeInletTemperatureReferenceJ_A_cm2 = [ ...
    .1 .4 .8 1.3 1.9];
reference.cathodeInletTemperatureReference_C = [ ...
    70.5 74.3 75.9 77.8 80.9];
reference.cathodeOutletTemperatureReferenceJ_A_cm2 = ...
    reference.cathodeInletTemperatureReferenceJ_A_cm2;
reference.cathodeOutletTemperatureReference_C = [ ...
    73.0 75.68421 78.52632 82.78947 89.4812];
reference.trainingCurrentDensity_A_cm2 = [0.1 0.2 0.4 0.7 1.0 1.3 1.6 1.9];
reference.validationCurrentDensity_A_cm2 = setdiff( ...
    reference.currentDensity_A_cm2, reference.trainingCurrentDensity_A_cm2, ...
    'stable');
end

function contract = pressureMeasurementContract()
contract = struct( ...
    'schemaVersion', "RouteA_External240kW_PressureMeasurementContract_v01", ...
    'status', "user_confirmed_stack_inlet_outlet", ...
    'pressureBasis', "raw_source_header_Pa_a_absolute", ...
    'flowBasis', "test_table_compressor_inlet_mass_flow_wet_dry_basis_unconfirmed", ...
    'modelComparisonEligible', true, ...
    'inletLabel', "raw_source_dry_out_pressure_at_stack_inlet_user_confirmed", ...
    'outletLabel', "raw_source_wet_in_pressure_at_stack_outlet_user_confirmed", ...
    'rawSourceEvidence', ...
        "240kw电堆数据.txt: dry_out/wet_in pressures in Pa(a); user confirmed both taps tightly at stack inlet/outlet", ...
    'remainingUncertainty', [ ...
        "compressor_inlet_mass_flow_wet_dry_basis", ...
        "same_time_window_and_sensor_uncertainty_for_the_five_anchors"], ...
    'permittedUse', ...
        "semi_quantitative_stack_pressure_calibration_for_declared_external_case_only");
end

function defaults = calibrationDefaults(overrides)
base = routeA_focused_parameter_defaults("self_humidifying");
defaults = struct( ...
    'ambientTemperature_C', 20, ...
    'ambientPressure_MPa_abs', .101325, ...
    'ambientRelativeHumidity', .5, ...
    'stackIo_A_cm2', base.stack.io_A_cm2, ...
    'stackAlpha', base.stack.alpha, ...
    'cathodeChannelDpNominal_MPa', base.cathode.channelDpNominal_MPa, ...
    'cathodeChannelMdotNominal_kg_s', ...
        base.cathode.channelMdotNominal_kg_s, ...
    'cathodeChannelFlowArea_m2', base.cathode.channelFlowArea_m2, ...
    'cathodeChannelLaminarFraction', ...
        base.cathode.channelLaminarFraction, ...
    'intercoolerDpNominal_MPa', base.bop.intercoolerDpNominal_MPa, ...
    'exhaustBackpressureValveMaxArea_m2', ...
        base.cathode.exhaustBackpressureValveMaxArea_m2, ...
    'exhaustBackpressureValveOpenMinArea_m2', ...
        base.cathode.exhaustBackpressureValveOpenMinArea_m2, ...
    'exhaustBackpressureValveKi_area_per_MPa_s', ...
        base.cathode.exhaustBackpressureValveKi_area_per_MPa_s, ...
    'cegrEnabled', false, ...
    'cegrTargetRatio', 0);
names = fieldnames(overrides);
for idx = 1:numel(names)
    if ~isfield(defaults, names{idx})
        error('RouteA:External240kWOverride', ...
            'Unsupported external-240-kW override: %s.', names{idx});
    end
    defaults.(names{idx}) = overrides.(names{idx});
end
validateattributes(defaults.cathodeChannelDpNominal_MPa, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>', 0, '<=', .2});
validateattributes(defaults.cathodeChannelMdotNominal_kg_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>', 0, '<=', 1});
validateattributes(defaults.cathodeChannelFlowArea_m2, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>', 0, '<=', .1});
validateattributes(defaults.cathodeChannelLaminarFraction, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>=', 0, '<=', .99});
validateattributes(defaults.stackIo_A_cm2, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>=', 1e-14, '<=', 1e-2});
validateattributes(defaults.stackAlpha, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>=', .4, '<=', 1});
validateattributes(defaults.cegrTargetRatio, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>=', 0, '<=', .9});
end

function index = nearestDataIndex(data, query)
[distance, index] = min(abs(data - query)); %#ok<ASGLU>
end

function text = jLabel(j)
text = replace(string(sprintf('%.1f', j)), '.', 'p');
end
