function pressure = routeA_focused_pressure_observations( ...
    out, model, window, ambientPressure_MPa_abs)
% Collect the focused pressure chain from existing Simscape log nodes.
%
% The compressor volume pressure is used as the compressor discharge proxy.
% The IntercoolerOutletPTSensor is the pressure after the current L2
% intercooler pressure-loss interface. Neither quantity is a compressor map
% shaft-pressure measurement or a validated hardware pressure rating.

pressure = struct( ...
    'schemaVersion', "RouteA_Focused_PressureObservations_v01", ...
    'status', "not_collected", ...
    'window_s', window, ...
    'nodes', repmat(nodeTemplate(), 0, 1), ...
    'chain', chainTemplate(), ...
    'definitions', struct( ...
        'compressorDischarge', "Compressor Volume.p_I", ...
        'compressorAfterIntercooler', "IntercoolerOutletPTSensor.P", ...
        'stackCathodeChannel', "PEMFC_Stack_Core/Cathode_Gas_Channels/Cathode.p_I", ...
        'cathodeOutlet', "CathodeOutletChamber.p_I", ...
        'splitNode', ...
            "cEGR_Valve_Upstream_PT_Sensor.P at the ideal stack-outlet tee; p_split=p_EGR,up", ...
        'egrValveDownstream', ...
            "cEGR_Valve_Downstream_PT_Sensor.P at compressor-inlet mixer side", ...
        'pressureMargin', "compressor_after_intercooler - cathode_outlet", ...
        'cathodeChannelRepresentation', ...
            "single_constant_volume_chamber_plus_calibratable_equivalent_flow_resistance_without_distributed_channel_friction", ...
        'engineeringUse', ...
            "lumped_pressure_readback_with_calibratable_equivalent_resistance"));

try
    simlog = out.get(get_param(model, 'SimscapeLogName'));
    paths = routeA_block_paths(model);
    specs = { ...
        'compressor_inlet_mixer', paths.compressorInletMixer, 'p_I', 'T_I'; ...
        'compressor_discharge', paths.compressorVolume, 'p_I', 'T_I'; ...
        'compressor_after_intercooler', ...
            [paths.oxygen '/IntercoolerOutletPTSensor'], 'P', 'T'; ...
        'stack_cathode_channel', [paths.cathodeGas '/Cathode'], 'p_I', 'T_I'; ...
        'cathode_outlet_chamber', paths.outletChamber, 'p_I', 'T_I'; ...
        'split_node', paths.egrValveUpSensor, 'P', 'T'; ...
        'egr_valve_downstream', paths.egrValveDownSensor, 'P', 'T'};

    for idx = 1:size(specs, 1)
        item = nodeTemplate();
        item.name = string(specs{idx, 1});
        item.path = string(specs{idx, 2});
        item.pressureProperty = string(specs{idx, 3});
        item.temperatureProperty = string(specs{idx, 4});
        node = simscape.logging.findNode(simlog, char(item.path));
        if isempty(node)
            item.status = "unavailable";
            pressure.nodes(end + 1) = item;
            continue;
        end
        if ~isprop(node, char(item.pressureProperty)) || ...
                ~isprop(node, char(item.temperatureProperty))
            item.status = "unavailable";
            pressure.nodes(end + 1) = item;
            continue;
        end
        item.pressure = seriesStats(node, char(item.pressureProperty), ...
            'MPa', window);
        item.temperature = seriesStats(node, ...
            char(item.temperatureProperty), 'K', window);
        if isprop(node, 'y_I_i')
            item.composition = compositionStats(node, window);
        end
        item.status = "collected";
        pressure.nodes(end + 1) = item;
    end

    collected = [pressure.nodes.status] == "collected";
    if all(collected)
        pressure.status = "collected";
    elseif any(collected)
        pressure.status = "partial";
    else
        pressure.status = "unavailable";
    end
    pressure.chain = buildChain(pressure.nodes, ambientPressure_MPa_abs);
catch exception
    pressure.status = "collection_error";
    pressure.errorId = string(exception.identifier);
    pressure.errorMessage = string(exception.message);
end
end

function item = nodeTemplate()
item = struct( ...
    'name', "", ...
    'path', "", ...
    'status', "not_collected", ...
    'pressureProperty', "", ...
    'temperatureProperty', "", ...
    'pressure', struct(), ...
    'temperature', struct(), ...
    'composition', struct());
end

function stats = seriesStats(node, propertyName, unit, window)
series = node.(propertyName).series;
time = series.time;
time = time(:);
data = series.values(unit);
data = normalizeData(data, time);
if size(data, 2) > 1
    data = data(:, 1);
end
mask = time >= window(1) & time < window(2);
if ~any(mask)
    error('RouteA:FocusedPressureWindow', ...
        'No samples are available for %s.', propertyName);
end
sampleTime = unique([window(1); time(mask); window(2)]);
sampleValues = interp1(time, data, sampleTime, 'linear', 'extrap');
stats = struct( ...
    'unit', unit, ...
    'mean', trapz(sampleTime, sampleValues) / diff(window), ...
    'maximum', max(sampleValues), ...
    'minimum', min(sampleValues));
end

function stats = compositionStats(node, window)
stats = struct('available', false, 'basis', "mole", ...
    'mean', [NaN NaN NaN NaN], 'maximum', [NaN NaN NaN NaN], ...
    'minimum', [NaN NaN NaN NaN]);
series = node.y_I_i.series;
time = series.time;
time = time(:);
data = normalizeData(series.values('1'), time);
if size(data, 2) < 4
    return;
end
mask = time >= window(1) & time < window(2);
if ~any(mask)
    return;
end
sample = data(mask, 1:4);
stats.available = true;
stats.mean = mean(sample, 1);
stats.maximum = max(sample, [], 1);
stats.minimum = min(sample, [], 1);
end

function chain = buildChain(nodes, ambientPressure_MPa_abs)
chain = chainTemplate();
for idx = 1:numel(nodes)
    node = nodes(idx);
    if node.status ~= "collected"
        continue;
    end
    switch node.name
        case "compressor_inlet_mixer"
            chain.compressorInletMixerPressure_MPa = node.pressure.mean;
            chain.compressorInletMixerTemperature_K = node.temperature.mean;
            if node.composition.available
                chain.compressorInletMixerMoleFraction = node.composition.mean;
            end
        case "compressor_discharge"
            chain.compressorDischargePressure_MPa = node.pressure.mean;
            chain.compressorDischargeTemperature_K = node.temperature.mean;
        case "compressor_after_intercooler"
            chain.compressorAfterIntercoolerPressure_MPa = node.pressure.mean;
            chain.compressorAfterIntercoolerTemperature_K = node.temperature.mean;
        case "stack_cathode_channel"
            chain.stackCathodeChannelPressure_MPa = node.pressure.mean;
            chain.stackCathodeChannelTemperature_K = node.temperature.mean;
        case "cathode_outlet_chamber"
            chain.cathodeOutletPressure_MPa = node.pressure.mean;
            chain.cathodeOutletTemperature_K = node.temperature.mean;
        case "split_node"
            chain.splitPressure_MPa = node.pressure.mean;
            chain.splitTemperature_K = ...
                node.temperature.mean;
            chain.egrValveUpstreamPressure_MPa = node.pressure.mean;
            chain.egrValveUpstreamTemperature_K = node.temperature.mean;
        case "egr_valve_downstream"
            chain.egrValveDownstreamPressure_MPa = node.pressure.mean;
            chain.egrValveDownstreamTemperature_K = node.temperature.mean;
    end
end
chain.compressorDischargeToCathodeOutletMargin_MPa = ...
    chain.compressorDischargePressure_MPa - chain.cathodeOutletPressure_MPa;
chain.compressorAfterIntercoolerToCathodeOutletMargin_MPa = ...
    chain.compressorAfterIntercoolerPressure_MPa - ...
    chain.cathodeOutletPressure_MPa;
chain.compressorAfterIntercoolerToStackCathodeChannelDrop_MPa = ...
    chain.compressorAfterIntercoolerPressure_MPa - ...
    chain.stackCathodeChannelPressure_MPa;
chain.stackCathodeChannelToCathodeOutletDrop_MPa = ...
    chain.stackCathodeChannelPressure_MPa - ...
    chain.cathodeOutletPressure_MPa;
if nargin >= 2 && ~isempty(ambientPressure_MPa_abs) && ...
        isfinite(ambientPressure_MPa_abs) && isfinite(chain.splitPressure_MPa)
    chain.exhaustBackpressureValveDrop_MPa = ...
        chain.splitPressure_MPa - ambientPressure_MPa_abs;
end
chain.splitToCompressorInletMargin_MPa = ...
    chain.splitPressure_MPa - chain.compressorInletMixerPressure_MPa;
chain.egrValvePressureDrop_MPa = ...
    chain.egrValveUpstreamPressure_MPa - ...
    chain.egrValveDownstreamPressure_MPa;
chain.cathodeOutletToCompressorInletMargin_MPa = ...
    chain.cathodeOutletPressure_MPa - ...
    chain.compressorInletMixerPressure_MPa;
end

function chain = chainTemplate()
chain = struct( ...
    'compressorInletMixerPressure_MPa', NaN, ...
    'compressorInletMixerTemperature_K', NaN, ...
    'compressorInletMixerMoleFraction', [NaN NaN NaN NaN], ...
    'compressorDischargePressure_MPa', NaN, ...
    'compressorDischargeTemperature_K', NaN, ...
    'compressorAfterIntercoolerPressure_MPa', NaN, ...
    'compressorAfterIntercoolerTemperature_K', NaN, ...
    'stackCathodeChannelPressure_MPa', NaN, ...
    'stackCathodeChannelTemperature_K', NaN, ...
    'cathodeOutletPressure_MPa', NaN, ...
    'cathodeOutletTemperature_K', NaN, ...
    'splitPressure_MPa', NaN, ...
    'splitTemperature_K', NaN, ...
    'egrValveUpstreamPressure_MPa', NaN, ...
    'egrValveUpstreamTemperature_K', NaN, ...
    'egrValveDownstreamPressure_MPa', NaN, ...
    'egrValveDownstreamTemperature_K', NaN, ...
    'compressorDischargeToCathodeOutletMargin_MPa', NaN, ...
    'compressorAfterIntercoolerToCathodeOutletMargin_MPa', NaN, ...
    'compressorAfterIntercoolerToStackCathodeChannelDrop_MPa', NaN, ...
    'stackCathodeChannelToCathodeOutletDrop_MPa', NaN, ...
    'exhaustBackpressureValveDrop_MPa', NaN, ...
    'splitToCompressorInletMargin_MPa', NaN, ...
    'egrValvePressureDrop_MPa', NaN, ...
    'cathodeOutletToCompressorInletMargin_MPa', NaN);
end

function data = normalizeData(data, time)
if isvector(data)
    data = data(:);
end
if size(data, 1) ~= numel(time)
    data = data.';
end
if size(data, 1) ~= numel(time)
    error('RouteA:FocusedPressureSeriesShape', ...
        'Simscape series shape is inconsistent with its time vector.');
end
end
