function caseCfg = routeA_focused_case_template(modelId)
% Return the focused-model case contract with platform defaults.

if nargin < 1 || strlength(string(modelId)) == 0
    modelId = "focused_legacy";
end
params = routeA_focused_parameter_defaults(modelId);
standard = routeA_simCase_template();
caseCfg = struct();
caseCfg.caseId = "focused_case";
caseCfg.description = "Focused cathode-cEGR case";
caseCfg.boundary = struct('type', "Current", 'profile', 100);
caseCfg.air = struct( ...
    'modeId', standard.controls.cathode.airControlMode, ...
    'targetOer', standard.controls.cathode.targetOer, ...
    'targetMdot_kg_s', standard.controls.cathode.targetMdot_kg_s, ...
    'directCommand', standard.controls.cathode.directCommand, ...
    'pid', standard.controls.cathode.airController);
caseCfg.cathode = struct( ...
    'sourcePressure_MPa_abs', standard.controls.cathode.sourcePressure_MPa_abs, ...
    'sourceTemperature_C', standard.controls.cathode.sourceTemperature_C, ...
    'freshAirO2MoleFraction', standard.controls.cathode.o2MoleFraction, ...
    'freshAirWaterMoleFraction', standard.controls.cathode.h2oMoleFraction, ...
    'outletPressure_MPa_abs', standard.controls.cathode.outletPressure_MPa_abs, ...
    'humidifierRelativeHumidity', standard.controls.cathode.humidifierRH, ...
    'humidifierEnabled', 0);
caseCfg.cegr = standard.controls.cegr;
caseCfg.cegr.enabled = true;
caseCfg.cegr.profile = caseCfg.cegr.targetRatio;
caseCfg.anode = struct( ...
    'tankPressure_MPa_abs', standard.controls.anode.sourcePressure_MPa_abs, ...
    'sourceTemperature_C', standard.controls.anode.sourceTemperature_C, ...
    'hydrogenMoleFraction', standard.controls.anode.h2MoleFraction, ...
    'inletPressure_MPa_abs', standard.controls.anode.inletPressure_MPa_abs, ...
    'humidifierRelativeHumidity', standard.controls.anode.humidifierRH, ...
    'recirculationBaseCommand', standard.controls.anode.recirculationBaseCommand, ...
    'recirculationCurrentGain_A_inv', ...
        standard.controls.anode.recirculationCurrentGain_A_inv, ...
    'purgeEnabled', standard.controls.anode.purgeEnabled, ...
    'purgeOnN2MoleFraction', standard.controls.anode.purgeOnN2MoleFraction, ...
    'purgeOffN2MoleFraction', standard.controls.anode.purgeOffN2MoleFraction);
caseCfg.thermal = standard.controls.thermal;
caseCfg.stack = standard.controls.stack;
caseCfg.devices = standard.controls.devices;
caseCfg.controller = standard.controls.electrical.voltageController;
caseCfg.environment = params.environment;
caseCfg.designPoint = params.designPoint;
caseCfg.ejector = params.ejector;
caseCfg.bopDesign = params.bop.design;
caseCfg.architecture = struct( ...
    'id', params.architectureId, ...
    'drive', params.architecture.drive, ...
    'humidificationMode', "self_humidifying_external_MIn_disabled", ...
    'takeoff', params.architecture.takeoff, ...
    'returnLocation', params.architecture.returnLocation, ...
    'backpressureLocation', "common_pre_split", ...
    'separatorStatus', "gas_phase_L2_no_composition_change", ...
    'splitLocation', "post_separator_gas_boundary");
caseCfg.focused = struct( ...
    'stackTemperature_C', [], ...
    'cathodeGasTemperature_C', [], ...
    'stackIo_A_cm2', params.stack.io_A_cm2, ...
    'stackAlpha', params.stack.alpha, ...
    'cathodeSourcePressure_MPa_abs', [], ...
    'cathodeSourceTemperature_C', [], ...
    'cathodeChannelDpNominal_MPa', params.cathode.channelDpNominal_MPa, ...
    'cathodeChannelMdotNominal_kg_s', ...
        params.cathode.channelMdotNominal_kg_s, ...
    'cathodeChannelFlowArea_m2', params.cathode.channelFlowArea_m2, ...
    'cathodeChannelLaminarFraction', ...
        params.cathode.channelLaminarFraction, ...
    'intercoolerDpNominal_MPa', [], ...
    'commonBackpressureValveMaxArea_m2', ...
        params.cathode.commonBackpressureValveMaxArea_m2, ...
    'commonBackpressureValveOpenMinArea_m2', ...
        params.cathode.commonBackpressureValveOpenMinArea_m2, ...
    'commonBackpressureValveKi_area_per_MPa_s', ...
        params.cathode.commonBackpressureValveKi_area_per_MPa_s, ...
    'anodeFeedPressure_MPa_abs', [], ...
    'anodeInletMdot_kg_s', params.anode.inletMdot_kg_s, ...
    'anodeOutletPressure_MPa_abs', ...
        params.anode.outletPressure_MPa_abs, ...
    'anodeBoundaryTemperature_C', [], ...
    'anodeHydrogenMoleFraction', [], ...
    'anodePipeLength_m', params.anode.pipeLength_m, ...
    'anodePipeDiameter_m', params.anode.pipeDiameter_m, ...
    'anodePipeArea_m2', params.anode.pipeArea_m2, ...
    'anodePipeExtraLength_m', params.anode.pipeExtraLength_m, ...
    'anodePipeRoughness_m', params.anode.pipeRoughness_m);
end
