function [cases, contract] = routeA_focused_external240kw_hydraulic_screen_case_factory(jQuery, overrides)
% Build fixed-boundary cases that expose the current cathode pressure curve.

if nargin < 1 || isempty(jQuery)
    jQuery = [0.1 0.4 0.8 1.3 1.9];
end
if nargin < 2 || isempty(overrides)
    overrides = struct();
end

settings = defaultSettings(overrides);
[cases, reference] = routeA_focused_external240kw_case_factory(jQuery);
for idx = 1:numel(cases)
    caseCfg = cases(idx);
    caseCfg.caseId = "external240_hydraulic_iso_m" + ...
        flowLabel(caseCfg.air.targetMdot_kg_s);
    caseCfg.description = ...
        "External 240 kW hydraulic identification: fixed I, T, and p_out";
    caseCfg.boundary.profile = settings.fixedCurrent_A;
    caseCfg.cathode.outletPressure_MPa_abs = settings.outletPressure_MPa_abs;
    caseCfg.thermal.stackTemperatureSet_C = settings.stackTemperature_C;
    caseCfg.focused.stackTemperature_C = settings.stackTemperature_C;
    caseCfg.cegr.enabled = false;
    caseCfg.cegr.targetRatio = 0;
    caseCfg.cegr.profile = 0;
    cases(idx) = caseCfg;
end

contract = struct( ...
    'schemaVersion', "RouteA_External240kW_HydraulicScreen_v01", ...
    'parameterLayer', "external_case", ...
    'purpose', "model_only_hydraulic_response_screen", ...
    'freshAirFlowSource', ...
        "external240_reference_freshAirMdot_kg_s_at_selected_current_anchors", ...
    'fixedCurrent_A', settings.fixedCurrent_A, ...
    'fixedStackTemperature_C', settings.stackTemperature_C, ...
    'fixedOutletPressure_MPa_abs', settings.outletPressure_MPa_abs, ...
    'cegrEnabled', false, ...
    'comparisonPolicy', ...
        "do_not_calibrate_or_claim_device_validation_from_this_model_only_screen", ...
    'requiredObservables', [ ...
        "compressorInletMassFlow_kg_s"; ...
        "stackCathodeChannelPressure_MPa"; ...
        "cathodeOutletPressure_MPa"; ...
        "stackCathodeChannelToCathodeOutletDrop_MPa"], ...
    'acceptance', struct( ...
        'outletPressureTolerance_kPa', 3, ...
        'flowRelativeTolerance', 0.01, ...
        'requireMonotonicChannelDrop', true), ...
    'sourceCurrentDensity_A_cm2', reference.requestedCurrentDensity_A_cm2(:));
end

function settings = defaultSettings(overrides)
settings = struct( ...
    'fixedCurrent_A', 38, ...
    'stackTemperature_C', 80, ...
    'outletPressure_MPa_abs', 0.21);
names = fieldnames(overrides);
for idx = 1:numel(names)
    if ~isfield(settings, names{idx})
        error('RouteA:HydraulicScreenOverride', ...
            'Unsupported hydraulic-screen override: %s.', names{idx});
    end
    settings.(names{idx}) = overrides.(names{idx});
end
validateattributes(settings.fixedCurrent_A, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>=', 0, '<=', 721});
validateattributes(settings.stackTemperature_C, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>=', 60, '<=', 100});
validateattributes(settings.outletPressure_MPa_abs, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>=', 0.1, '<=', 0.4});
end

function label = flowLabel(mdot_kg_s)
label = string(sprintf('%06d', round(1e6 * mdot_kg_s)));
end
