function metrics = routeA_focused_performance_metrics(result, context)
% Build focused cathode and stack performance metrics from one assessed case.
%
% The oxygen partial pressure is deliberately labelled at the compressor
% inlet mixer, where the current focused model exposes pressure and mixture
% composition. It is not renamed as a stack cathode inlet measurement.

metrics = struct( ...
    'schemaVersion', "RouteA_Focused_PerformanceMetrics_v03", ...
    'status', "not_available", ...
    'comparisonEligible', false, ...
    'electrical', struct(), ...
    'cathode', struct(), ...
    'cegr', struct(), ...
    'thermal', struct(), ...
    'water', struct(), ...
    'pressure', struct(), ...
    'antiCondensation', struct(), ...
    'control', struct(), ...
    'definitions', definitionContract());

if ~isstruct(result) || ~isstruct(context) || ...
        ~isfield(result, 'tail') || ~isfield(result, 'gasClosure')
    metrics.status = "assessment_incomplete";
    return;
end

tail = result.tail;
area = context.stackArea_cm2;
cells = context.stackCells;
current = tail.stackCurrent_A.mean;
voltage = tail.stackVoltage_V.mean;
power = tail.stackPower_kW.mean;

metrics.electrical = struct( ...
    'current_A', current, ...
    'voltage_V', voltage, ...
    'power_kW', power, ...
    'cellVoltage_V', voltage / max(cells, 1), ...
    'currentDensity_A_cm2', current / max(area, eps), ...
    'powerDensity_kW_cm2', power / max(area, eps), ...
    'stackCells', cells, ...
    'activeArea_cm2', area, ...
    'boundaryType', string(context.boundaryType));

rMix = tail.egrRatio.mean;
rFresh = tail.freshBasisRatio.mean;
split = getField(result, 'cegrSplit', struct());
metrics.cegr = struct( ...
    'targetRatio', result.targetRatio, ...
    'actualRatioSplitBasis', getField(split, 'ratioTotalMassBasis', NaN), ...
    'splitReturnMdot_kg_s', getField(split, 'returnMdot_kg_s', NaN), ...
    'splitExhaustMdot_kg_s', getField(split, 'exhaustMdot_kg_s', NaN), ...
    'splitTotalMdot_kg_s', getField(split, 'totalMdot_kg_s', NaN), ...
    'splitFlowBasis', getField(split, 'basis', "not_available"), ...
    'splitFlowStatus', getField(split, 'status', "not_available"), ...
    'actualRatioSplitDryBasis', getField(split, 'ratioDryBasis', NaN), ...
    'splitDryBasisStatus', getField(split, 'dryBasisStatus', ...
        "not_available_branch_species"), ...
    'actualRatioMixBasis', rMix, ...
    'actualRatioFreshBasis', rFresh, ...
    'massFlow_kg_s', tail.egrMdot_kg_s.mean, ...
    'freshAirApprox_kg_s', tail.freshAirApprox_kg_s.mean, ...
    'mixedAirMassFlow_kg_s', tail.compressorMdot_kg_s.mean, ...
    'valveArea_m2', tail.egrValveArea_m2.mean, ...
    'valveAreaFraction', tail.egrValveAreaFraction.mean, ...
    'valveDeltaP_MPa', tail.egrValveDeltaP_MPa.mean, ...
    'controlMode', context.cegrControls.controlMode, ...
    'valveMode', context.cegrControls.valveMode, ...
    'trackingRequired', result.cegrTrackingRequired);

compressorMassFraction = getField(result.gasClosure, ...
    'compressorInletMassFraction', [NaN NaN NaN NaN]);
[compressorMoleFraction, pO2] = oxygenPressure( ...
    compressorMassFraction, tail.compressorPressure_Pa.mean, ...
    context.molarMass_kg_mol);
metrics.cathode = struct( ...
    'compressorInletMassFlow_kg_s', tail.compressorMdot_kg_s.mean, ...
    'compressorInletPressure_Pa', tail.compressorPressure_Pa.mean, ...
    'compressorInletTemperature_K', tail.compressorTemperature_K.mean, ...
    'compressorInletO2MassFraction', compressorMassFraction(2), ...
    'cathodeInletO2MassFraction', getField(tail, ...
        'inletO2MassFraction', struct('mean', NaN)).mean, ...
    'compressorInletCompositionMassFraction', compressorMassFraction, ...
    'compressorInletCompositionMoleFraction', compressorMoleFraction, ...
    'freshAirWaterVaporMdot_kg_s', speciesComponent(result.gasClosure, ...
        'freshAirSpeciesMdot_kg_s', 4), ...
    'cathodeInletWaterVaporMdot_kg_s', getField(tail, ...
        'inletWaterVaporMdot_kg_s', struct('mean', NaN)).mean, ...
    'cathodeOutletWaterVaporMdot_kg_s', speciesComponent(result.gasClosure, ...
        'outletSpeciesMdot_kg_s', 4), ...
    'compressorInletO2PartialPressure_Pa', pO2, ...
    'oxygenPartialPressureLocation', "compressor_inlet_mixer", ...
    'cathodeInletRH', getField(tail, 'rhCaIn', struct('mean', NaN)).mean, ...
    'cathodeOutletRH', getField(tail, 'rhCaOut', struct('mean', NaN)).mean, ...
    'relativeHumidityUse', "display_only;_not_a_mass_or_steady_state_basis", ...
    'oxygenStoich_lambda', tail.lambdaCaIn.mean, ...
    'cathodeOutletPressure_MPa', tail.cathodeOutletPressure_MPa.mean, ...
    'cathodeOutletTemperature_K', tail.cathodeOutletTemperature_K.mean, ...
    'gasClosurePassed', result.gasClosurePassed);

metrics.thermal = struct( ...
    'stackTemperature_C', tail.stackTemperature_C.mean, ...
    'stackTemperatureSet_C', context.thermal.stackTemperatureSet_C, ...
    'stackTemperatureDeviation_C', tail.stackTemperature_C.mean - ...
        context.thermal.stackTemperatureSet_C, ...
    'heatFlowResultStatus', "not_closed_fixed_temperature_boundary");

metrics.water = waterMetric(result);
metrics.pressure = getField(result, 'pressureObservations', struct());
metrics.antiCondensation = getField(result, ...
    'antiCondensation', struct());
metrics.control = struct( ...
    'airModeId', context.air.modeId, ...
    'targetOer', context.air.targetOer, ...
    'targetMdot_kg_s', context.air.targetMdot_kg_s, ...
    'directCompressorCommand', context.air.directCommand, ...
    'freshAirSourcePressure_MPa_abs', context.cathode.sourcePressure_MPa_abs, ...
    'freshAirSourceTemperature_C', context.cathode.sourceTemperature_C, ...
    'freshAirO2MoleFraction', context.cathode.freshAirO2MoleFraction, ...
    'freshAirWaterMoleFraction', context.cathode.freshAirWaterMoleFraction, ...
    'cathodeOutletPressureTarget_MPa_abs', ...
        context.cathode.outletPressure_MPa_abs, ...
    'humidifierRH', context.cathode.humidifierRelativeHumidity, ...
    'humidifierEnabled', logical(context.cathode.humidifierEnabled), ...
    'stackTemperatureSet_C', context.thermal.stackTemperatureSet_C, ...
    'focusedParameterBridgeStatus', context.focusedParameterBridge.status, ...
    'electricalBoundaryPassed', result.boundaryPassed, ...
    'cEGRPassed', result.cegrPassed, ...
    'lambdaPassed', result.lambdaPassed, ...
    'steadyPassed', result.steadyPassed);

metrics.comparisonEligible = logical(result.passed) && ...
    logical(result.gasClosurePassed) && logical(result.steadyPassed);
if metrics.comparisonEligible
    metrics.status = "behavior_verified_for_focused_scope";
else
    metrics.status = "executed_not_eligible_for_performance_comparison";
end
end

function [moleFraction, pO2] = oxygenPressure(massFraction, pressurePa, molarMass)
moleFraction = [NaN NaN NaN NaN];
if numel(massFraction) ~= 4 || any(~isfinite(massFraction)) || ...
        numel(molarMass) ~= 4 || any(~isfinite(molarMass)) || ...
        ~isfinite(pressurePa)
    return;
end
amount = massFraction ./ double(molarMass(:).');
total = sum(amount);
if total <= 0 || ~isfinite(total)
    return;
end
moleFraction = amount / total;
pO2 = pressurePa * moleFraction(2);
end

function water = waterMetric(result)
water = struct( ...
    'status', "not_available", ...
    'mixerCondensationRate_kg_s', NaN, ...
    'mixerSaturationRatio', NaN, ...
    'nodesCollected', 0, ...
    'liquidInventoryClosed', false, ...
    'engineeringConclusionAllowed', false);
if ~isfield(result, 'waterObservations') || ...
        ~isstruct(result.waterObservations)
    return;
end
obs = result.waterObservations;
water.nodesCollected = sum([obs.nodes.status] == "collected");
for idx = 1:numel(obs.nodes)
    node = obs.nodes(idx);
    if node.name ~= "compressor_inlet_mixer" || node.status ~= "collected"
        continue;
    end
    if isfield(node, 'condensation') && ...
            isfield(node.condensation, 'mean_kg_s')
        water.mixerCondensationRate_kg_s = node.condensation.mean_kg_s;
    end
    if isfield(node, 'saturation') && ...
            isfield(node.saturation, 'mean')
        water.mixerSaturationRatio = node.saturation.mean;
    end
    water.status = "collected_gas_phase_only";
    break;
end
end

function value = speciesComponent(gasClosure, fieldName, index)
value = NaN;
if ~isstruct(gasClosure) || ~isfield(gasClosure, fieldName)
    return;
end
species = gasClosure.(fieldName);
if isnumeric(species) && numel(species) >= index && isfinite(species(index))
    value = species(index);
end
end

function value = getField(s, name, default)
if isstruct(s) && isfield(s, name) && ~isempty(s.(name))
    value = s.(name);
else
    value = default;
end
end

function definitions = definitionContract()
definitions = struct( ...
    'r_split', ...
        "m_return / (m_return + m_exhaust) at the modeled return/exhaust branch flow signals; total-mass basis until branch species are available", ...
    'r_split_dry', ...
        "dry-basis split ratio; not available until return and exhaust branch species are observed", ...
    'x_comp_in', "m_return / (m_return + m_fresh) at compressor_inlet_mixer", ...
    'r_mix_legacy', "m_cegr / m_compressor_inlet; retained as a legacy compressor-inlet ratio", ...
    'r_fresh', "m_return / m_fresh", ...
    'oxygenPartialPressure', ...
        "p_abs * mole_fraction_O2 at compressor_inlet_mixer", ...
    'currentDensity', "stack_current / active_area_per_cell", ...
    'powerDensity', "stack_power / active_area_per_cell", ...
    'waterBoundary', "gas_phase_condensation_and_saturation_only");
end
