function analysis = routeA_focused_performance_analysis(study)
% Summarize the performance contract across focused study cases.

analysis = struct( ...
    'schemaVersion', "RouteA_Focused_PerformanceAnalysis_v03", ...
    'status', "no_cases", ...
    'comparisonEligibleCaseIds', strings(0, 1), ...
    'caseSummary', repmat(summaryTemplate(), 0, 1), ...
    'comparisonContract', struct( ...
        'sameBoundaryRequired', true, ...
        'sameSolverRequired', true, ...
        'sameInitializationRequired', true, ...
        'excludedFromEngineeringConclusion', ...
            ["liquid_water_inventory"; "liquid_transport"; ...
             "separator_efficiency"; "compressor_parasitic_power"]));

if ~isstruct(study) || ~isfield(study, 'cases') || isempty(study.cases)
    return;
end

rows = repmat(summaryTemplate(), numel(study.cases), 1);
for idx = 1:numel(study.cases)
    item = study.cases(idx);
    rows(idx).caseId = string(item.caseId);
    rows(idx).passed = logical(getField(item, 'passed', false));
    rows(idx).simCompleted = logical(getField(item, 'simCompleted', false));
    rows(idx).failureCategory = string(getField(item, ...
        'failureCategory', ""));
    if ~isfield(item, 'performance') || ~isstruct(item.performance)
        continue;
    end
    p = item.performance;
    rows(idx).status = string(getField(p, 'status', "not_available"));
    rows(idx).comparisonEligible = logical(getField(p, ...
        'comparisonEligible', false));
    if isfield(p, 'electrical')
        rows(idx).current_A = p.electrical.current_A;
        rows(idx).voltage_V = p.electrical.voltage_V;
        rows(idx).power_kW = p.electrical.power_kW;
        rows(idx).currentDensity_A_cm2 = p.electrical.currentDensity_A_cm2;
        rows(idx).powerDensity_kW_cm2 = p.electrical.powerDensity_kW_cm2;
    end
    if isfield(p, 'cegr')
        rows(idx).targetCegrRatio = getField(p.cegr, 'targetRatio', NaN);
        rows(idx).actualCegrRatioSplitBasis = getField(p.cegr, ...
            'actualRatioSplitBasis', NaN);
        rows(idx).splitReturnMdot_kg_s = getField(p.cegr, ...
            'splitReturnMdot_kg_s', NaN);
        rows(idx).splitExhaustMdot_kg_s = getField(p.cegr, ...
            'splitExhaustMdot_kg_s', NaN);
        rows(idx).splitTotalMdot_kg_s = getField(p.cegr, ...
            'splitTotalMdot_kg_s', NaN);
        rows(idx).actualCegrRatioMixBasis = getField(p.cegr, ...
            'actualRatioMixBasis', NaN);
        rows(idx).actualCegrRatioFreshBasis = getField(p.cegr, ...
            'actualRatioFreshBasis', NaN);
    end
    if isfield(p, 'cathode')
        rows(idx).lambda = p.cathode.oxygenStoich_lambda;
        rows(idx).oxygenPartialPressure_Pa = ...
            p.cathode.compressorInletO2PartialPressure_Pa;
        rows(idx).freshAirWaterVaporMdot_kg_s = getField(p.cathode, ...
            'freshAirWaterVaporMdot_kg_s', NaN);
        rows(idx).cathodeInletWaterVaporMdot_kg_s = getField(p.cathode, ...
            'cathodeInletWaterVaporMdot_kg_s', NaN);
        rows(idx).cathodeOutletWaterVaporMdot_kg_s = getField(p.cathode, ...
            'cathodeOutletWaterVaporMdot_kg_s', NaN);
        rows(idx).cathodeInletRH = p.cathode.cathodeInletRH;
    end
    if isfield(p, 'thermal')
        rows(idx).stackTemperature_C = p.thermal.stackTemperature_C;
        rows(idx).stackTemperatureSet_C = p.thermal.stackTemperatureSet_C;
    end
    if isfield(p, 'water')
        rows(idx).mixerCondensationRate_kg_s = ...
            p.water.mixerCondensationRate_kg_s;
        rows(idx).mixerSaturationRatio = p.water.mixerSaturationRatio;
    end
    if isfield(p, 'pressure') && isstruct(p.pressure) && ...
            isfield(p.pressure, 'chain')
        chain = p.pressure.chain;
        rows(idx).compressorDischargePressure_MPa = ...
            chain.compressorDischargePressure_MPa;
        rows(idx).compressorAfterIntercoolerPressure_MPa = ...
            chain.compressorAfterIntercoolerPressure_MPa;
        rows(idx).stackCathodeChannelPressure_MPa = ...
            chain.stackCathodeChannelPressure_MPa;
        rows(idx).cathodeOutletPressure_MPa = ...
            chain.cathodeOutletPressure_MPa;
        rows(idx).compressorToCathodeMargin_MPa = ...
            chain.compressorAfterIntercoolerToCathodeOutletMargin_MPa;
        rows(idx).cathodeChannelToOutletDrop_MPa = ...
            chain.stackCathodeChannelToCathodeOutletDrop_MPa;
    end
    if isfield(p, 'antiCondensation') && ...
            isstruct(p.antiCondensation) && ...
            isfield(p.antiCondensation, 'mixer')
        mixer = p.antiCondensation.mixer;
        rows(idx).mixerTemperature_C = mixer.temperature_C;
        rows(idx).mixerDewPoint_C = mixer.dewPointTemperature_C;
        rows(idx).mixerDewPointMargin_C = mixer.dewPointMargin_C;
        rows(idx).temperatureLiftRequired_C = ...
            mixer.temperatureLiftRequired_C;
        rows(idx).sensibleHeatProxy_kW = ...
            p.antiCondensation.measures.sensibleHeatProxy_kW;
    end
end

eligible = [rows.comparisonEligible];
analysis.caseSummary = rows;
analysis.comparisonEligibleCaseIds = [rows(eligible).caseId].';
if any(eligible)
    analysis.status = "behavior_verified_for_eligible_cases";
else
    analysis.status = "executed_but_no_case_is_comparison_eligible";
end
end

function value = getField(s, name, default)
if isstruct(s) && isfield(s, name) && ~isempty(s.(name))
    value = s.(name);
else
    value = default;
end
end

function value = summaryTemplate()
value = struct( ...
    'caseId', "", ...
    'status', "not_available", ...
    'passed', false, ...
    'simCompleted', false, ...
    'comparisonEligible', false, ...
    'failureCategory', "", ...
    'current_A', NaN, ...
    'voltage_V', NaN, ...
    'power_kW', NaN, ...
    'currentDensity_A_cm2', NaN, ...
    'powerDensity_kW_cm2', NaN, ...
    'targetCegrRatio', NaN, ...
    'actualCegrRatioSplitBasis', NaN, ...
    'splitReturnMdot_kg_s', NaN, ...
    'splitExhaustMdot_kg_s', NaN, ...
    'splitTotalMdot_kg_s', NaN, ...
    'actualCegrRatioMixBasis', NaN, ...
    'actualCegrRatioFreshBasis', NaN, ...
    'lambda', NaN, ...
    'oxygenPartialPressure_Pa', NaN, ...
    'freshAirWaterVaporMdot_kg_s', NaN, ...
    'cathodeInletWaterVaporMdot_kg_s', NaN, ...
    'cathodeOutletWaterVaporMdot_kg_s', NaN, ...
    'cathodeInletRH', NaN, ...
    'stackTemperature_C', NaN, ...
    'stackTemperatureSet_C', NaN, ...
    'mixerCondensationRate_kg_s', NaN, ...
    'mixerSaturationRatio', NaN, ...
    'compressorDischargePressure_MPa', NaN, ...
    'compressorAfterIntercoolerPressure_MPa', NaN, ...
    'stackCathodeChannelPressure_MPa', NaN, ...
    'cathodeOutletPressure_MPa', NaN, ...
    'compressorToCathodeMargin_MPa', NaN, ...
    'cathodeChannelToOutletDrop_MPa', NaN, ...
    'mixerTemperature_C', NaN, ...
    'mixerDewPoint_C', NaN, ...
    'mixerDewPointMargin_C', NaN, ...
    'temperatureLiftRequired_C', NaN, ...
    'sensibleHeatProxy_kW', NaN);
end
