function assessment = routeA_focused_cegr_screen_assessment(study)
% Summarize low-load cEGR behavior-screening outputs without calibration claims.

if ~isstruct(study) || ~isfield(study, 'cases')
    error('RouteA:FocusedCEGRScreenStudy', ...
        'study must be a focused-study result with a cases field.');
end

rows = repmat(rowTemplate(), numel(study.cases), 1);
for idx = 1:numel(study.cases)
    item = study.cases(idx);
    row = rowTemplate();
    row.caseId = string(getField(item, 'caseId', ""));
    row.simCompleted = logical(getField(item, 'simCompleted', false));
    row.localNumericsPassed = logical(getField(item, 'passed', false));
    row.errorId = string(getField(item, 'errorId', ""));
    if isfield(item, 'caseCfg') && isstruct(item.caseCfg)
        row.targetRSplitCommand = getNested(item.caseCfg, ...
            {'cegr', 'targetRatio'}, NaN);
    end
    if isfield(item, 'performance') && isstruct(item.performance)
        row = collectPerformance(row, item.performance);
    end
    rows(idx) = row;
end

assessment = struct( ...
    'schemaVersion', "RouteA_Focused_CEGRScreenAssessment_v02", ...
    'scope', "low_load_cegr_behavior_and_mechanism_screening_only", ...
    'targetDefinition', ...
        "commanded_cegr_ratio_is_screened_against_observed_branch_r_split", ...
    'rows', rows, ...
    'allCasesCompleted', all([rows.simCompleted]), ...
    'allCasesLocalNumericsPassed', all([rows.localNumericsPassed]), ...
    'engineeringSelectionAllowed', false, ...
    'performanceCalibrationClaimAllowed', false);
end

function row = collectPerformance(row, performance)
if isfield(performance, 'electrical')
    row.currentDensity_A_cm2 = getField(performance.electrical, ...
        'currentDensity_A_cm2', NaN);
    row.cellVoltage_V = getField(performance.electrical, 'cellVoltage_V', NaN);
end
if isfield(performance, 'cegr')
    cegr = performance.cegr;
    row.actualRSplit = getField(cegr, 'actualRatioSplitBasis', NaN);
    row.mCegr_kg_s = getField(cegr, 'massFlow_kg_s', NaN);
    row.mCegrOverFresh = getField(cegr, 'actualRatioFreshBasis', NaN);
    row.mCegrOverMix = getField(cegr, 'actualRatioMixBasis', NaN);
    row.cegrValveAreaFraction = getField(cegr, 'valveAreaFraction', NaN);
    row.cegrValveDeltaP_MPa = getField(cegr, 'valveDeltaP_MPa', NaN);
end
if isfield(performance, 'cathode')
    cathode = performance.cathode;
    row.mFreshH2O_kg_s = getField(cathode, ...
        'freshAirWaterVaporMdot_kg_s', NaN);
    row.mCathodeInletH2O_kg_s = getField(cathode, ...
        'cathodeInletWaterVaporMdot_kg_s', NaN);
    row.mCathodeOutletH2O_kg_s = getField(cathode, ...
        'cathodeOutletWaterVaporMdot_kg_s', NaN);
    row.cathodeInletRH = getField(cathode, 'cathodeInletRH', NaN);
    row.compressorInletPO2_Pa = getField(cathode, ...
        'compressorInletO2PartialPressure_Pa', NaN);
    row.actualOER = getField(cathode, 'oxygenStoich_lambda', NaN);
end
if isfield(performance, 'pressure') && isstruct(performance.pressure) && ...
        isfield(performance.pressure, 'chain')
    chain = performance.pressure.chain;
    row.compressorInletPressure_MPa = getField(chain, ...
        'compressorInletMixerPressure_MPa', NaN);
    row.compressorDischargePressure_MPa = getField(chain, ...
        'compressorDischargePressure_MPa', NaN);
    row.compressorAfterIntercoolerPressure_MPa = getField(chain, ...
        'compressorAfterIntercoolerPressure_MPa', NaN);
    row.stackCathodePressure_MPa = getField(chain, ...
        'stackCathodeChannelPressure_MPa', NaN);
    row.cathodeOutletPressure_MPa = getField(chain, ...
        'cathodeOutletPressure_MPa', NaN);
end
if isfield(performance, 'antiCondensation') && ...
        isstruct(performance.antiCondensation) && ...
        isfield(performance.antiCondensation, 'mixer')
    row.mixerDewPointMargin_C = getField(performance.antiCondensation.mixer, ...
        'dewPointMargin_C', NaN);
end
if isfield(performance, 'water')
    row.compressorInletSaturationRatio = getField(performance.water, ...
        'mixerSaturationRatio', NaN);
end
end

function row = rowTemplate()
row = struct( ...
    'caseId', "", ...
    'simCompleted', false, ...
    'localNumericsPassed', false, ...
    'errorId', "", ...
    'currentDensity_A_cm2', NaN, ...
    'cellVoltage_V', NaN, ...
    'targetRSplitCommand', NaN, ...
    'actualRSplit', NaN, ...
    'actualOER', NaN, ...
    'mCegr_kg_s', NaN, ...
    'mCegrOverFresh', NaN, ...
    'mCegrOverMix', NaN, ...
    'cegrValveAreaFraction', NaN, ...
    'cegrValveDeltaP_MPa', NaN, ...
    'mFreshH2O_kg_s', NaN, ...
    'mCathodeInletH2O_kg_s', NaN, ...
    'mCathodeOutletH2O_kg_s', NaN, ...
    'cathodeInletRH', NaN, ...
    'compressorInletPO2_Pa', NaN, ...
    'compressorInletPressure_MPa', NaN, ...
    'compressorDischargePressure_MPa', NaN, ...
    'compressorAfterIntercoolerPressure_MPa', NaN, ...
    'stackCathodePressure_MPa', NaN, ...
    'cathodeOutletPressure_MPa', NaN, ...
    'mixerDewPointMargin_C', NaN, ...
    'compressorInletSaturationRatio', NaN);
end

function value = getNested(s, path, default)
value = s;
for idx = 1:numel(path)
    if ~isstruct(value) || ~isfield(value, path{idx}) || ...
            isempty(value.(path{idx}))
        value = default;
        return;
    end
    value = value.(path{idx});
end
end

function value = getField(s, fieldName, default)
if isstruct(s) && isfield(s, fieldName) && ~isempty(s.(fieldName))
    value = s.(fieldName);
else
    value = default;
end
end
