function params = routeA_focused_parameter_defaults(modelId)
% Return defaults for the focused cathode-cEGR research model.
%
% Shared Route A platform values remain the source for environment and
% solver defaults. The active focused model is sized from the explicit
% 240 kW external test case; its geometry and BOP assumptions remain
% visible rather than being promoted to platform defaults.

if nargin < 1
    modelId = "focused_legacy";
end
paths = routeA_focused_paths(modelId);
addpath(char(paths.sharedScriptDir));
platform = routeA_platform_default_parameters();

params = struct();
params.modelId = paths.modelId;
params.modelName = paths.modelName;
params.sourceModelName = ...
    "PEMFuelCellSystem_GasMixture_cEGR_RouteA_v01";
params.parameterLayer = "external_case";
params.externalCase = struct( ...
    'id', "240kW_stack_606cell_380cm2", ...
    'source', "00_支撑材料/01_项目系统实验数据/240kw电堆数据.txt", ...
    'scope', "stack_geometry_airflow_cathode_pressure_drop_and_BOP_screening", ...
    'extrapolation', "iL_above_1p9_Acm2_and_BOP_capacity_are_screening_assumptions");
params.architectureId = ...
    "Passive_SelfHumidifying_PostSeparatorGas_CompressorInlet";
params.targetArchitectureId = ...
    "Passive_ExternalMembraneHumidifier_PostSeparatorGas_CompressorInlet";
params.architecture = struct( ...
    'drive', "passive_pressure_difference", ...
    'stackHumidification', "self_humidifying_external_MIn_disabled", ...
    'takeoff', "post_separator_gas_boundary", ...
    'returnLocation', "compressor_inlet", ...
    'controlLayer', "common_backpressure_and_return_valve", ...
    'backpressureLocation', "common_pre_split", ...
    'separatorStatus', "gas_phase_L2_no_composition_change", ...
    'status', "P3_self_humidifying_configuration_in_progress");

% The external case is used to design the BOP around the stack, not to
% accept the legacy compressor map as a hardware constraint.
params.designPoint = struct( ...
    'currentDensity_A_cm2', 1.6, ...
    'current_A', 608, ...
    'power_kW', 241.33344, ...
    'freshAirMdot_kg_s', 0.22961, ...
    'stackInletPressure_MPa_abs', 0.2356391, ...
    'stackOutletPressure_MPa_abs', 0.2029417, ...
    'stackChannelDrop_MPa', 0.0326974, ...
    'source', "external_case_240kW_606cell_380cm2_interpolated_j1p6");

params.ejector = struct( ...
    'enabled', false, ...
    'status', "disabled_until_constitutive_rebuild", ...
    'areaThroat_m2', 4.2e-4, ...
    'areaRatioNozzle', 3.0, ...
    'areaRatioMixing', 8.0, ...
    'minAreaRatioSecondary', 0.3, ...
    'efficiencyPrimary', 0.90, ...
    'efficiencySecondary', 0.82, ...
    'efficiencyExpansion', 0.80, ...
    'efficiencyMixing', 0.78, ...
    'areaA_m2', 1.25e-3, ...
    'areaB_m2', 1.25e-3, ...
    'areaS_m2', 8.0e-4, ...
    'pressureRecovery', 1.05, ...
    'pressureSmoothing_Pa', 1e-6, ...
    'mdotSmoothing_kg_s', 1e-8, ...
    'activePressureMarginMin_MPa', 0.015, ...
    'targetSplitRatio', 0.10, ...
    'reverseFlowPolicy', "isolate_and_bypass");

if params.modelId == "ejector_self_humidifying"
    params.sourceModelName = ...
        "PEMFuelCellSystem_Cathode_cEGR_SelfHumidifying_v01";
    params.architectureId = ...
        "Passive_Ejector_PostSeparatorGas_PostCompressorCathodeInlet";
    params.targetArchitectureId = params.architectureId;
    params.architecture = struct( ...
        'drive', "ejector_primary_pressure_difference", ...
        'stackHumidification', "self_humidifying_external_MIn_disabled", ...
        'takeoff', "post_intercooler_primary", ...
        'returnLocation', "post_compressor_cathode_inlet", ...
        'controlLayer', "compressor_common_backpressure_and_ejector_geometry", ...
        'backpressureLocation', "common_pre_split", ...
        'separatorStatus', "gas_phase_L2_no_composition_change", ...
        'status', "E3_ejector_structure_in_progress");
end

params.stack = struct( ...
    'numCells', 606, ...
    'area_cm2', 380, ...
    'iL_A_cm2', 2.5, ...
    ... % Effective values for the declared 240 kW external no-cEGR case.
    'io_A_cm2', 2e-14, ...
    'alpha', 1.0, ...
    'temperature_C', 80, ...
    'temperatureSource', "focused_stack_temperature_C", ...
    'cathodeGasTemperature_C', 80, ...
    'cathodeGasTemperatureSource', "focused_cathode_inlet_temperature_C");

params.anode = struct( ...
    'feedPressure_MPa_abs', ...
        platform.controls.anode_source_pressure_MPa_abs.value, ...
    'inletMdot_kg_s', 0.008, ...
    'outletPressure_MPa_abs', ...
        platform.environment.ambient_p_MPa_abs.value, ...
    'boundaryTemperature_C', platform.environment.ambient_T_C.value, ...
    'hydrogenMoleFraction', platform.anode.tank.yH2.value, ...
    'pipeLength_m', 1, ...
    'pipeDiameter_m', 0.056, ...
    'pipeArea_m2', pi * 0.056^2 / 4, ...
    'pipeExtraLength_m', 0.1, ...
    'pipeRoughness_m', 15e-6);

params.cathode = struct( ...
    'sourcePressure_MPa_abs', ...
        platform.environment.ambient_p_MPa_abs.value, ...
    'sourceTemperature_C', ...
        platform.controls.cathode_source_temperature_C.value, ...
    'channelDpNominal_MPa', 0.0300, ...
    ... % 606 cells, 721 A, lambda_O2=1.8, 20 C/50 pct RH inlet air.
    'channelMdotNominal_kg_s', 0.278837, ...
    'channelFlowArea_m2', pi * 0.0717^2 / 4, ...
    'channelLaminarFraction', 0.80, ...
    'commonBackpressureValveMaxArea_m2', 0.00134, ...
    'commonBackpressureValveOpenMinArea_m2', 1e-10, ...
    'commonBackpressureValveKi_area_per_MPa_s', 0.002);

params.bop = struct( ...
    'compressorMap', struct( ...
        'rpm_TLU', [0, 50000, 80000], ...
        'p_ratio_TLU', [1; 1.5; 2; 2.5; 3], ...
        'mdot_corr_TLU', [ ...
            0, 0.28, 0.56; ...
            0, 0.26, 0.52; ...
            0, 0.24, 0.48; ...
            0, 0.22, 0.44; ...
            0, 0.20, 0.40]), ...
    'intercoolerMdotNominal_kg_s', 0.40798, ...
    'intercoolerDpNominal_MPa', 0.005, ...
    'intercoolerArea_m2', pi * 0.1^2 / 4, ...
    'separatorMdotNominal_kg_s', 0.40798, ...
    'separatorDpNominal_MPa', 0.002, ...
    'separatorArea_m2', pi * 0.072^2 / 4, ...
    'cegrValveMaxArea_m2', 0.001, ...
    'cegrPipeDiameter_m', 0.072, ...
    'design', struct( ...
        'compressorRatedMdot_kg_s', 0.230, ...
        'compressorDesignMdot_kg_s', 0.330, ...
        'compressorRatedPressureRatio', 2.60, ...
        'compressorMaximumPressureRatio', 3.00, ...
        'compressorSurgeMarginFraction', 0.15, ...
        'compressorEfficiencyAssumption', 0.75, ...
        'compressorDesignStatus', "external_case_assumption_not_hardware_validation", ...
        'intercoolerPressureDropMax_MPa', 0.005, ...
        'intercoolerOutletTemperatureTarget_C', [50, 65], ...
        'primaryTakeoffLocation', "post_intercooler", ...
        'stackInletPressureTarget_MPa_abs', [0.230, 0.245], ...
        'stackOutletPressureTarget_MPa_abs', [0.195, 0.210], ...
        'separatorPressureDropMax_MPa', 0.003, ...
        'separatorLiquidCarryoverStatus', "gas_phase_L2_boundary_only", ...
        'ratedSplitRatioRange', [0.05, 0.15]));

params.interface = struct( ...
    'schemaVersion', "RouteA_Focused_ParameterBridge_v01", ...
    'anodeBoundary', "mass_flow_inlet_pressure_outlet", ...
    'thermalBoundary', "fixed_temperature_source", ...
    'standardAnodePressureMapping', ...
        "controls.anode.sourcePressure_MPa_abs -> focused_anode_feed_p_MPa_abs", ...
    'standardAnodeTemperatureMapping', ...
        "controls.anode.sourceTemperature_C -> focused_anode_boundary_T_C", ...
    'standardAnodeCompositionMapping', ...
        "controls.anode.h2MoleFraction -> focused_anode_yH2", ...
    'cathodeSourceTemperatureMapping', ...
        "controls.cathode.sourceTemperature_C -> env_T", ...
    'airInletPressureSource', ...
        "controls.environment.ambientPressure_MPa_abs -> env_p", ...
    'cathodeChannelResistanceMapping', ...
        "focused.cathodeChannel* -> cathode_channel_*", ...
    'electrochemistryMapping', ...
        "MEA mask parameters are configured directly in the external-case model", ...
    'freshAirHumidityMapping', ...
        "environment(T,p,RH) -> cathode.freshAirWaterMoleFraction -> env_yH20", ...
    'commonBackpressureValveMapping', ...
        "focused.commonBackpressureValve* -> common_bp_valve_*", ...
    'ejectorMapping', ...
        "ejector.* -> FuelCell Ejector (FC) compile-time parameters", ...
    'standardThermalMapping', ...
        "controls.thermal.stackTemperatureSet_C -> focused_stack_temperature_C", ...
    'notApplicablePolicy', ...
        "removed_BOP_parameters_are_reported_not_applied");

params.solver = struct( ...
    'solver', platform.numerics.solver.value, ...
    'relTol', platform.numerics.relTol.value, ...
    'absTol', platform.numerics.absTol.value, ...
    'maxStep_s', platform.numerics.maxStep_s.value, ...
    'stopTime_s', platform.numerics.stopTime_s.value);

params.environment = struct( ...
    'ambientTemperature_C', platform.environment.ambient_T_C.value, ...
    'ambientPressure_MPa_abs', platform.environment.ambient_p_MPa_abs.value, ...
    'ambientRelativeHumidity', 0.5);
end
