function analysis = routeA_focused_anti_condensation_analysis( ...
    result, pressure, water, context)
% Screen dew-point and anti-condensation measures from existing gas results.
%
% This is a gas-phase engineering screen. It does not add a heater, dryer,
% separator efficiency, liquid inventory, or liquid carryover model.

analysis = struct( ...
    'schemaVersion', "RouteA_Focused_AntiCondensation_v01", ...
    'status', "not_available", ...
    'engineeringConclusionAllowed', false, ...
    'screeningSpecificHeat_J_kgK', 1005, ...
    'mixer', mixerTemplate(), ...
    'measures', measuresTemplate(), ...
    'definitions', struct( ...
        'dewPoint', "temperature where p_sat(T_dew)=y_H2O*p_abs", ...
        'temperatureLift', "max(T_dew-T_mixer,0)", ...
        'vaporReduction', "max(1-p_sat(T_mixer)/(y_H2O*p_abs),0)", ...
        'separatorBoundary', ...
            "liquid removal after condensation; not vapor drying"));

if ~isstruct(result) || ~isstruct(pressure) || ...
        ~isstruct(water) || ~isstruct(context) || ...
        ~isfield(pressure, 'chain')
    return;
end

chain = pressure.chain;
if any(~isfinite([chain.compressorInletMixerPressure_MPa, ...
        chain.compressorInletMixerTemperature_K]))
    return;
end

y = chain.compressorInletMixerMoleFraction;
if numel(y) < 4 || any(~isfinite(y))
    return;
end

pMPa = chain.compressorInletMixerPressure_MPa;
temperatureC = chain.compressorInletMixerTemperature_K - 273.15;
yH2O = max(y(4), 0);
pH2O_MPa = yH2O * pMPa;
pSat_MPa = saturationPressure_MPa(temperatureC);
saturationRatio = pH2O_MPa / max(pSat_MPa, eps);
dewPointC = dewPointTemperature_C(pH2O_MPa);
liftC = max(dewPointC - temperatureC, 0);

condensationRate = NaN;
condensationIntegral = NaN;
waterNode = findNode(water, "compressor_inlet_mixer");
if ~isempty(waterNode) && waterNode.status == "collected" && ...
        isfield(waterNode, 'condensation')
    condensationRate = waterNode.condensation.mean_kg_s;
    condensationIntegral = waterNode.condensation.integral_kg;
end

mixedMdot = NaN;
if isfield(result, 'tail') && isfield(result.tail, 'compressorMdot_kg_s')
    mixedMdot = result.tail.compressorMdot_kg_s.mean;
end
heatProxy = mixedMdot * analysis.screeningSpecificHeat_J_kgK * liftC / 1000;

analysis.mixer = struct( ...
    'pressure_MPa_abs', pMPa, ...
    'temperature_C', temperatureC, ...
    'waterMoleFraction', yH2O, ...
    'waterVaporPressure_MPa', pH2O_MPa, ...
    'saturationPressure_MPa', pSat_MPa, ...
    'saturationRatio', saturationRatio, ...
    'dewPointTemperature_C', dewPointC, ...
    'dewPointMargin_C', temperatureC - dewPointC, ...
    'temperatureLiftRequired_C', liftC, ...
    'condensationRate_kg_s', condensationRate, ...
    'condensationIntegral_kg', condensationIntegral, ...
    'mixedMassFlow_kg_s', mixedMdot);

analysis.measures = struct( ...
    'requiredVaporReductionFraction', max(1 - pSat_MPa / ...
        max(pH2O_MPa, eps), 0), ...
    'sensibleHeatProxy_kW', heatProxy, ...
    'liquidRemovalAtEfficiency', liquidRemovalScreen( ...
        condensationRate, [0, 0.9, 0.99, 0.999]), ...
    'recommendedOrder', recommendation(analysis.mixer));
analysis.status = "collected_gas_phase_screening";
end

function value = mixerTemplate()
value = struct( ...
    'pressure_MPa_abs', NaN, ...
    'temperature_C', NaN, ...
    'waterMoleFraction', NaN, ...
    'waterVaporPressure_MPa', NaN, ...
    'saturationPressure_MPa', NaN, ...
    'saturationRatio', NaN, ...
    'dewPointTemperature_C', NaN, ...
    'dewPointMargin_C', NaN, ...
    'temperatureLiftRequired_C', NaN, ...
    'condensationRate_kg_s', NaN, ...
    'condensationIntegral_kg', NaN, ...
    'mixedMassFlow_kg_s', NaN);
end

function value = measuresTemplate()
value = struct( ...
    'requiredVaporReductionFraction', NaN, ...
    'sensibleHeatProxy_kW', NaN, ...
    'liquidRemovalAtEfficiency', repmat(efficiencyTemplate(), 0, 1), ...
    'recommendedOrder', strings(0, 1));
end

function values = liquidRemovalScreen(rate, efficiencies)
values = repmat(efficiencyTemplate(), numel(efficiencies), 1);
for idx = 1:numel(efficiencies)
    values(idx).efficiency = efficiencies(idx);
    values(idx).inletCondensationRate_kg_s = rate;
    values(idx).residualLiquidCarryover_kg_s = rate * (1 - efficiencies(idx));
end
end

function value = efficiencyTemplate()
value = struct( ...
    'efficiency', NaN, ...
    'inletCondensationRate_kg_s', NaN, ...
    'residualLiquidCarryover_kg_s', NaN);
end

function value = recommendation(mixer)
if mixer.temperatureLiftRequired_C > 0
    value = ["first_raise_mixer_or_recycle_temperature"; ...
        "then_remove_any_condensed_liquid_before_compressor"; ...
        "do_not_use_liquid_separator_as_vapor_dryer"];
else
    value = ["temperature_margin_is_nonnegative_for_this_case"; ...
        "still_provide_liquid_carryover_protection_before_compressor"];
end
end

function node = findNode(water, name)
node = [];
if ~isfield(water, 'nodes') || isempty(water.nodes)
    return;
end
for idx = 1:numel(water.nodes)
    if water.nodes(idx).name == name
        node = water.nodes(idx);
        return;
    end
end
end

function pMPa = saturationPressure_MPa(temperatureC)
pSat_kPa = 0.61121 .* exp((18.678 - temperatureC ./ 234.5) .* ...
    (temperatureC ./ (257.14 + temperatureC)));
pMPa = max(pSat_kPa * 1e-3, 1e-12);
end

function temperatureC = dewPointTemperature_C(pWaterMPa)
if ~isfinite(pWaterMPa) || pWaterMPa <= 0
    temperatureC = -Inf;
    return;
end
low = -40;
high = 120;
if pWaterMPa >= saturationPressure_MPa(high)
    temperatureC = high;
    return;
end
if pWaterMPa <= saturationPressure_MPa(low)
    temperatureC = low;
    return;
end
for idx = 1:80
    mid = (low + high) / 2;
    if saturationPressure_MPa(mid) < pWaterMPa
        low = mid;
    else
        high = mid;
    end
end
temperatureC = (low + high) / 2;
end
