function [totalFlowStudy, totalFlowMatrix, freshAirStudy, freshAirMatrix] = ...
    routeA_focused_external240kw_cegr_matrix_case_factory(overrides)
% Build the two formal 240-kW V-SH passive-cEGR screening batches.
%
% Run the returned studies separately with run_routeA_focused_study:
%   totalResult = run_routeA_focused_study(totalFlowStudy);
%   freshResult = run_routeA_focused_study(freshAirStudy);
%
% These studies are bound to the current V-SH topology:
%   stack cathode outlet -> ideal split -> V_EGR -> compressor inlet
%                                     -> V_BP  -> ambient exhaust.
% The v02 result filenames are deliberately retained so a completed rerun
% replaces the invalid valve-after-split matrix results in place. Do not
% merge old and new MAT rows.
%
% The canonical study coordinate is R_EGR=m_return/m_fresh at the
% compressor inlet. The existing valve controller accepts x_EGR=m_return/
% m_total, so every case applies x_EGR=R_EGR/(1+R_EGR) explicitly.
% Batch A keeps total compressor-inlet flow at the reference OER for each
% load. Batch B keeps that reference fresh-air flow and uses mode 4 to
% increase total compressor flow as cEGR increases.

if nargin < 1 || isempty(overrides)
    overrides = struct();
end
settings = defaultSettings(overrides);
conditions = recommendedConditions();

[totalCases, totalRows] = buildCases(conditions, settings, "total_flow_fixed");
[freshCases, freshRows] = buildCases(conditions, settings, "fresh_air_fixed");
contract = screenContract();

totalFlowStudy = studyConfig(totalCases, settings, contract, "total_flow_fixed");
freshAirStudy = studyConfig(freshCases, settings, contract, "fresh_air_fixed");
totalFlowMatrix = matrixDescriptor(totalRows, conditions, settings, contract, ...
    "total_flow_fixed");
freshAirMatrix = matrixDescriptor(freshRows, conditions, settings, contract, ...
    "fresh_air_fixed");
end

function [cases, rows] = buildCases(conditions, settings, strategy)
switch strategy
    case "total_flow_fixed"
        ratioCount = numel(settings.totalFlowFractions);
    case "fresh_air_fixed"
        ratioCount = numel(settings.freshAirRecirculationR);
    otherwise
        error('RouteA:External240kWCEGRStrategy', 'Unknown flow strategy.');
end
caseCount = numel(conditions) * ratioCount;
cases = struct([]);
rows = repmat(rowTemplate(), caseCount, 1);
caseIndex = 0;
for conditionIndex = 1:numel(conditions)
    condition = conditions(conditionIndex);
    if strategy == "total_flow_fixed"
        recirculationR = (condition.referenceOER - 1) * ...
            settings.totalFlowFractions;
    else
        recirculationR = settings.freshAirRecirculationR;
    end
    for ratioIndex = 1:numel(recirculationR)
        R = recirculationR(ratioIndex);
        x = R / (1 + R);
        [caseCfg, ~] = routeA_focused_external240kw_case_factory( ...
            condition.currentDensity_A_cm2, struct( ...
            'cegrEnabled', R > 0, 'cegrTargetRatio', x));
        caseCfg = applyRecommendedCondition(caseCfg, condition);
        if strategy == "total_flow_fixed"
            caseCfg.air.modeId = 2;
            flowPolicy = "total_compressor_inlet_mdot_held_at_reference_OER";
        else
            caseCfg.air.modeId = 4;
            flowPolicy = "fresh_air_mdot_held_at_reference_OER_total_mdot_increases";
        end
        caseCfg.air.targetOer = condition.referenceOER;
        caseCfg.cegr.enabled = logical(R > 0);
        caseCfg.cegr.controlMode = 1;
        caseCfg.cegr.targetRatio = x;
        caseCfg.cegr.targetRecirculationR = R;
        caseCfg.cegr.profile = struct( ...
            'kind', "ramp", 'start_value', 0, 'end_value', x, ...
            'start_s', 0, 'end_s', settings.startupRampDuration_s);
        caseCfg.flowControlPolicy = flowPolicy;
        caseCfg.caseId = "external240_" + strategy + "_j" + ...
            numericLabel(condition.currentDensity_A_cm2, 1) + "_R" + ...
            numericLabel(R, 3);
        caseCfg.description = "External 240 kW V-SH passive cEGR; " + ...
            "strategy=" + strategy + ", R_EGR=m_return/m_fresh=" + ...
            string(R) + ", controller x_EGR=" + string(x) + ...
            ", reference OER=" + string(condition.referenceOER);
        caseIndex = caseIndex + 1;
        if caseIndex == 1
            cases = repmat(caseCfg, caseCount, 1);
        end
        cases(caseIndex) = caseCfg;
        rows(caseIndex) = buildRow(caseCfg, condition, R, x, strategy, ...
            flowPolicy);
    end
end
end

function caseCfg = applyRecommendedCondition(caseCfg, condition)
% Workbook cathode pressure is user-confirmed gauge pressure. The current
% V-SH stack-outlet pressure anchor receives ambient plus the workbook value;
% the ideal split then feeds V_EGR and V_BP. The gas temperature is the
% model's lumped compressor/intercooler boundary.
caseCfg.cathode.outletPressure_MPa_abs = ...
    condition.ambientPressure_MPa_abs + condition.cathodePressureGauge_kPa * 1e-3;
caseCfg.thermal.stackTemperatureSet_C = condition.stackTemperature_C;
caseCfg.focused.stackTemperature_C = condition.stackTemperature_C;
caseCfg.focused.cathodeGasTemperature_C = condition.cathodeGasTemperature_C;
caseCfg.recommendedTestCondition = condition;
end

function cfg = studyConfig(cases, settings, contract, strategy)
resultDir = fullfile(fileparts(mfilename('fullpath')), '..', '..', ...
    '02_结果', 'RouteA_Cathode_cEGR_Focused', 'outputs', ...
    '20260820_vsh_validation');
if isfield(settings, 'resultDir') && strlength(string(settings.resultDir)) > 0
    resultDir = char(settings.resultDir);
end
fileStem = "RouteA_Focused_External240kW_VSH_PassiveCEGR_" + strategy + ...
    "_4J_600s_20260820.mat";
if isfield(settings, 'resultTag') && strlength(string(settings.resultTag)) > 0
    fileStem = "RouteA_Focused_External240kW_VSH_PassiveCEGR_" + strategy + ...
        "_4J_600s_" + string(settings.resultTag) + ".mat";
end
cfg = struct( ...
    'modelId', "self_humidifying", ...
    'calculationType', "steady", ...
    'cases', cases, ...
    'researchDuration_s', settings.researchDuration_s, ...
    'tailLogicalWindow_s', settings.tailLogicalWindow_s, ...
    'steadyWindowDuration_s', settings.steadyWindowDuration_s, ...
    'retainSimulationOutputs', false, ...
    'executionMode', "parallel", ...
    'parallel', struct('poolProfile', settings.poolProfile, ...
        'workerCount', settings.workerCount, 'showProgress', true, ...
        'useFastRestart', false), ...
    'resultFile', string(fullfile(resultDir, fileStem)), ...
    'cegrScreenContract', contract);
end

function matrix = matrixDescriptor(rows, conditions, settings, contract, strategy)
matrix = struct( ...
    'schemaVersion', "RouteA_External240kW_VSH_CEGRMatrix_v03", ...
    'parameterLayer', "external_case", ...
    'purpose', "passive_cegr_pressure_temperature_oxygen_and_gas_phase_screen", ...
    'flowStrategy', strategy, ...
    'canonicalTargetDefinition', ...
        "R_EGR=m_return_over_m_fresh_at_compressor_inlet", ...
    'controllerTargetDefinition', ...
        "x_EGR=m_return_over_m_total=R_EGR_over_1_plus_R_EGR", ...
    'topology', contract.topology, ...
    'pressureReadbackContract', contract.pressureReadback, ...
    'resultReplacementPolicy', ...
        "overwrite_v02_only_after_each_complete_current_topology_batch;_do_not_merge_with_valve-after-split_rows", ...
    'actualOERObservable', ...
        "cathode_inlet_species_mdot_and_stack_current_tail_minimum", ...
    'recommendedConditions', conditions, ...
    'rows', rows, ...
    'auditTable', struct2table(rows), ...
    'caseCount', numel(rows), ...
    'totalFlowFractions', settings.totalFlowFractions, ...
    'freshAirRecirculationR', settings.freshAirRecirculationR, ...
    'source', "电堆信息及推荐测试工况.xlsx Sheet1", ...
    'cegrScreenContract', contract, ...
    'execution', struct('runner', "run_routeA_focused_study", ...
        'mode', "parallel", 'poolProfile', settings.poolProfile, ...
        'workerCount', settings.workerCount, 'coldStartOnly', true, ...
        'modelTime_s_per_case', settings.researchDuration_s, ...
        'tailWindow_s', settings.tailLogicalWindow_s));
end

function condition = recommendedConditions()
% Values transcribed from the workbook's recommended test-condition rows.
ambientPressure_MPa_abs = .101325;
condition = struct( ...
    'currentDensity_A_cm2', {0.1, 0.2, 0.4, 1.0}, ...
    'stackCurrent_A', {38, 76, 152, 380}, ...
    'referenceOER', {5.0, 3.6, 2.4, 1.8}, ...
    'cathodePressureGauge_kPa', {40, 55, 70, 130}, ...
    'ambientPressure_MPa_abs', {ambientPressure_MPa_abs, ambientPressure_MPa_abs, ...
        ambientPressure_MPa_abs, ambientPressure_MPa_abs}, ...
    'cathodeGasTemperature_C', {60, 62, 65, 75}, ...
    'stackTemperature_C', {61.5, 64, 68, 80});
end

function contract = screenContract()
contract = struct( ...
    'schemaVersion', "RouteA_Focused_CEGRScreenContract_v03", ...
    'targetDefinition', ...
        "targetRecirculationR_and_actualRecirculationR_are_m_return_over_m_fresh_at_compressor_inlet;_controller_target_is_x_EGR=R_EGR_over_1_plus_R_EGR;_r_split_is_branch_only", ...
    'oer', struct('unacceptableBelow', 1, 'riskUpperInclusive', 1.2), ...
    'tracking', struct('absoluteTolerance', .005, ...
        'relativeTolerance', .05), ...
    'condensation', struct('nearSaturationRatio', .95, ...
        'nearDewMargin_C', 2, 'nonzeroRate_kg_s', 1e-10), ...
    'topology', struct( ...
        'id', "VSH_StackOutletIdealSplit_TwoValve_v01", ...
        'flowPath', ...
            "stack_cathode_outlet_to_ideal_split_then_V_EGR_to_compressor_inlet_and_V_BP_to_ambient_exhaust", ...
        'replacedTopology', ...
            "valve-after-split_with_post-backpressure_gas_boundary", ...
        'postBackpressureGasBoundaryPresent', false), ...
    'pressureReadback', struct( ...
        'idealNodeTolerance_kPa', .1, ...
        'requiredEqualities', ...
            "p_stack_out_approximately_p_split_approximately_p_EGR_up;_p_EGR_down_approximately_p_comp_in", ...
        'requiredDrops', ...
            "delta_p_EGR=p_EGR_up-p_EGR_down;_delta_p_BP=p_split-p_ambient"), ...
    'liquidWaterBoundary', ...
        "gas_phase_only;_no_liquid_inventory_transport_drain_or_compressor_wet-gas_tolerance_model");
end

function settings = defaultSettings(overrides)
settings = struct( ...
    'totalFlowFractions', [0 .10 .25 .50 .75 1.00], ...
    'freshAirRecirculationR', [0 .10 .50 1 2 4 8], ...
    'researchDuration_s', 600, ...
    'tailLogicalWindow_s', [540 600], ...
    'steadyWindowDuration_s', 60, ...
    'startupRampDuration_s', 60, ...
    'poolProfile', "local", ...
    'workerCount', 4, ...
    'resultDir', "", ...
    'resultTag', "20260820");
if ~isstruct(overrides) || ~isscalar(overrides)
    error('RouteA:External240kWCEGRMatrixOverrides', ...
        'overrides must be a scalar struct.');
end
names = fieldnames(overrides);
for idx = 1:numel(names)
    if ~isfield(settings, names{idx})
        error('RouteA:External240kWCEGRMatrixOverride', ...
            'Unsupported cEGR-matrix override: %s.', names{idx});
    end
    settings.(names{idx}) = overrides.(names{idx});
end
validateattributes(settings.totalFlowFractions, {'numeric'}, ...
    {'vector', 'real', 'finite', '>=', 0, '<=', 1});
validateattributes(settings.freshAirRecirculationR, {'numeric'}, ...
    {'vector', 'real', 'finite', '>=', 0, '<=', 8});
if settings.totalFlowFractions(1) ~= 0 || ...
        settings.freshAirRecirculationR(1) ~= 0
    error('RouteA:External240kWCEGRMatrixZero', ...
        'Both batches must include the R_EGR=0 reference case.');
end
validateattributes(settings.researchDuration_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
validateattributes(settings.tailLogicalWindow_s, {'numeric'}, ...
    {'vector', 'numel', 2, 'real', 'finite', 'nonnegative'});
if settings.tailLogicalWindow_s(1) >= settings.tailLogicalWindow_s(2) || ...
        settings.tailLogicalWindow_s(2) > settings.researchDuration_s
    error('RouteA:External240kWCEGRMatrixTailWindow', ...
        'tailLogicalWindow_s must be increasing and inside researchDuration_s.');
end
validateattributes(settings.steadyWindowDuration_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive', '<=', ...
    diff(settings.tailLogicalWindow_s)});
validateattributes(settings.startupRampDuration_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'nonnegative', '<', settings.researchDuration_s});
validateattributes(settings.workerCount, {'numeric'}, ...
    {'scalar', 'integer', 'positive'});
settings.totalFlowFractions = double(settings.totalFlowFractions(:).');
settings.freshAirRecirculationR = ...
    double(settings.freshAirRecirculationR(:).');
settings.poolProfile = string(settings.poolProfile);
end

function row = buildRow(caseCfg, condition, R, x, strategy, flowPolicy)
row = rowTemplate();
row.caseId = caseCfg.caseId;
row.flowStrategy = strategy;
row.flowPolicy = flowPolicy;
row.currentDensity_A_cm2 = condition.currentDensity_A_cm2;
row.referenceOER = condition.referenceOER;
row.cathodePressureGauge_kPa = condition.cathodePressureGauge_kPa;
row.cathodePressureAbsolute_MPa = caseCfg.cathode.outletPressure_MPa_abs;
row.cathodeGasTemperature_C = condition.cathodeGasTemperature_C;
row.stackTemperature_C = condition.stackTemperature_C;
row.targetRecirculationR = R;
row.controllerTargetMixFraction = x;
end

function row = rowTemplate()
row = struct( ...
    'caseId', "", 'flowStrategy', "", 'flowPolicy', "", ...
    'currentDensity_A_cm2', NaN, 'referenceOER', NaN, ...
    'cathodePressureGauge_kPa', NaN, ...
    'cathodePressureAbsolute_MPa', NaN, ...
    'cathodeGasTemperature_C', NaN, 'stackTemperature_C', NaN, ...
    'targetRecirculationR', NaN, 'controllerTargetMixFraction', NaN);
end

function text = numericLabel(value, decimals)
format = "%." + string(decimals) + "f";
text = replace(string(sprintf(char(format), value)), '.', 'p');
end
