function [focused, bridge] = routeA_focused_parameter_bridge(caseCfg, defaults)
% Map standard anode and thermal inputs to focused boundary variables.
%
% The focused model does not silently pretend that removed BOP parameters are
% active. Parameters that have a physical replacement are mapped to the
% replacement boundary; parameters with no equivalent remain explicit
% not_applicable entries in the returned bridge contract.

if ~isstruct(caseCfg) || ~isscalar(caseCfg)
    error('RouteA:FocusedBridgeCase', ...
        'caseCfg must be a scalar struct.');
end

focused = struct( ...
    'stackTemperature_C', defaults.stack.temperature_C, ...
    'cathodeGasTemperature_C', defaults.stack.cathodeGasTemperature_C, ...
    'stackIo_A_cm2', defaults.stack.io_A_cm2, ...
    'stackAlpha', defaults.stack.alpha, ...
    'cathodeSourcePressure_MPa_abs', defaults.cathode.sourcePressure_MPa_abs, ...
    'cathodeSourceTemperature_C', defaults.cathode.sourceTemperature_C, ...
    'cathodeChannelDpNominal_MPa', defaults.cathode.channelDpNominal_MPa, ...
    'cathodeChannelMdotNominal_kg_s', ...
        defaults.cathode.channelMdotNominal_kg_s, ...
    'cathodeChannelFlowArea_m2', defaults.cathode.channelFlowArea_m2, ...
    'cathodeChannelLaminarFraction', ...
        defaults.cathode.channelLaminarFraction, ...
    'exhaustBackpressureValveMaxArea_m2', ...
        defaults.cathode.exhaustBackpressureValveMaxArea_m2, ...
    'exhaustBackpressureValveOpenMinArea_m2', ...
        defaults.cathode.exhaustBackpressureValveOpenMinArea_m2, ...
    'exhaustBackpressureValveKi_area_per_MPa_s', ...
        defaults.cathode.exhaustBackpressureValveKi_area_per_MPa_s, ...
    'anodeFeedPressure_MPa_abs', defaults.anode.feedPressure_MPa_abs, ...
    'anodeInletMdot_kg_s', defaults.anode.inletMdot_kg_s, ...
    'anodeOutletPressure_MPa_abs', defaults.anode.outletPressure_MPa_abs, ...
    'anodeBoundaryTemperature_C', defaults.anode.boundaryTemperature_C, ...
    'anodeHydrogenMoleFraction', defaults.anode.hydrogenMoleFraction, ...
    'anodePipeLength_m', defaults.anode.pipeLength_m, ...
    'anodePipeDiameter_m', defaults.anode.pipeDiameter_m, ...
    'anodePipeArea_m2', defaults.anode.pipeArea_m2, ...
    'anodePipeExtraLength_m', defaults.anode.pipeExtraLength_m, ...
    'anodePipeRoughness_m', defaults.anode.pipeRoughness_m, ...
    'ejectorEnabled', defaults.ejector.enabled, ...
    'ejectorAreaThroat_m2', defaults.ejector.areaThroat_m2, ...
    'ejectorAreaRatioNozzle', defaults.ejector.areaRatioNozzle, ...
    'ejectorAreaRatioMixing', defaults.ejector.areaRatioMixing, ...
    'ejectorMinAreaRatioSecondary', defaults.ejector.minAreaRatioSecondary, ...
    'ejectorEfficiencyPrimary', defaults.ejector.efficiencyPrimary, ...
    'ejectorEfficiencySecondary', defaults.ejector.efficiencySecondary, ...
    'ejectorEfficiencyExpansion', defaults.ejector.efficiencyExpansion, ...
    'ejectorEfficiencyMixing', defaults.ejector.efficiencyMixing, ...
    'ejectorAreaA_m2', defaults.ejector.areaA_m2, ...
    'ejectorAreaB_m2', defaults.ejector.areaB_m2, ...
    'ejectorAreaS_m2', defaults.ejector.areaS_m2, ...
    'ejectorPressureRecovery', defaults.ejector.pressureRecovery, ...
    'ejectorPressureSmoothing_Pa', defaults.ejector.pressureSmoothing_Pa, ...
    'ejectorMdotSmoothing_kg_s', defaults.ejector.mdotSmoothing_kg_s);

mapping = repmat(mappingTemplate(), 0, 1);

[focused.stackTemperature_C, source] = selectValue(caseCfg, ...
    'stackTemperature_C', {{'thermal', 'stackTemperatureSet_C'}}, ...
    focused.stackTemperature_C, "platform_default");
mapping(end + 1) = mappedEntry('thermal.stackTemperatureSet_C', ...
    source, 'focused_stack_temperature_C', focused.stackTemperature_C, ...
    'degC', 'mapped');

[focused.cathodeGasTemperature_C, source] = selectFocusedOnly(caseCfg, ...
    'cathodeGasTemperature_C', focused.cathodeGasTemperature_C, ...
    "external_case_default");
mapping(end + 1) = mappedEntry('focused.cathodeGasTemperature_C', source, ...
    'focused_cathode_inlet_temperature_C', ...
    focused.cathodeGasTemperature_C, 'degC', 'mapped');

[focused.stackIo_A_cm2, source] = selectFocusedOnly(caseCfg, ...
    'stackIo_A_cm2', focused.stackIo_A_cm2, "external_case_default");
mapping(end + 1) = mappedEntry('focused.stackIo_A_cm2', source, ...
    'stack_io', focused.stackIo_A_cm2, 'A/cm^2', 'mapped');

[focused.stackAlpha, source] = selectFocusedOnly(caseCfg, ...
    'stackAlpha', focused.stackAlpha, "external_case_default");
mapping(end + 1) = mappedEntry('focused.stackAlpha', source, ...
    'stack_alpha', focused.stackAlpha, '1', 'mapped');

[focused.cathodeSourcePressure_MPa_abs, source] = selectValue(caseCfg, ...
    'cathodeSourcePressure_MPa_abs', ...
    {{'environment', 'ambientPressure_MPa_abs'}, ...
     {'cathode', 'sourcePressure_MPa_abs'}}, ...
    focused.cathodeSourcePressure_MPa_abs, "platform_default");
mapping(end + 1) = mappedEntry('cathode.sourcePressure_MPa_abs', ...
    source, 'env_p', focused.cathodeSourcePressure_MPa_abs, ...
    'MPa(abs)', 'mapped');
mapping(end + 1) = mappedEntry('cathode.sourcePressure_MPa_abs', ...
    source, 'cegr_inlet_mixer_p0', focused.cathodeSourcePressure_MPa_abs, ...
    'MPa(abs)', 'derived');
mapping(end).reason = "initial_mixer_pressure_consistency";

[focused.cathodeChannelDpNominal_MPa, source] = selectFocusedOnly(caseCfg, ...
    'cathodeChannelDpNominal_MPa', focused.cathodeChannelDpNominal_MPa, ...
    "platform_default");
mapping(end + 1) = mappedEntry( ...
    'focused.cathodeChannelDpNominal_MPa', source, ...
    'cathode_channel_dp_nominal_MPa', focused.cathodeChannelDpNominal_MPa, ...
    'MPa', 'mapped');

[focused.cathodeChannelMdotNominal_kg_s, source] = selectFocusedOnly( ...
    caseCfg, 'cathodeChannelMdotNominal_kg_s', ...
    focused.cathodeChannelMdotNominal_kg_s, "platform_default");
mapping(end + 1) = mappedEntry( ...
    'focused.cathodeChannelMdotNominal_kg_s', source, ...
    'cathode_channel_mdot_nominal_kg_s', ...
    focused.cathodeChannelMdotNominal_kg_s, 'kg/s', 'mapped');

[focused.cathodeChannelFlowArea_m2, source] = selectFocusedOnly(caseCfg, ...
    'cathodeChannelFlowArea_m2', focused.cathodeChannelFlowArea_m2, ...
    "platform_default");
mapping(end + 1) = mappedEntry( ...
    'focused.cathodeChannelFlowArea_m2', source, ...
    'cathode_channel_flow_area_m2', focused.cathodeChannelFlowArea_m2, ...
    'm^2', 'mapped');

[focused.cathodeChannelLaminarFraction, source] = selectFocusedOnly( ...
    caseCfg, 'cathodeChannelLaminarFraction', ...
    focused.cathodeChannelLaminarFraction, "platform_default");
mapping(end + 1) = mappedEntry( ...
    'focused.cathodeChannelLaminarFraction', source, ...
    'cathode_channel_laminar_fraction', ...
    focused.cathodeChannelLaminarFraction, '1', 'mapped');

[focused.exhaustBackpressureValveMaxArea_m2, source] = selectFocusedOnly( ...
    caseCfg, 'exhaustBackpressureValveMaxArea_m2', ...
    focused.exhaustBackpressureValveMaxArea_m2, "external_case_default");
mapping(end + 1) = mappedEntry( ...
    'focused.exhaustBackpressureValveMaxArea_m2', source, ...
    'exhaust_bp_valve_max_area', focused.exhaustBackpressureValveMaxArea_m2, ...
    'm^2', 'mapped');

[focused.exhaustBackpressureValveOpenMinArea_m2, source] = ...
    selectFocusedOnly(caseCfg, 'exhaustBackpressureValveOpenMinArea_m2', ...
    focused.exhaustBackpressureValveOpenMinArea_m2, "external_case_default");
mapping(end + 1) = mappedEntry( ...
    'focused.exhaustBackpressureValveOpenMinArea_m2', source, ...
    'exhaust_bp_valve_open_min_area', ...
    focused.exhaustBackpressureValveOpenMinArea_m2, 'm^2', 'mapped');

[focused.exhaustBackpressureValveKi_area_per_MPa_s, source] = ...
    selectFocusedOnly(caseCfg, 'exhaustBackpressureValveKi_area_per_MPa_s', ...
    focused.exhaustBackpressureValveKi_area_per_MPa_s, "external_case_default");
mapping(end + 1) = mappedEntry( ...
    'focused.exhaustBackpressureValveKi_area_per_MPa_s', source, ...
    'exhaust_bp_valve_control_Ki_area_per_MPa_s', ...
    focused.exhaustBackpressureValveKi_area_per_MPa_s, 'm^2/(MPa*s)', 'mapped');

if isfield(caseCfg, 'cathode') && isstruct(caseCfg.cathode) && ...
        isfield(caseCfg.cathode, 'freshAirWaterMoleFraction')
    mapping(end + 1) = mappedEntry( ...
        'environment.ambientRelativeHumidity', ...
        'derived_from_environment_T_p_RH', 'env_yH20', ...
        caseCfg.cathode.freshAirWaterMoleFraction, 'mole fraction', ...
        'derived');
end

[focused.cathodeSourceTemperature_C, source] = selectValue(caseCfg, ...
    'cathodeSourceTemperature_C', ...
    {{'cathode', 'sourceTemperature_C'}}, ...
    focused.cathodeSourceTemperature_C, "platform_default");
mapping(end + 1) = mappedEntry('cathode.sourceTemperature_C', ...
    source, 'env_T', focused.cathodeSourceTemperature_C, ...
    'degC', 'mapped');

[focused.anodeFeedPressure_MPa_abs, source] = selectValue(caseCfg, ...
    'anodeFeedPressure_MPa_abs', ...
    {{'anode', 'tankPressure_MPa_abs'}, ...
     {'anode', 'sourcePressure_MPa_abs'}}, ...
    focused.anodeFeedPressure_MPa_abs, "platform_default");
mapping(end + 1) = mappedEntry('anode.sourcePressure_MPa_abs', ...
    source, 'focused_anode_feed_p_MPa_abs', ...
    focused.anodeFeedPressure_MPa_abs, 'MPa(abs)', 'mapped');

[focused.anodeBoundaryTemperature_C, source] = selectValue(caseCfg, ...
    'anodeBoundaryTemperature_C', ...
    {{'anode', 'sourceTemperature_C'}}, ...
    focused.anodeBoundaryTemperature_C, "platform_default");
mapping(end + 1) = mappedEntry('anode.sourceTemperature_C', source, ...
    'focused_anode_boundary_T_C', focused.anodeBoundaryTemperature_C, ...
    'degC', 'mapped');

[focused.anodeHydrogenMoleFraction, source] = selectValue(caseCfg, ...
    'anodeHydrogenMoleFraction', ...
    {{'anode', 'hydrogenMoleFraction'}, ...
     {'anode', 'h2MoleFraction'}}, ...
    focused.anodeHydrogenMoleFraction, "platform_default");
mapping(end + 1) = mappedEntry('anode.h2MoleFraction', source, ...
    'focused_anode_yH2', focused.anodeHydrogenMoleFraction, '-', 'mapped');

[focused.anodeInletMdot_kg_s, source] = selectFocusedOnly(caseCfg, ...
    'anodeInletMdot_kg_s', focused.anodeInletMdot_kg_s, "platform_default");
mapping(end + 1) = mappedEntry('focused.anodeInletMdot_kg_s', source, ...
    'focused_anode_inlet_mdot_kg_s', focused.anodeInletMdot_kg_s, ...
    'kg/s', 'mapped');

[focused.anodeOutletPressure_MPa_abs, source] = selectFocusedOnly(caseCfg, ...
    'anodeOutletPressure_MPa_abs', focused.anodeOutletPressure_MPa_abs, ...
    "platform_default");
mapping(end + 1) = mappedEntry('focused.anodeOutletPressure_MPa_abs', ...
    source, 'focused_anode_outlet_p_MPa_abs', ...
    focused.anodeOutletPressure_MPa_abs, 'MPa(abs)', 'mapped');

[focused.anodePipeLength_m, source] = selectFocusedOnly(caseCfg, ...
    'anodePipeLength_m', focused.anodePipeLength_m, "platform_default");
mapping(end + 1) = mappedEntry('focused.anodePipeLength_m', source, ...
    'focused_anode_pipe_length', focused.anodePipeLength_m, 'm', 'mapped');

[focused.anodePipeDiameter_m, source] = selectFocusedOnly(caseCfg, ...
    'anodePipeDiameter_m', focused.anodePipeDiameter_m, "platform_default");
areaWasExplicit = hasFocusedField(caseCfg, 'anodePipeArea_m2');
if areaWasExplicit
    explicitArea = caseCfg.focused.anodePipeArea_m2;
    expectedArea = pi * focused.anodePipeDiameter_m^2 / 4;
    if ~isfinite(explicitArea) || explicitArea <= 0
        error('RouteA:FocusedAnodePipeArea', ...
            'focused.anodePipeArea_m2 must be positive and finite.');
    end
    if hasFocusedField(caseCfg, 'anodePipeDiameter_m') && ...
            abs(explicitArea - expectedArea) > max(1e-12, 1e-6 * expectedArea)
        error('RouteA:FocusedAnodePipeGeometry', ...
            'Focused anode pipe diameter and area are inconsistent.');
    end
    focused.anodePipeArea_m2 = explicitArea;
    areaSource = "focused.anodePipeArea_m2 (checked)";
else
    focused.anodePipeArea_m2 = pi * focused.anodePipeDiameter_m^2 / 4;
    areaSource = "derived_from_focused.anodePipeDiameter_m";
end
mapping(end + 1) = mappedEntry('focused.anodePipeDiameter_m', source, ...
    'focused_anode_pipe_area', focused.anodePipeArea_m2, 'm^2', 'derived');
mapping(end).reason = areaSource;

[focused.anodePipeExtraLength_m, source] = selectFocusedOnly(caseCfg, ...
    'anodePipeExtraLength_m', focused.anodePipeExtraLength_m, ...
    "platform_default");
mapping(end + 1) = mappedEntry('focused.anodePipeExtraLength_m', source, ...
    'focused_anode_pipe_extra_length', focused.anodePipeExtraLength_m, ...
    'm', 'mapped');

[focused.anodePipeRoughness_m, source] = selectFocusedOnly(caseCfg, ...
    'anodePipeRoughness_m', focused.anodePipeRoughness_m, ...
    "platform_default");
mapping(end + 1) = mappedEntry('focused.anodePipeRoughness_m', source, ...
    'focused_anode_pipe_roughness', focused.anodePipeRoughness_m, ...
    'm', 'mapped');

isEjectorModel = lower(string(defaults.modelId)) == ...
    "ejector_self_humidifying";
ejectorFields = { ...
    'enabled', 'ejectorEnabled', 'ejector_enabled', 'boolean'; ...
    'areaThroat_m2', 'ejectorAreaThroat_m2', 'ejector_area_throat_m2', 'm^2'; ...
    'areaRatioNozzle', 'ejectorAreaRatioNozzle', 'ejector_area_ratio_nozzle', '-'; ...
    'areaRatioMixing', 'ejectorAreaRatioMixing', 'ejector_area_ratio_mixing', '-'; ...
    'minAreaRatioSecondary', 'ejectorMinAreaRatioSecondary', ...
        'ejector_min_area_ratio_secondary', '-'; ...
    'efficiencyPrimary', 'ejectorEfficiencyPrimary', ...
        'ejector_efficiency_primary', '-'; ...
    'efficiencySecondary', 'ejectorEfficiencySecondary', ...
        'ejector_efficiency_secondary', '-'; ...
    'efficiencyExpansion', 'ejectorEfficiencyExpansion', ...
        'ejector_efficiency_expansion', '-'; ...
    'efficiencyMixing', 'ejectorEfficiencyMixing', ...
        'ejector_efficiency_mixing', '-'; ...
    'areaA_m2', 'ejectorAreaA_m2', 'ejector_area_A_m2', 'm^2'; ...
    'areaB_m2', 'ejectorAreaB_m2', 'ejector_area_B_m2', 'm^2'; ...
    'areaS_m2', 'ejectorAreaS_m2', 'ejector_area_S_m2', 'm^2'; ...
    'pressureRecovery', 'ejectorPressureRecovery', ...
        'ejector_pressure_recovery', '-'; ...
    'pressureSmoothing_Pa', 'ejectorPressureSmoothing_Pa', ...
        'ejector_pressure_smoothing_Pa', 'Pa'; ...
    'mdotSmoothing_kg_s', 'ejectorMdotSmoothing_kg_s', ...
        'ejector_mdot_smoothing_kg_s', 'kg/s'};
if isEjectorModel
    for idx = 1:size(ejectorFields, 1)
        canonical = "ejector." + string(ejectorFields{idx, 1});
        [value, source] = selectEjectorValue(caseCfg, ejectorFields{idx, 1}, ...
            focused.(ejectorFields{idx, 2}), "platform_default");
        focused.(ejectorFields{idx, 2}) = value;
        mapping(end + 1) = mappedEntry(canonical, source, ...
            ejectorFields{idx, 3}, value, ejectorFields{idx, 4}, 'mapped');
    end
end

mapping = addNotApplicable(mapping, caseCfg, 'anode.inletPressure_MPa_abs', ...
    'mass_flow_source_boundary', ...
    'The focused anode inlet is set by mass flow, not inlet pressure.');
mapping = addNotApplicable(mapping, caseCfg, 'anode.humidifierRH', ...
    'removed_anode_BOP', ...
    'The focused boundary has no anode humidifier.');
mapping = addNotApplicable(mapping, caseCfg, ...
    'anode.recirculationBaseCommand', 'removed_anode_BOP', ...
    'The focused boundary has no anode recirculation loop.');
mapping = addNotApplicable(mapping, caseCfg, ...
    'anode.recirculationCurrentGain_A_inv', 'removed_anode_BOP', ...
    'The focused boundary has no anode recirculation loop.');
mapping = addNotApplicable(mapping, caseCfg, 'anode.purgeEnabled', ...
    'removed_anode_BOP', ...
    'The focused boundary has no anode purge valve.');
mapping = addNotApplicable(mapping, caseCfg, ...
    'anode.purgeOnN2MoleFraction', 'removed_anode_BOP', ...
    'The focused boundary has no anode purge valve.');
mapping = addNotApplicable(mapping, caseCfg, ...
    'anode.purgeOffN2MoleFraction', 'removed_anode_BOP', ...
    'The focused boundary has no anode purge valve.');
mapping = addNotApplicable(mapping, caseCfg, ...
    'devices.thermal.coolantGeometry', 'removed_thermal_BOP', ...
    'The focused temperature boundary does not contain coolant channels.');
mapping = addNotApplicable(mapping, caseCfg, ...
    'devices.thermal.radiatorCore', 'removed_thermal_BOP', ...
    'The focused temperature boundary does not contain a radiator.');

validateFocusedValues(focused);

modelWritePoints = [ ...
    "focused_stack_temperature_C", ...
    "focused_cathode_inlet_temperature_C", ...
    "stack_io", ...
    "stack_alpha", ...
    "env_p", ...
    "env_T", ...
    "cegr_inlet_mixer_p0", ...
    "cathode_channel_dp_nominal_MPa", ...
    "cathode_channel_mdot_nominal_kg_s", ...
    "cathode_channel_flow_area_m2", ...
    "cathode_channel_laminar_fraction", ...
    "exhaust_bp_valve_max_area", ...
    "exhaust_bp_valve_open_min_area", ...
    "exhaust_bp_valve_control_Ki_area_per_MPa_s", ...
    "focused_anode_feed_p_MPa_abs", ...
    "focused_anode_inlet_mdot_kg_s", ...
    "focused_anode_outlet_p_MPa_abs", ...
    "focused_anode_boundary_T_C", ...
    "focused_anode_yH2", ...
    "focused_anode_pipe_length", ...
    "focused_anode_pipe_area", ...
    "focused_anode_pipe_extra_length", ...
    "focused_anode_pipe_roughness"];
if isEjectorModel
    modelWritePoints = [modelWritePoints, string(ejectorFields(:, 3)).'];
end

bridge = struct( ...
    'schemaVersion', "RouteA_Focused_ParameterBridge_v01", ...
    'status', "mapped_with_explicit_fixed_boundaries", ...
    'modelWritePoints', modelWritePoints, ...
    'mapping', mapping, ...
    'removedSubsystemPolicy', ...
        "accepted_standard_fields_are_reported_not_applicable_when_no_physical_replacement_exists", ...
    'engineeringUse', ...
        "fixed_anode_and_temperature_boundary_with_ejector_contract;_not_a_full_BOP_result");
end

function [value, source] = selectValue(caseCfg, focusedName, standardPaths, default, defaultSource)
if hasFocusedField(caseCfg, focusedName)
    value = caseCfg.focused.(focusedName);
    source = "focused." + string(focusedName);
else
    value = default;
    source = defaultSource;
    for idx = 1:numel(standardPaths)
        standardPath = standardPaths{idx};
        if hasNestedField(caseCfg, standardPath)
            value = getNestedField(caseCfg, standardPath);
            source = string(standardPath{1}) + "." + string(standardPath{2});
            break;
        end
    end
end
end

function [value, source] = selectFocusedOnly(caseCfg, fieldName, default, defaultSource)
if hasFocusedField(caseCfg, fieldName)
    value = caseCfg.focused.(fieldName);
    source = "focused." + string(fieldName);
else
    value = default;
    source = defaultSource;
end
end

function [value, source] = selectEjectorValue(caseCfg, fieldName, default, defaultSource)
focusedName = ['ejector', upper(fieldName(1)), fieldName(2:end)];
if isfield(caseCfg, 'ejector') && isstruct(caseCfg.ejector) && ...
        isfield(caseCfg.ejector, fieldName) && ...
        ~isempty(caseCfg.ejector.(fieldName))
    value = caseCfg.ejector.(fieldName);
    source = "ejector." + string(fieldName);
elseif hasFocusedField(caseCfg, focusedName)
    value = caseCfg.focused.(focusedName);
    source = "focused." + string(focusedName);
else
    value = default;
    source = defaultSource;
end
end

function present = hasFocusedField(caseCfg, fieldName)
present = isfield(caseCfg, 'focused') && isstruct(caseCfg.focused) && ...
    isfield(caseCfg.focused, fieldName) && ~isempty(caseCfg.focused.(fieldName));
end

function present = hasNestedField(s, path)
present = isfield(s, path{1}) && isstruct(s.(path{1})) && ...
    isfield(s.(path{1}), path{2}) && ~isempty(s.(path{1}).(path{2}));
end

function value = getNestedField(s, path)
value = s.(path{1}).(path{2});
end

function mapping = addNotApplicable(mapping, caseCfg, canonicalName, reason, text)
entry = mappedEntry(canonicalName, "case field if supplied", "", NaN, ...
    "", "not_applicable");
entry.reason = string(text);
entry.sourcePresent = hasCanonicalField(caseCfg, canonicalName);
entry.targetVariable = string(reason);
mapping(end + 1) = entry;
end

function present = hasCanonicalField(caseCfg, canonicalName)
parts = split(string(canonicalName), '.');
if string(canonicalName) == "anode.humidifierRH"
    canonicalName = "anode.humidifierRelativeHumidity";
    parts = split(canonicalName, '.');
end
value = caseCfg;
for idx = 1:numel(parts)
    if ~isstruct(value) || ~isfield(value, char(parts(idx)))
        present = false;
        return;
    end
    value = value.(char(parts(idx)));
end
present = ~isempty(value);
end

function entry = mappedEntry(canonicalName, sourcePath, targetVariable, value, unit, status)
entry = mappingTemplate();
entry.canonicalName = string(canonicalName);
entry.sourcePath = string(sourcePath);
entry.targetVariable = string(targetVariable);
entry.value = value;
entry.unit = string(unit);
entry.status = string(status);
entry.reason = "";
entry.sourcePresent = false;
end

function entry = mappingTemplate()
entry = struct( ...
    'canonicalName', "", ...
    'sourcePath', "", ...
    'targetVariable', "", ...
    'value', NaN, ...
    'unit', "", ...
    'status', "", ...
    'reason', "", ...
    'sourcePresent', false);
end

function validateFocusedValues(focused)
validateRange(focused.stackTemperature_C, [60, 100], ...
    'focused.stackTemperature_C');
validateRange(focused.cathodeGasTemperature_C, [0, 150], ...
    'focused.cathodeGasTemperature_C');
validateRange(focused.stackIo_A_cm2, [1e-14, 1e-2], ...
    'focused.stackIo_A_cm2');
validateRange(focused.stackAlpha, [0.4, 1], 'focused.stackAlpha');
validateRange(focused.cathodeSourcePressure_MPa_abs, [0.05, 1], ...
    'focused.cathodeSourcePressure_MPa_abs');
validateRange(focused.cathodeSourceTemperature_C, [-50, 150], ...
    'focused.cathodeSourceTemperature_C');
validateRange(focused.cathodeChannelDpNominal_MPa, [1e-5, 0.2], ...
    'focused.cathodeChannelDpNominal_MPa');
validateRange(focused.cathodeChannelMdotNominal_kg_s, [1e-4, 1], ...
    'focused.cathodeChannelMdotNominal_kg_s');
validateRange(focused.cathodeChannelFlowArea_m2, [1e-6, 0.1], ...
    'focused.cathodeChannelFlowArea_m2');
validateRange(focused.cathodeChannelLaminarFraction, [0, 0.99], ...
    'focused.cathodeChannelLaminarFraction');
validateRange(focused.exhaustBackpressureValveMaxArea_m2, [1e-8, 0.1], ...
    'focused.exhaustBackpressureValveMaxArea_m2');
validateRange(focused.exhaustBackpressureValveOpenMinArea_m2, [0, 0.1], ...
    'focused.exhaustBackpressureValveOpenMinArea_m2');
validateRange(focused.exhaustBackpressureValveKi_area_per_MPa_s, [0, 1], ...
    'focused.exhaustBackpressureValveKi_area_per_MPa_s');
if focused.exhaustBackpressureValveOpenMinArea_m2 > ...
        focused.exhaustBackpressureValveMaxArea_m2
    error('RouteA:FocusedBackpressureValveArea', ...
        'The exhaust backpressure-valve minimum area exceeds its maximum area.');
end
validateRange(focused.anodeFeedPressure_MPa_abs, [0.2, 1], ...
    'focused.anodeFeedPressure_MPa_abs');
validateRange(focused.anodeInletMdot_kg_s, [eps, 1], ...
    'focused.anodeInletMdot_kg_s');
validateRange(focused.anodeOutletPressure_MPa_abs, [0.01, 1], ...
    'focused.anodeOutletPressure_MPa_abs');
validateRange(focused.anodeBoundaryTemperature_C, [-50, 150], ...
    'focused.anodeBoundaryTemperature_C');
validateRange(focused.anodeHydrogenMoleFraction, [0.9, 1], ...
    'focused.anodeHydrogenMoleFraction');
validateRange(focused.anodePipeLength_m, [1e-4, 100], ...
    'focused.anodePipeLength_m');
validateRange(focused.anodePipeDiameter_m, [1e-4, 1], ...
    'focused.anodePipeDiameter_m');
validateRange(focused.anodePipeArea_m2, [1e-8, 1], ...
    'focused.anodePipeArea_m2');
validateRange(focused.anodePipeExtraLength_m, [0, 100], ...
    'focused.anodePipeExtraLength_m');
validateRange(focused.anodePipeRoughness_m, [0, 0.01], ...
    'focused.anodePipeRoughness_m');
validateEjectorValues(focused);
end

function validateEjectorValues(focused)
validateattributes(focused.ejectorEnabled, {'numeric', 'logical'}, ...
    {'scalar', 'real', 'finite'}, 'RouteA:FocusedEjectorEnabled');
if ~ismember(double(focused.ejectorEnabled), [0, 1])
    error('RouteA:FocusedEjectorEnabled', ...
        'focused.ejectorEnabled must be false/true or 0/1.');
end
validateRange(focused.ejectorAreaThroat_m2, [1e-8, 1], ...
    'focused.ejectorAreaThroat_m2');
validateRange(focused.ejectorAreaRatioNozzle, [1, 1e4], ...
    'focused.ejectorAreaRatioNozzle');
validateRange(focused.ejectorAreaRatioMixing, [1, 1e4], ...
    'focused.ejectorAreaRatioMixing');
validateRange(focused.ejectorMinAreaRatioSecondary, [1e-6, 1e4], ...
    'focused.ejectorMinAreaRatioSecondary');
validateRange(focused.ejectorEfficiencyPrimary, [1e-6, 1], ...
    'focused.ejectorEfficiencyPrimary');
validateRange(focused.ejectorEfficiencySecondary, [1e-6, 1], ...
    'focused.ejectorEfficiencySecondary');
validateRange(focused.ejectorEfficiencyExpansion, [1e-6, 1], ...
    'focused.ejectorEfficiencyExpansion');
validateRange(focused.ejectorEfficiencyMixing, [1e-6, 1], ...
    'focused.ejectorEfficiencyMixing');
validateRange(focused.ejectorAreaA_m2, [1e-8, 1], ...
    'focused.ejectorAreaA_m2');
validateRange(focused.ejectorAreaB_m2, [1e-8, 1], ...
    'focused.ejectorAreaB_m2');
validateRange(focused.ejectorAreaS_m2, [1e-8, 1], ...
    'focused.ejectorAreaS_m2');
validateRange(focused.ejectorPressureRecovery, [1e-6, 1e4], ...
    'focused.ejectorPressureRecovery');
validateRange(focused.ejectorPressureSmoothing_Pa, [0, 1e6], ...
    'focused.ejectorPressureSmoothing_Pa');
validateRange(focused.ejectorMdotSmoothing_kg_s, [0, 1], ...
    'focused.ejectorMdotSmoothing_kg_s');
end

function validateRange(value, bounds, name)
validateattributes(value, {'numeric'}, {'scalar', 'real', 'finite'}, ...
    'RouteA:FocusedBoundaryValue', name);
if value < bounds(1) || value > bounds(2)
    error('RouteA:FocusedBoundaryRange', ...
        '%s must be within [%.6g, %.6g].', name, bounds(1), bounds(2));
end
end
