function assessment = routeA_focused_cegr_screen_assessment(study, contract)
% Audit passive-cEGR screening cases without making hardware claims.
%
% The study target is R_EGR=m_return/m_fresh at the compressor inlet. The
% valve controller uses x_EGR=m_return/m_total=R_EGR/(1+R_EGR); r_split is
% a separate exhaust-branch metric and is never used as the target proxy.

if nargin < 1 || ~isstruct(study) || ~isfield(study, 'cases')
    error('RouteA:FocusedCEGRScreenStudy', ...
        'study must be a focused-study result with a cases field.');
end
if nargin < 2 || isempty(contract)
    contract = defaultContract();
else
    contract = normalizeContract(contract);
end

rows = repmat(rowTemplate(), numel(study.cases), 1);
for idx = 1:numel(study.cases)
    item = study.cases(idx);
    row = rowTemplate();
    row.caseId = string(getField(item, 'caseId', ""));
    row.simCompleted = logical(getField(item, 'simCompleted', false));
    row.localNumericsPassed = logical(getField(item, 'passed', false));
    row.errorId = string(getField(item, 'errorId', ""));
    row.targetMixFraction = getNested(item, {'caseCfg', 'cegr', ...
        'targetRatio'}, NaN);
    row.targetRecirculationR = getNested(item, {'caseCfg', 'cegr', ...
        'targetRecirculationR'}, NaN);
    if ~isfinite(row.targetRecirculationR) && isfinite(row.targetMixFraction) && ...
            row.targetMixFraction < 1
        row.targetRecirculationR = row.targetMixFraction / ...
            (1 - row.targetMixFraction);
    end
    row.targetOER = getNested(item, {'caseCfg', 'air', 'targetOer'}, NaN);
    row.airControlMode = getNested(item, {'caseCfg', 'air', 'modeId'}, NaN);
    row.mixFractionTrackingTolerance = getField(item, 'targetTolerance', ...
        contract.tracking.absoluteTolerance);
    row.recirculationTrackingTolerance = max( ...
        contract.tracking.absoluteTolerance, ...
        contract.tracking.relativeTolerance * row.targetRecirculationR);
    row.actualOERMinimum = getField(item, 'lambdaTailMin', NaN);
    if isfield(item, 'performance') && isstruct(item.performance)
        row = collectPerformance(row, item.performance, item);
    end
    if ~isfinite(row.actualOERMinimum)
        row.actualOERMinimum = row.actualOERMean;
    end
    row.actualOERStatus = classifyOER(row.actualOERMinimum, contract.oer);
    row.controlTrackingStatus = classifyTracking(row, item);
    row.topologyPressureStatus = classifyTopologyPressure( ...
        row, contract.pressureReadback);
    row.mixerCondensationStatus = classifyMixerCondensation(row, ...
        contract.condensation);
    row.cathodeGasCondensationStatus = classifyNodeCondensation( ...
        row.cathodeGasSaturationRatio, row.cathodeGasCondensationRate_kg_s, ...
        contract.condensation);
    row.cegrBranchCondensationStatus = ...
        "not_applicable_ideal_connection";
    row.caseScreenStatus = classifyCase(row);
    rows(idx) = row;
end

assessment = struct( ...
    'schemaVersion', "RouteA_Focused_CEGRScreenAssessment_v05", ...
    'scope', "low_load_passive_cegr_gas_phase_screening_only", ...
    'targetDefinition', contract.targetDefinition, ...
    'topology', contract.topology, ...
    'pressureReadbackContract', contract.pressureReadback, ...
    'contract', contract, ...
    'rows', rows, ...
    'auditTable', struct2table(rows), ...
    'allCasesCompleted', all([rows.simCompleted]), ...
    'allCasesLocalNumericsPassed', all([rows.localNumericsPassed]), ...
    'engineeringSelectionAllowed', false, ...
    'performanceCalibrationClaimAllowed', false, ...
    'conclusionBoundary', ...
        "gas_phase_screening_only;_no_liquid_inventory_droplet_transport_compressor_wet-gas_tolerance_or_valve_hardware_validation");
end

function row = collectPerformance(row, performance, item)
if isfield(performance, 'electrical')
    row.currentDensity_A_cm2 = getField(performance.electrical, ...
        'currentDensity_A_cm2', NaN);
    row.cellVoltage_V = getField(performance.electrical, 'cellVoltage_V', NaN);
end
if isfield(performance, 'cegr')
    cegr = performance.cegr;
    row.actualRSplit = getField(cegr, 'actualRatioSplitBasis', NaN);
    row.actualMixFraction = getField(cegr, 'actualRatioMixBasis', NaN);
    row.mCegr_kg_s = getField(cegr, 'massFlow_kg_s', NaN);
    row.actualRecirculationR = getField(cegr, 'actualRatioFreshBasis', NaN);
    row.cegrValveAreaFraction = getField(cegr, 'valveAreaFraction', NaN);
    row.cegrValveDeltaP_MPa = getField(cegr, 'valveDeltaP_MPa', NaN);
end
row.mixFractionError = row.actualMixFraction - row.targetMixFraction;
row.recirculationError = row.actualRecirculationR - row.targetRecirculationR;
row.splitBasisDelta = row.actualRSplit - row.targetMixFraction;
if isfield(performance, 'cathode')
    cathode = performance.cathode;
    row.actualOERMean = getField(cathode, 'oxygenStoich_lambda', NaN);
    row.cathodeInletRH = getField(cathode, 'cathodeInletRH', NaN);
    row.compressorInletPO2_Pa = getField(cathode, ...
        'compressorInletO2PartialPressure_Pa', NaN);
end
if isfield(performance, 'pressure') && isstruct(performance.pressure) && ...
        isfield(performance.pressure, 'chain')
    chain = performance.pressure.chain;
    row.compressorInletPressure_MPa = getField(chain, ...
        'compressorInletMixerPressure_MPa', NaN);
    row.compressorDischargePressure_MPa = getField(chain, ...
        'compressorDischargePressure_MPa', NaN);
    row.compressorAfterIntercoolerPressure_MPa = getField(chain, ...
        'compressorAfterIntercoolerPressure_MPa', NaN);
    row.stackCathodePressure_MPa = getField(chain, ...
        'stackCathodeChannelPressure_MPa', NaN);
    row.cathodeOutletPressure_MPa = getField(chain, ...
        'cathodeOutletPressure_MPa', NaN);
    row.splitPressure_MPa = getField(chain, 'splitPressure_MPa', NaN);
    row.egrValveUpstreamPressure_MPa = getField(chain, ...
        'egrValveUpstreamPressure_MPa', NaN);
    row.egrValveDownstreamPressure_MPa = getField(chain, ...
        'egrValveDownstreamPressure_MPa', NaN);
    row.egrValvePressureDrop_MPa = getField(chain, ...
        'egrValvePressureDrop_MPa', NaN);
    row.exhaustBackpressureValveDrop_MPa = getField(chain, ...
        'exhaustBackpressureValveDrop_MPa', NaN);
    row.stackToSplitDeltaP_MPa = row.cathodeOutletPressure_MPa - ...
        row.splitPressure_MPa;
    row.splitToEgrUpstreamDeltaP_MPa = row.splitPressure_MPa - ...
        row.egrValveUpstreamPressure_MPa;
    row.egrDownstreamToCompressorInletDeltaP_MPa = ...
        row.egrValveDownstreamPressure_MPa - ...
        row.compressorInletPressure_MPa;
end
if isfield(performance, 'antiCondensation') && ...
        isstruct(performance.antiCondensation) && ...
        isfield(performance.antiCondensation, 'mixer')
    mixer = performance.antiCondensation.mixer;
    row.mixerTemperature_C = getField(mixer, 'temperature_C', NaN);
    row.mixerDewPointMargin_C = getField(mixer, 'dewPointMargin_C', NaN);
    row.mixerCondensationRate_kg_s = getField(mixer, ...
        'condensationRate_kg_s', NaN);
    row.mixerCondensationIntegral_kg = getField(mixer, ...
        'condensationIntegral_kg', NaN);
    row.mixerSaturationRatio = getField(mixer, 'saturationRatio', NaN);
end
if isfield(item, 'waterObservations') && isstruct(item.waterObservations)
    row = collectWaterNodes(row, item.waterObservations);
end
end

function row = collectWaterNodes(row, observations)
if ~isfield(observations, 'nodes') || ~isstruct(observations.nodes)
    return;
end
nodes = observations.nodes;
row = copyNode(row, nodes, "compressor_inlet_mixer", "mixer");
row = copyNode(row, nodes, "cathode_gas", "cathodeGas");
end

function row = copyNode(row, nodes, nodeName, prefix)
index = find(string({nodes.name}) == nodeName, 1);
if isempty(index)
    return;
end
node = nodes(index);
meanRate = getNested(node, {'condensation', 'mean_kg_s'}, NaN);
integral = getNested(node, {'condensation', 'integral_kg'}, NaN);
saturation = getNested(node, {'saturation', 'mean'}, NaN);
switch prefix
    case "mixer"
        row.mixerCondensationRate_kg_s = meanRate;
        row.mixerCondensationIntegral_kg = integral;
        row.mixerSaturationRatio = saturation;
    case "cathodeGas"
        row.cathodeGasCondensationRate_kg_s = meanRate;
        row.cathodeGasCondensationIntegral_kg = integral;
        row.cathodeGasSaturationRatio = saturation;
end
end

function status = classifyOER(value, threshold)
if ~isfinite(value)
    status = "not_evaluable";
elseif value < threshold.unacceptableBelow
    status = "not_acceptable_below_1";
elseif value <= threshold.riskUpperInclusive
    status = "risk_1_to_1p2";
else
    status = "feasible_above_1p2";
end
end

function status = classifyTracking(row, item)
if ~row.simCompleted
    status = "not_available_simulation_failed";
elseif ~isfinite(row.targetRecirculationR) || ...
        ~isfinite(row.actualRecirculationR)
    status = "not_evaluable";
elseif row.targetRecirculationR == 0
    status = "not_applicable_zero_target";
elseif abs(row.recirculationError) <= row.recirculationTrackingTolerance
    status = "within_control_tolerance";
elseif isfinite(row.cegrValveDeltaP_MPa) && row.cegrValveDeltaP_MPa <= 0
    status = "deviation_no_forward_pressure";
elseif isfinite(row.cegrValveAreaFraction) && ...
        row.cegrValveAreaFraction >= 1 - 1e-6
    status = "deviation_valve_area_saturated";
elseif ~logical(getField(item, 'steadyEngineeringPassed', false))
    status = "deviation_not_steady";
else
    status = "deviation_check_pi_or_flow_definition";
end
end

function status = classifyTopologyPressure(row, contract)
values = [ ...
    row.stackToSplitDeltaP_MPa, ...
    row.splitToEgrUpstreamDeltaP_MPa, ...
    row.egrDownstreamToCompressorInletDeltaP_MPa];
if ~row.simCompleted
    status = "not_available_simulation_failed";
elseif any(~isfinite(values))
    status = "not_evaluable";
elseif max(abs(values)) * 1e3 <= contract.idealNodeTolerance_kPa
    status = "within_ideal_split_tolerance";
else
    status = "ideal_split_pressure_mismatch";
end
end

function status = classifyMixerCondensation(row, threshold)
if ~isfinite(row.mixerSaturationRatio) || ...
        ~isfinite(row.mixerDewPointMargin_C) || ...
        ~isfinite(row.mixerCondensationRate_kg_s)
    status = "not_evaluable";
elseif row.mixerCondensationRate_kg_s > threshold.nonzeroRate_kg_s || ...
        row.mixerSaturationRatio > 1 || row.mixerDewPointMargin_C < 0
    status = "condensing_or_supersaturated";
elseif row.mixerSaturationRatio >= threshold.nearSaturationRatio || ...
        row.mixerDewPointMargin_C <= threshold.nearDewMargin_C
    status = "near_saturation_risk";
else
    status = "gas_phase_noncondensing";
end
end

function status = classifyNodeCondensation(saturation, rate, threshold)
if ~isfinite(saturation) || ~isfinite(rate)
    status = "not_evaluable";
elseif rate > threshold.nonzeroRate_kg_s || saturation > 1
    status = "condensing_or_supersaturated";
elseif saturation >= threshold.nearSaturationRatio
    status = "near_saturation_risk";
else
    status = "gas_phase_noncondensing";
end
end

function status = classifyCase(row)
if ~row.simCompleted
    status = "not_executed";
elseif row.actualOERStatus == "not_acceptable_below_1"
    status = "not_acceptable_oer";
elseif row.mixerCondensationStatus == "condensing_or_supersaturated"
    status = "not_acceptable_mixer_condensation";
elseif row.controlTrackingStatus ~= "within_control_tolerance" && ...
        row.controlTrackingStatus ~= "not_applicable_zero_target"
    status = "requires_cegr_tracking_review";
elseif row.topologyPressureStatus ~= "within_ideal_split_tolerance"
    status = "topology_pressure_readback_review";
elseif row.actualOERStatus == "risk_1_to_1p2" || ...
        row.mixerCondensationStatus == "near_saturation_risk" || ...
        row.cathodeGasCondensationStatus == "near_saturation_risk" || ...
        row.cegrBranchCondensationStatus == "near_saturation_risk"
    status = "risk_review_required";
elseif row.localNumericsPassed
    status = "candidate_feasible_gas_phase_screen";
else
    status = "numerical_or_steady_review_required";
end
end

function contract = defaultContract()
contract = struct( ...
    'schemaVersion', "RouteA_Focused_CEGRScreenContract_v03", ...
    'targetDefinition', ...
        "targetRecirculationR_and_actualRecirculationR_are_m_return_over_m_fresh_at_compressor_inlet;_controller_mix_fraction_is_R_over_1_plus_R;_r_split_is_a_separate_branch_metric", ...
    'oer', struct('unacceptableBelow', 1, 'riskUpperInclusive', 1.2), ...
    'tracking', struct('absoluteTolerance', .005, ...
        'relativeTolerance', .05), ...
    'condensation', struct( ...
        'nearSaturationRatio', .95, ...
        'nearDewMargin_C', 2, ...
        'nonzeroRate_kg_s', 1e-10), ...
    'topology', struct( ...
        'id', "VSH_StackOutletIdealSplit_TwoValve_v01", ...
        'flowPath', ...
            "stack_cathode_outlet_to_ideal_split_then_V_EGR_to_compressor_inlet_and_V_BP_to_ambient_exhaust", ...
        'replacedTopology', ...
            "valve-after-split_with_post-backpressure_gas_boundary", ...
        'postBackpressureGasBoundaryPresent', false), ...
    'pressureReadback', struct( ...
        'idealNodeTolerance_kPa', .1, ...
        'requiredEqualities', ...
            "p_stack_out_approximately_p_split_approximately_p_EGR_up;_p_EGR_down_approximately_p_comp_in", ...
        'requiredDrops', ...
            "delta_p_EGR=p_EGR_up-p_EGR_down;_delta_p_BP=p_split-p_ambient"), ...
    'liquidWaterBoundary', ...
        "gas_phase_only;_no_liquid_inventory_transport_drain_or_compressor_wet-gas_tolerance_model");
end

function contract = normalizeContract(user)
if ~isstruct(user) || ~isscalar(user)
    error('RouteA:FocusedCEGRScreenContract', ...
        'contract must be a scalar struct.');
end
contract = defaultContract();
names = fieldnames(user);
for idx = 1:numel(names)
    if ~isfield(contract, names{idx})
        error('RouteA:FocusedCEGRScreenContractField', ...
            'Unsupported cEGR-screen contract field: %s.', names{idx});
    end
    contract.(names{idx}) = user.(names{idx});
end
if ~isfield(contract.tracking, 'relativeTolerance')
    contract.tracking.relativeTolerance = .05;
end
validateattributes(contract.oer.unacceptableBelow, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive'});
validateattributes(contract.oer.riskUpperInclusive, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>', contract.oer.unacceptableBelow});
validateattributes(contract.tracking.absoluteTolerance, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive', '<=', .5});
validateattributes(contract.tracking.relativeTolerance, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive', '<=', 1});
validateattributes(contract.condensation.nearSaturationRatio, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>', 0, '<=', 1});
validateattributes(contract.condensation.nearDewMargin_C, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>=', 0});
validateattributes(contract.condensation.nonzeroRate_kg_s, {'numeric'}, ...
    {'scalar', 'real', 'finite', '>', 0});
validateattributes(contract.pressureReadback.idealNodeTolerance_kPa, {'numeric'}, ...
    {'scalar', 'real', 'finite', 'positive', '<=', 10});
end

function row = rowTemplate()
row = struct( ...
    'caseId', "", ...
    'simCompleted', false, ...
    'localNumericsPassed', false, ...
    'errorId', "", ...
    'currentDensity_A_cm2', NaN, ...
    'cellVoltage_V', NaN, ...
    'airControlMode', NaN, ...
    'targetOER', NaN, ...
    'actualOERMean', NaN, ...
    'actualOERMinimum', NaN, ...
    'actualOERStatus', "not_evaluable", ...
    'targetRecirculationR', NaN, ...
    'actualRecirculationR', NaN, ...
    'recirculationError', NaN, ...
    'recirculationTrackingTolerance', NaN, ...
    'targetMixFraction', NaN, ...
    'actualMixFraction', NaN, ...
    'mixFractionError', NaN, ...
    'mixFractionTrackingTolerance', NaN, ...
    'controlTrackingStatus', "not_evaluable", ...
    'topologyPressureStatus', "not_evaluable", ...
    'actualRSplit', NaN, ...
    'splitBasisDelta', NaN, ...
    'mCegr_kg_s', NaN, ...
    'cegrValveAreaFraction', NaN, ...
    'cegrValveDeltaP_MPa', NaN, ...
    'cathodeInletRH', NaN, ...
    'compressorInletPO2_Pa', NaN, ...
    'compressorInletPressure_MPa', NaN, ...
    'compressorDischargePressure_MPa', NaN, ...
    'compressorAfterIntercoolerPressure_MPa', NaN, ...
    'stackCathodePressure_MPa', NaN, ...
    'cathodeOutletPressure_MPa', NaN, ...
    'splitPressure_MPa', NaN, ...
    'egrValveUpstreamPressure_MPa', NaN, ...
    'egrValveDownstreamPressure_MPa', NaN, ...
    'stackToSplitDeltaP_MPa', NaN, ...
    'splitToEgrUpstreamDeltaP_MPa', NaN, ...
    'egrDownstreamToCompressorInletDeltaP_MPa', NaN, ...
    'egrValvePressureDrop_MPa', NaN, ...
    'exhaustBackpressureValveDrop_MPa', NaN, ...
    'mixerTemperature_C', NaN, ...
    'mixerDewPointMargin_C', NaN, ...
    'mixerSaturationRatio', NaN, ...
    'mixerCondensationRate_kg_s', NaN, ...
    'mixerCondensationIntegral_kg', NaN, ...
    'mixerCondensationStatus', "not_evaluable", ...
    'cathodeGasSaturationRatio', NaN, ...
    'cathodeGasCondensationRate_kg_s', NaN, ...
    'cathodeGasCondensationIntegral_kg', NaN, ...
    'cathodeGasCondensationStatus', "not_evaluable", ...
    'cegrBranchCondensationStatus', "not_applicable_ideal_connection", ...
    'caseScreenStatus', "not_executed");
end

function value = getNested(s, path, default)
value = s;
for idx = 1:numel(path)
    if ~isstruct(value) || ~isfield(value, path{idx}) || ...
            isempty(value.(path{idx}))
        value = default;
        return;
    end
    value = value.(path{idx});
end
end

function value = getField(s, fieldName, default)
if isstruct(s) && isfield(s, fieldName) && ~isempty(s.(fieldName))
    value = s.(fieldName);
else
    value = default;
end
end
