function study = run_routeA_focused_vsh_v4_boundary_temperature()
% Run boundary-focused temperature perturbations for two W3 risk cases.

scriptDir = fileparts(mfilename('fullpath'));
sharedDir = fullfile(scriptDir, '..', 'RouteA_GasMixture_Derived');
addpath(scriptDir, sharedDir);

[totalStudy, ~, freshStudy, ~] = ...
    routeA_focused_external240kw_cegr_matrix_case_factory();
oerCase = findCase(totalStudy.cases, "external240_total_flow_fixed_j0p2_R2p600");
condCase = findCase(freshStudy.cases, "external240_fresh_air_fixed_j0p4_R0p500");
cases = repmat(oerCase, 0, 1);
for temperature = [60 70 80 90]
    item = oerCase;
    item.caseId = "V4_oer_boundary_j0p2_R2p6_T" + string(temperature);
    item.description = "V4 boundary temperature perturbation; OER boundary";
    item.focused.cathodeGasTemperature_C = temperature;
    cases(end + 1) = item; %#ok<AGROW>
end
for temperature = [60 70 80 90]
    item = condCase;
    item.caseId = "V4_cond_boundary_j0p4_R0p5_T" + string(temperature);
    item.description = "V4 boundary temperature perturbation; condensation boundary";
    item.focused.cathodeGasTemperature_C = temperature;
    cases(end + 1) = item; %#ok<AGROW>
end

resultFile = fullfile(scriptDir, '..', '..', '02_结果', ...
    'RouteA_Cathode_cEGR_Focused', 'outputs', '20260820_vsh_validation', ...
    'RouteA_VSH_V4_boundary_temperature_120s_20260820.mat');
cfg = struct( ...
    'modelId', "self_humidifying", ...
    'calculationType', "steady", ...
    'cases', cases, ...
    'researchDuration_s', 120, ...
    'tailLogicalWindow_s', [90 120], ...
    'steadyWindowDuration_s', 30, ...
    'retainSimulationOutputs', false, ...
    'executionMode', "parallel", ...
    'parallel', struct('poolProfile', "local", 'workerCount', 4, ...
        'showProgress', true, 'useFastRestart', false), ...
    'resultFile', string(resultFile), ...
    'cegrScreenContract', totalStudy.cegrScreenContract);

study = run_routeA_focused_study(cfg);
routeA_focused_study = study; %#ok<NASGU>
save(resultFile, 'routeA_focused_study', '-v7.3');
assignin('base', 'routeA_focused_v4_study', study);
fprintf('V4_DONE cases=%d completed=%d passed=%d result=%s\n', ...
    numel(study.cases), sum([study.cases.simCompleted]), ...
    sum([study.cases.passed]), resultFile);
rows = study.cegrScreenAudit.rows;
for idx = 1:numel(rows)
    fprintf('V4_CASE %s T=%.1f OERmin=%.6g S=%.6g dew=%.6g cond=%.6g area=%.6g tracking=%s screen=%s\n', ...
        rows(idx).caseId, ...
        rows(idx).mixerTemperature_C, rows(idx).actualOERMinimum, ...
        rows(idx).mixerSaturationRatio, rows(idx).mixerDewPointMargin_C, ...
        rows(idx).mixerCondensationRate_kg_s, ...
        rows(idx).cegrValveAreaFraction, ...
        rows(idx).controlTrackingStatus, rows(idx).caseScreenStatus);
end
end

function item = findCase(cases, caseId)
index = find(string({cases.caseId}) == string(caseId), 1);
if isempty(index)
    error('RouteA:FocusedV4Case', 'V4 source case not found: %s', caseId);
end
item = cases(index);
end
