function result = run_routeA_focused_v6_contract_tests()
% Non-simulation contract regression for V6 pressure eligibility semantics.

scriptDir = fileparts(mfilename('fullpath'));
addpath(scriptDir, fullfile(scriptDir, '..', 'RouteA_GasMixture_Derived'));
resultFile = fullfile(scriptDir, '..', '..', '02_结果', ...
    'RouteA_Cathode_cEGR_Focused', 'outputs', '20260820_vsh_validation', ...
    'RouteA_VSH_V2_external240_baseline_600s_20260820.mat');
loaded = load(resultFile, 'routeA_focused_study');
[~, reference] = routeA_focused_external240kw_case_factory();

eligible = routeA_focused_external240kw_calibration_assessment( ...
    loaded.routeA_focused_study, reference);
assert(eligible.pressure.comparisonEligible, ...
    'The confirmed pressure contract must be comparison eligible.');
assert(strlength(eligible.pressure.blockedReason) == 0, ...
    'An eligible pressure contract must not retain a blocked reason.');
assert(eligible.pressure.passed, ...
    'The existing V2 pressure subgate must remain passed.');
assert(~eligible.passed, ...
    'The V2 top-level assessment must remain incomplete for its known gates.');

blockedReference = reference;
blockedReference.pressureMeasurementContract.modelComparisonEligible = false;
blocked = routeA_focused_external240kw_calibration_assessment( ...
    loaded.routeA_focused_study, blockedReference);
assert(~blocked.pressure.comparisonEligible, ...
    'The ineligible pressure contract must remain blocked.');
assert(blocked.pressure.blockedReason == ...
    "external_pressure_tap_mapping_not_confirmed", ...
    'The ineligible pressure contract must expose the mapping block reason.');
assert(~blocked.pressure.passed, ...
    'An ineligible pressure contract cannot pass the pressure subgate.');

emptyStudy = loaded.routeA_focused_study;
emptyStudy.cases = emptyStudy.cases([]);
empty = routeA_focused_external240kw_calibration_assessment( ...
    emptyStudy, reference);
assert(empty.pressure.comparisonEligible, ...
    'Eligibility is a contract property even when no anchors are available.');
assert(strlength(empty.pressure.blockedReason) == 0, ...
    'Missing anchors must not be mislabeled as a mapping block.');
assert(~empty.pressure.passed, ...
    'No pressure anchors must keep the pressure gate unevaluable.');

result = struct( ...
    'status', "passed", ...
    'eligible', eligible.pressure, ...
    'blocked', blocked.pressure, ...
    'emptyAnchors', empty.pressure, ...
    'sourceResultFile', string(resultFile));
fprintf(['V6_CONTRACT_TESTS status=%s eligibleBlockedReason="%s" ', ...
    'blockedReason="%s" emptyPassed=%d\n'], result.status, ...
    eligible.pressure.blockedReason, blocked.pressure.blockedReason, ...
    empty.pressure.passed);
end
