function study = run_routeA_focused_vsh_v1_parameter_audit()
% Run the V1 baseline/perturbation consumer audit through the formal runner.

scriptDir = fileparts(mfilename('fullpath'));
sharedDir = fullfile(scriptDir, '..', 'RouteA_GasMixture_Derived');
addpath(scriptDir, sharedDir);

[totalStudy, ~, ~, ~] = ...
    routeA_focused_external240kw_cegr_matrix_case_factory();
totalR0 = totalStudy.cases(1);
totalR04 = totalStudy.cases(2);
low = totalR0;

cases = repmat(low, 0, 1);
pairs = repmat(pairTemplate(), 0, 1);

[cases, pairs] = addPair(cases, pairs, ...
    mutate(low, 'V1_current_base', @(c) setCurrent(c, 38)), ...
    mutate(low, 'V1_current_perturb', @(c) setCurrent(c, 76)), ...
    "current_boundary");
[cases, pairs] = addPair(cases, pairs, totalR0, totalR04, ...
    "cegr_R_EGR_x_EGR");
[cases, pairs] = addPair(cases, pairs, ...
    mutate(low, 'V1_envT_base', @(c) setAmbientT(c, 20)), ...
    mutate(low, 'V1_envT_perturb', @(c) setAmbientT(c, 30)), ...
    "env_T");
[cases, pairs] = addPair(cases, pairs, ...
    mutate(low, 'V1_focusedT_base', @(c) setFocusedGasT(c, 60)), ...
    mutate(low, 'V1_focusedT_perturb', @(c) setFocusedGasT(c, 90)), ...
    "focused_cathode_inlet_temperature_C");
[cases, pairs] = addPair(cases, pairs, ...
    mutate(low, 'V1_RH_base', @(c) setAmbientRH(c, 0.5)), ...
    mutate(low, 'V1_RH_perturb', @(c) setAmbientRH(c, 0.8)), ...
    "ambient_RH_and_H2O");
[cases, pairs] = addPair(cases, pairs, ...
    mutate(totalR04, 'V1_valveMax_base', @(c) c), ...
    mutate(totalR04, 'V1_valveMax_perturb', @(c) setFocusedField(c, ...
        'exhaustBackpressureValveMaxArea_m2', ...
        0.8 * c.focused.exhaustBackpressureValveMaxArea_m2)), ...
    "exhaust_backpressure_valve_max_area");
[cases, pairs] = addPair(cases, pairs, ...
    mutate(totalR04, 'V1_valveMin_base', @(c) c), ...
    mutate(totalR04, 'V1_valveMin_perturb', @(c) setFocusedField(c, ...
        'exhaustBackpressureValveOpenMinArea_m2', ...
        2 * c.focused.exhaustBackpressureValveOpenMinArea_m2)), ...
    "exhaust_backpressure_valve_min_area");
[cases, pairs] = addPair(cases, pairs, ...
    mutate(totalR04, 'V1_valveKi_base', @(c) c), ...
    mutate(totalR04, 'V1_valveKi_perturb', @(c) setFocusedField(c, ...
        'exhaustBackpressureValveKi_area_per_MPa_s', ...
        1.25 * c.focused.exhaustBackpressureValveKi_area_per_MPa_s)), ...
    "exhaust_backpressure_valve_Ki");
[cases, pairs] = addPair(cases, pairs, ...
    mutate(low, 'V1_flowResistance_base', @(c) c), ...
    mutate(low, 'V1_flowResistance_perturb', @(c) setFocusedField(c, ...
        'cathodeChannelDpNominal_MPa', ...
        1.25 * c.focused.cathodeChannelDpNominal_MPa)), ...
    "cathode_equivalent_flow_resistance");
[cases, pairs] = addPair(cases, pairs, ...
    mutate(low, 'V1_stackT_base', @(c) c), ...
    mutate(low, 'V1_stackT_perturb', @(c) setStackT(c, ...
        c.thermal.stackTemperatureSet_C + 5)), ...
    "focused_stack_temperature_C");
[cases, pairs] = addPair(cases, pairs, ...
    mutate(low, 'V1_O2_base', @(c) setO2(c, 0.21)), ...
    mutate(low, 'V1_O2_perturb', @(c) setO2(c, 0.20)), ...
    "env_yO2");

resultFile = fullfile(scriptDir, '..', '..', '02_结果', ...
    'RouteA_Cathode_cEGR_Focused', 'outputs', '20260820_vsh_validation', ...
    'RouteA_VSH_V1_parameter_consumers_120s_20260820.mat');
cfg = struct( ...
    'modelId', "self_humidifying", ...
    'calculationType', "steady", ...
    'cases', cases, ...
    'researchDuration_s', 120, ...
    'tailLogicalWindow_s', [90 120], ...
    'steadyWindowDuration_s', 30, ...
    'retainSimulationOutputs', false, ...
    'executionMode', "parallel", ...
    'parallel', struct('poolProfile', "local", 'workerCount', 4, ...
        'showProgress', true, 'useFastRestart', false), ...
    'resultFile', string(resultFile));

study = run_routeA_focused_study(cfg);
consumerAudit = assessPairs(study, pairs);
study.parameterConsumerAudit = consumerAudit;
routeA_focused_study = study; %#ok<NASGU>
save(resultFile, 'routeA_focused_study', '-v7.3');
assignin('base', 'routeA_focused_v1_study', study);
fprintf('V1_DONE cases=%d completed=%d passed=%d pairCount=%d pairPassed=%d result=%s\n', ...
    numel(study.cases), sum([study.cases.simCompleted]), ...
    sum([study.cases.passed]), numel(consumerAudit), ...
    sum([consumerAudit.responsePassed]), resultFile);
for idx = 1:numel(consumerAudit)
    fprintf('V1_PAIR %s passed=%d deltas=%s\n', ...
        consumerAudit(idx).parameter, ...
        consumerAudit(idx).responsePassed, ...
        mat2str(consumerAudit(idx).delta, 6));
end
end

function [cases, pairs] = addPair(cases, pairs, base, perturb, parameter)
base.caseId = string(base.caseId);
perturb.caseId = string(perturb.caseId);
cases = [cases; base; perturb]; %#ok<AGROW>
item = pairTemplate();
item.parameter = string(parameter);
item.baseCaseId = string(base.caseId);
item.perturbCaseId = string(perturb.caseId);
pairs(end + 1) = item; %#ok<AGROW>
end

function caseCfg = mutate(caseCfg, caseId, mutator)
caseCfg.caseId = string(caseId);
caseCfg.description = "V1 parameter consumer audit: " + string(caseId);
caseCfg.cegr.enabled = false;
caseCfg.cegr.targetRatio = 0;
caseCfg.cegr.targetRecirculationR = 0;
caseCfg.cegr.profile = 0;
caseCfg = mutator(caseCfg);
end

function caseCfg = setCurrent(caseCfg, value)
caseCfg.boundary.profile = value;
end

function caseCfg = setAmbientT(caseCfg, value)
caseCfg.environment.ambientTemperature_C = value;
end

function caseCfg = setFocusedGasT(caseCfg, value)
caseCfg.focused.cathodeGasTemperature_C = value;
end

function caseCfg = setAmbientRH(caseCfg, value)
caseCfg.environment.ambientRelativeHumidity = value;
end

function caseCfg = setFocusedField(caseCfg, fieldName, value)
caseCfg.focused.(fieldName) = value;
end

function caseCfg = setStackT(caseCfg, value)
caseCfg.thermal.stackTemperatureSet_C = value;
caseCfg.focused.stackTemperature_C = value;
end

function caseCfg = setO2(caseCfg, value)
caseCfg.cathode.freshAirO2MoleFraction = value;
end

function audit = assessPairs(study, pairs)
audit = repmat(auditTemplate(), numel(pairs), 1);
for idx = 1:numel(pairs)
    base = findCase(study.cases, pairs(idx).baseCaseId);
    perturb = findCase(study.cases, pairs(idx).perturbCaseId);
    baseValues = observables(base);
    perturbValues = observables(perturb);
    delta = perturbValues - baseValues;
    audit(idx).parameter = pairs(idx).parameter;
    audit(idx).baseCaseId = pairs(idx).baseCaseId;
    audit(idx).perturbCaseId = pairs(idx).perturbCaseId;
    audit(idx).baseSimCompleted = logical(base.simCompleted);
    audit(idx).perturbSimCompleted = logical(perturb.simCompleted);
    audit(idx).delta = delta;
    thresholds = [1e-6 1e-6 1e-3 1e-5 1e-5 1 1e-4 1e-4 ...
        1e-6 1e-3 1e-4];
    finite = isfinite(delta);
    audit(idx).responsePassed = base.simCompleted && perturb.simCompleted && ...
        any(abs(delta(finite)) > thresholds(finite));
end
end

function values = observables(item)
values = NaN(1, 11);
if ~isfield(item, 'performance') || ~isstruct(item.performance)
    return;
end
p = item.performance;
values(1) = getNested(p, {'electrical', 'current_A'}, NaN);
values(2) = getNested(p, {'electrical', 'voltage_V'}, NaN);
values(3) = getNested(p, {'electrical', 'power_kW'}, NaN);
values(4) = getNested(p, {'cegr', 'actualRatioFreshBasis'}, NaN);
values(5) = getNested(p, {'cegr', 'valveAreaFraction'}, NaN);
values(6) = getNested(p, {'cathode', ...
    'compressorInletO2PartialPressure_Pa'}, NaN);
values(7) = getNested(p, {'cathode', 'cathodeInletRH'}, NaN);
values(8) = getNested(p, {'pressure', 'chain', ...
    'compressorDischargeTemperature_K'}, NaN);
values(9) = getNested(p, {'pressure', 'chain', ...
    'compressorAfterIntercoolerTemperature_K'}, NaN);
values(10) = getNested(p, {'pressure', 'chain', ...
    'stackCathodeChannelPressure_MPa'}, NaN);
values(11) = getNested(p, {'thermal', 'stackTemperature_C'}, NaN);
end

function item = findCase(cases, caseId)
index = find(string({cases.caseId}) == string(caseId), 1);
if isempty(index)
    error('RouteA:FocusedV1Case', 'V1 case not found: %s', caseId);
end
item = cases(index);
end

function value = getNested(source, path, default)
value = source;
for idx = 1:numel(path)
    if ~isstruct(value) || ~isfield(value, path{idx}) || ...
            isempty(value.(path{idx}))
        value = default;
        return;
    end
    value = value.(path{idx});
end
end

function value = pairTemplate()
value = struct('parameter', "", 'baseCaseId', "", 'perturbCaseId', "");
end

function value = auditTemplate()
value = struct('parameter', "", 'baseCaseId', "", 'perturbCaseId', "", ...
    'baseSimCompleted', false, 'perturbSimCompleted', false, ...
    'delta', NaN(1, 11), 'responsePassed', false);
end
