% Code to plot simulation results from PEMFuelCellSystemWithACustomLibrary
%% Plot Description:
%
% This plot shows the electrical power produced by the fuel cell stack as
% well as the power consumed by the cathode air compressor and the coolant
% pump to maintain stable and efficient system operation. As a result, the
% net power produced by the system is a few percent less than the power
% produced by the stack. Note that this model assumes an isentropic
% compressor. Accounting for compressor efficiency would decrease net power
% gain by another couple of percent.
%
% This plot also shows the excess heat generated by the fuel cell stack,
% which must be removed by the cooling system. The maximum power produced
% by the fuel cell stack is 95 kW.

% Copyright 2020-2021 The MathWorks, Inc.

% Generate simulation results if they don't exist
if ~exist('simlog_PEMFuelCellSystemWithACustomLibrary', 'var')
    sim('PEMFuelCellSystemWithACustomLibrary')
end

% Reuse figure if it exists, else create new figure
if ~exist('h2_PEMFuelCellSystemWithACustomLibrary', 'var') || ...
        ~isgraphics(h2_PEMFuelCellSystemWithACustomLibrary, 'figure')
    h2_PEMFuelCellSystemWithACustomLibrary = figure('Name', 'PEMFuelCellSystemWithACustomLibrary');
end
figure(h2_PEMFuelCellSystemWithACustomLibrary)
clf(h2_PEMFuelCellSystemWithACustomLibrary)

plotPower(simlog_PEMFuelCellSystemWithACustomLibrary)



% Plot power produced and consumed
function plotPower(simlog)

% Get simulation results
t = simlog.Membrane_Electrode_Assembly.power_elec.series.time;
power_elec = simlog.Membrane_Electrode_Assembly.power_elec.series.values('kW');
power_dissipated = simlog.Membrane_Electrode_Assembly.power_dissipated.series.values('kW');
power_compressor = simlog.Oxygen_Source.Compressor.power.series.values('kW');
power_pump = simlog.Cooling_System.Pump.power.series.values('kW');

% Compute net power gain
power_net = power_elec - power_compressor - power_pump;

% Plot results
handles(1) = subplot(2, 1, 1);
plot(t, power_net, 'LineWidth', 1)
hold on
plot(t, power_elec, 'LineWidth', 1)
plot(t, power_compressor, 'LineWidth', 1)
plot(t, power_pump, 'LineWidth', 1)
grid on
legend('Net Gain', 'Electrical', 'Air Compressor', 'Coolant Pump', 'Location', 'best')
title('Power Produced and Consumed (kW)')
handles(2) = subplot(2, 1, 2);
plot(t, power_dissipated, 'LineWidth', 1)
grid on
title('Heat Dissipated (kW)')
xlabel('Time (s)')

linkaxes(handles, 'x')

end