function create_routeA_panel()
% Create Route A cEGR-PEMFC simulation panel using App Designer API
%
% This script generates RouteA_Panel_v01.mlapp programmatically.
% Phase D Step D1: UI layout prototype (basic mode only, no callbacks yet)

% Create the app class file content
appClassCode = [...
'classdef RouteA_Panel_v01 < matlab.apps.AppBase' newline ...
'' newline ...
'    % Properties that correspond to app components' newline ...
'    properties (Access = public)' newline ...
'        UIFigure                    matlab.ui.Figure' newline ...
'        LeftPanel                   matlab.ui.container.Panel' newline ...
'        RightPanel                  matlab.ui.container.Panel' newline ...
'        StatusLabel                 matlab.ui.control.Label' newline ...
'        ' newline ...
'        % Mode toggle' newline ...
'        ModeButtonGroup             matlab.ui.container.ButtonGroup' newline ...
'        BasicModeButton             matlab.ui.control.ToggleButton' newline ...
'        AdvancedModeButton          matlab.ui.control.ToggleButton' newline ...
'        ' newline ...
'        % Electrical boundary' newline ...
'        ElectricalPanel             matlab.ui.container.Panel' newline ...
'        BoundaryModeLabel           matlab.ui.control.Label' newline ...
'        BoundaryModeDropDown        matlab.ui.control.DropDown' newline ...
'        BoundaryCommandLabel        matlab.ui.control.Label' newline ...
'        BoundaryCommandEditField    matlab.ui.control.NumericEditField' newline ...
'        BoundaryUnitLabel           matlab.ui.control.Label' newline ...
'        RampDurationLabel           matlab.ui.control.Label' newline ...
'        RampDurationEditField       matlab.ui.control.NumericEditField' newline ...
'        RampUnitLabel               matlab.ui.control.Label' newline ...
'        ' newline ...
'        % Air path' newline ...
'        AirPathPanel                matlab.ui.container.Panel' newline ...
'        OerLabel                    matlab.ui.control.Label' newline ...
'        OerEditField                matlab.ui.control.NumericEditField' newline ...
'        BackpressureLabel           matlab.ui.control.Label' newline ...
'        BackpressureEditField       matlab.ui.control.NumericEditField' newline ...
'        HumidifierRHLabel           matlab.ui.control.Label' newline ...
'        HumidifierRHEditField       matlab.ui.control.NumericEditField' newline ...
'        ' newline ...
'        % cEGR' newline ...
'        CegrPanel                   matlab.ui.container.Panel' newline ...
'        CegrRatioLabel              matlab.ui.control.Label' newline ...
'        CegrRatioEditField          matlab.ui.control.NumericEditField' newline ...
'        CegrEnabledCheckBox         matlab.ui.control.CheckBox' newline ...
'        ' newline ...
'        % Solver' newline ...
'        SolverPanel                 matlab.ui.container.Panel' newline ...
'        StopTimeLabel               matlab.ui.control.Label' newline ...
'        StopTimeEditField           matlab.ui.control.NumericEditField' newline ...
'        ' newline ...
'        % Case ID' newline ...
'        CaseIdLabel                 matlab.ui.control.Label' newline ...
'        CaseIdEditField             matlab.ui.control.EditField' newline ...
'        ' newline ...
'        % Buttons' newline ...
'        RunButton                   matlab.ui.control.Button' newline ...
'        MatrixButton                matlab.ui.control.Button' newline ...
'        ' newline ...
'        % Results' newline ...
'        KpiTable                    matlab.ui.control.Table' newline ...
'        TimeSeriesAxes              matlab.ui.control.UIAxes' newline ...
'        LogLabel                    matlab.ui.control.Label' newline ...
'        LogTextArea                 matlab.ui.control.TextArea' newline ...
'    end' newline ...
'    ' newline ...
'    % App state properties' newline ...
'    properties (Access = private)' newline ...
'        simCase  % Current simCase struct' newline ...
'    end' newline ...
'    ' newline ...
'    % Component initialization' newline ...
'    methods (Access = private)' newline ...
'        ' newline ...
'        function createComponents(app)' newline ...
'            % Create UIFigure and components' newline ...
'            ' newline ...
'            app.UIFigure = uifigure(''Visible'', ''off'');' newline ...
'            app.UIFigure.Position = [100 100 1200 700];' newline ...
'            app.UIFigure.Name = ''Route A cEGR-PEMFC 仿真平台'';' newline ...
'            app.UIFigure.Color = [0.94 0.94 0.94];' newline ...
'            ' newline ...
'            % Status bar' newline ...
'            app.StatusLabel = uilabel(app.UIFigure);' newline ...
'            app.StatusLabel.Position = [10 10 1180 25];' newline ...
'            app.StatusLabel.Text = ''状态: 就绪 | 模型: PEMFuelCellSystem_GasMixture_cEGR_RouteA_v01 | 参数源: platform_default'';' newline ...
'            app.StatusLabel.FontSize = 11;' newline ...
'            app.StatusLabel.BackgroundColor = [0.9 0.9 0.9];' newline ...
'            ' newline ...
'            % Left panel' newline ...
'            app.LeftPanel = uipanel(app.UIFigure);' newline ...
'            app.LeftPanel.Title = ''参数设置'';' newline ...
'            app.LeftPanel.Position = [10 50 480 620];' newline ...
'            app.LeftPanel.BackgroundColor = [0.94 0.94 0.94];' newline ...
'            ' newline ...
'            % Right panel' newline ...
'            app.RightPanel = uipanel(app.UIFigure);' newline ...
'            app.RightPanel.Title = ''结果展示'';' newline ...
'            app.RightPanel.Position = [500 50 690 620];' newline ...
'            app.RightPanel.BackgroundColor = [0.94 0.94 0.94];' newline ...
'            ' newline ...
'            % Mode toggle' newline ...
'            app.ModeButtonGroup = uibuttongroup(app.LeftPanel);' newline ...
'            app.ModeButtonGroup.Position = [320 580 140 30];' newline ...
'            app.ModeButtonGroup.BorderType = ''none'';' newline ...
'            app.ModeButtonGroup.BackgroundColor = [0.94 0.94 0.94];' newline ...
'            ' newline ...
'            app.BasicModeButton = uitogglebutton(app.ModeButtonGroup);' newline ...
'            app.BasicModeButton.Text = ''基础'';' newline ...
'            app.BasicModeButton.Position = [0 0 70 30];' newline ...
'            app.BasicModeButton.Value = true;' newline ...
'            ' newline ...
'            app.AdvancedModeButton = uitogglebutton(app.ModeButtonGroup);' newline ...
'            app.AdvancedModeButton.Text = ''高级'';' newline ...
'            app.AdvancedModeButton.Position = [70 0 70 30];' newline ...
'            ' newline ...
'            % Electrical boundary panel' newline ...
'            app.ElectricalPanel = uipanel(app.LeftPanel);' newline ...
'            app.ElectricalPanel.Title = ''电边界'';' newline ...
'            app.ElectricalPanel.Position = [10 440 450 100];' newline ...
'            app.ElectricalPanel.BackgroundColor = [1 1 1];' newline ...
'            ' newline ...
'            app.BoundaryModeLabel = uilabel(app.ElectricalPanel);' newline ...
'            app.BoundaryModeLabel.Position = [10 55 80 22];' newline ...
'            app.BoundaryModeLabel.Text = ''模式:'';' newline ...
'            ' newline ...
'            app.BoundaryModeDropDown = uidropdown(app.ElectricalPanel);' newline ...
'            app.BoundaryModeDropDown.Items = {''Current'', ''Power'', ''Voltage''};' newline ...
'            app.BoundaryModeDropDown.Value = ''Current'';' newline ...
'            app.BoundaryModeDropDown.Position = [90 55 120 22];' newline ...
'            ' newline ...
'            app.BoundaryCommandLabel = uilabel(app.ElectricalPanel);' newline ...
'            app.BoundaryCommandLabel.Position = [220 55 80 22];' newline ...
'            app.BoundaryCommandLabel.Text = ''命令值:'';' newline ...
'            ' newline ...
'            app.BoundaryCommandEditField = uieditfield(app.ElectricalPanel, ''numeric'');' newline ...
'            app.BoundaryCommandEditField.Position = [300 55 80 22];' newline ...
'            app.BoundaryCommandEditField.Value = 100;' newline ...
'            ' newline ...
'            app.BoundaryUnitLabel = uilabel(app.ElectricalPanel);' newline ...
'            app.BoundaryUnitLabel.Position = [385 55 40 22];' newline ...
'            app.BoundaryUnitLabel.Text = ''A'';' newline ...
'            ' newline ...
'            app.RampDurationLabel = uilabel(app.ElectricalPanel);' newline ...
'            app.RampDurationLabel.Position = [10 20 80 22];' newline ...
'            app.RampDurationLabel.Text = ''斜坡时间:'';' newline ...
'            ' newline ...
'            app.RampDurationEditField = uieditfield(app.ElectricalPanel, ''numeric'');' newline ...
'            app.RampDurationEditField.Position = [90 20 80 22];' newline ...
'            app.RampDurationEditField.Value = 60;' newline ...
'            ' newline ...
'            app.RampUnitLabel = uilabel(app.ElectricalPanel);' newline ...
'            app.RampUnitLabel.Position = [175 20 20 22];' newline ...
'            app.RampUnitLabel.Text = ''s'';' newline ...
'            ' newline ...
'            % Air path panel' newline ...
'            app.AirPathPanel = uipanel(app.LeftPanel);' newline ...
'            app.AirPathPanel.Title = ''气路'';' newline ...
'            app.AirPathPanel.Position = [10 320 450 110];' newline ...
'            app.AirPathPanel.BackgroundColor = [1 1 1];' newline ...
'            ' newline ...
'            app.OerLabel = uilabel(app.AirPathPanel);' newline ...
'            app.OerLabel.Position = [10 65 100 22];' newline ...
'            app.OerLabel.Text = ''OER:'';' newline ...
'            ' newline ...
'            app.OerEditField = uieditfield(app.AirPathPanel, ''numeric'');' newline ...
'            app.OerEditField.Position = [110 65 100 22];' newline ...
'            app.OerEditField.Value = 3.0;' newline ...
'            ' newline ...
'            app.BackpressureLabel = uilabel(app.AirPathPanel);' newline ...
'            app.BackpressureLabel.Position = [10 35 100 22];' newline ...
'            app.BackpressureLabel.Text = ''背压 (MPa):'';' newline ...
'            ' newline ...
'            app.BackpressureEditField = uieditfield(app.AirPathPanel, ''numeric'');' newline ...
'            app.BackpressureEditField.Position = [110 35 100 22];' newline ...
'            app.BackpressureEditField.Value = 0.1613;' newline ...
'            ' newline ...
'            app.HumidifierRHLabel = uilabel(app.AirPathPanel);' newline ...
'            app.HumidifierRHLabel.Position = [10 5 100 22];' newline ...
'            app.HumidifierRHLabel.Text = ''加湿器 RH:'';' newline ...
'            ' newline ...
'            app.HumidifierRHEditField = uieditfield(app.AirPathPanel, ''numeric'');' newline ...
'            app.HumidifierRHEditField.Position = [110 5 100 22];' newline ...
'            app.HumidifierRHEditField.Value = 0.9;' newline ...
'            ' newline ...
'            % cEGR panel' newline ...
'            app.CegrPanel = uipanel(app.LeftPanel);' newline ...
'            app.CegrPanel.Title = ''cEGR'';' newline ...
'            app.CegrPanel.Position = [10 230 450 80];' newline ...
'            app.CegrPanel.BackgroundColor = [1 1 1];' newline ...
'            ' newline ...
'            app.CegrRatioLabel = uilabel(app.CegrPanel);' newline ...
'            app.CegrRatioLabel.Position = [10 35 100 22];' newline ...
'            app.CegrRatioLabel.Text = ''目标比例:'';' newline ...
'            ' newline ...
'            app.CegrRatioEditField = uieditfield(app.CegrPanel, ''numeric'');' newline ...
'            app.CegrRatioEditField.Position = [110 35 100 22];' newline ...
'            app.CegrRatioEditField.Value = 0;' newline ...
'            ' newline ...
'            app.CegrEnabledCheckBox = uicheckbox(app.CegrPanel);' newline ...
'            app.CegrEnabledCheckBox.Text = ''启用 cEGR'';' newline ...
'            app.CegrEnabledCheckBox.Position = [10 5 100 22];' newline ...
'            app.CegrEnabledCheckBox.Value = false;' newline ...
'            ' newline ...
'            % Solver panel' newline ...
'            app.SolverPanel = uipanel(app.LeftPanel);' newline ...
'            app.SolverPanel.Title = ''求解器'';' newline ...
'            app.SolverPanel.Position = [10 160 450 60];' newline ...
'            app.SolverPanel.BackgroundColor = [1 1 1];' newline ...
'            ' newline ...
'            app.StopTimeLabel = uilabel(app.SolverPanel);' newline ...
'            app.StopTimeLabel.Position = [10 15 100 22];' newline ...
'            app.StopTimeLabel.Text = ''仿真时长 (s):'';' newline ...
'            ' newline ...
'            app.StopTimeEditField = uieditfield(app.SolverPanel, ''numeric'');' newline ...
'            app.StopTimeEditField.Position = [110 15 100 22];' newline ...
'            app.StopTimeEditField.Value = 600;' newline ...
'            ' newline ...
'            % Case ID' newline ...
'            app.CaseIdLabel = uilabel(app.LeftPanel);' newline ...
'            app.CaseIdLabel.Position = [10 125 100 22];' newline ...
'            app.CaseIdLabel.Text = ''Case ID:'';' newline ...
'            ' newline ...
'            app.CaseIdEditField = uieditfield(app.LeftPanel, ''text'');' newline ...
'            app.CaseIdEditField.Position = [110 125 200 22];' newline ...
'            app.CaseIdEditField.Value = ''case1'';' newline ...
'            ' newline ...
'            % Buttons' newline ...
'            app.RunButton = uibutton(app.LeftPanel, ''push'');' newline ...
'            app.RunButton.Position = [10 80 150 30];' newline ...
'            app.RunButton.Text = ''运行单工况'';' newline ...
'            app.RunButton.FontSize = 12;' newline ...
'            app.RunButton.FontWeight = ''bold'';' newline ...
'            app.RunButton.BackgroundColor = [0.2 0.6 0.2];' newline ...
'            app.RunButton.FontColor = [1 1 1];' newline ...
'            ' newline ...
'            app.MatrixButton = uibutton(app.LeftPanel, ''push'');' newline ...
'            app.MatrixButton.Position = [170 80 100 30];' newline ...
'            app.MatrixButton.Text = ''矩阵...'';' newline ...
'            app.MatrixButton.FontSize = 12;' newline ...
'            ' newline ...
'            % KPI table' newline ...
'            app.KpiTable = uitable(app.RightPanel);' newline ...
'            app.KpiTable.Position = [10 400 670 200];' newline ...
'            app.KpiTable.ColumnName = {''caseId'', ''V (V)'', ''I (A)'', ''P (kW)'', ''OER'', ''cEGR''};' newline ...
'            app.KpiTable.ColumnWidth = {100, 80, 80, 80, 60, 60};' newline ...
'            app.KpiTable.Data = {};' newline ...
'            ' newline ...
'            % Time series axes' newline ...
'            app.TimeSeriesAxes = uiaxes(app.RightPanel);' newline ...
'            app.TimeSeriesAxes.Position = [10 180 670 200];' newline ...
'            title(app.TimeSeriesAxes, ''时序曲线'');' newline ...
'            xlabel(app.TimeSeriesAxes, ''时间 (s)'');' newline ...
'            ylabel(app.TimeSeriesAxes, ''电压 (V) / 电流 (A) / 功率 (kW)'');' newline ...
'            grid(app.TimeSeriesAxes, ''on'');' newline ...
'            ' newline ...
'            % Log area' newline ...
'            app.LogLabel = uilabel(app.RightPanel);' newline ...
'            app.LogLabel.Position = [10 150 100 22];' newline ...
'            app.LogLabel.Text = ''运行日志:'';' newline ...
'            ' newline ...
'            app.LogTextArea = uitextarea(app.RightPanel);' newline ...
'            app.LogTextArea.Position = [10 10 670 130];' newline ...
'            app.LogTextArea.Value = {'' > 面板已就绪，请设置参数并点击"运行单工况"''};' newline ...
'            app.LogTextArea.Editable = ''off'';' newline ...
'            app.LogTextArea.FontName = ''Consolas'';' newline ...
'            ' newline ...
'            % Show figure after all components are created' newline ...
'            app.UIFigure.Visible = ''on'';' newline ...
'        end' newline ...
'    end' newline ...
'    ' newline ...
'    % App creation and deletion' newline ...
'    methods (Access = public)' newline ...
'        ' newline ...
'        function app = RouteA_Panel_v01' newline ...
'            % Create UIFigure and components' newline ...
'            createComponents(app)' newline ...
'            ' newline ...
'            % Initialize simCase with template' newline ...
'            app.simCase = routeA_simCase_template();' newline ...
'            app.simCase.caseId = app.CaseIdEditField.Value;' newline ...
'        end' newline ...
'        ' newline ...
'        function delete(app)' newline ...
'            % Delete UIFigure when app is deleted' newline ...
'            delete(app.UIFigure)' newline ...
'        end' newline ...
'    end' newline ...
'end' newline ...
];

% Write the .m file first (for version control)
mFilePath = 'RouteA_Panel_v01.m';
fid = fopen(mFilePath, 'w', 'n', 'UTF-8');
fprintf(fid, '%s', appClassCode);
fclose(fid);

fprintf('Created %s\n', mFilePath);
fprintf('To convert to .mlapp, open in App Designer:\n');
fprintf('  >> appdesigner(''%s'')\n', mFilePath);
fprintf('Then save as RouteA_Panel_v01.mlapp\n');

end
