function simCase = routeA_simCase_template()
% Return a fully populated simCase template with default values.
%
% The simCase struct is the standard input format for all Route A
% simulation tasks, covering CR3 three elements:
%   (a) initialState  - initial state of gas paths and stack
%   (b) controls      - electrical boundary, gas path, cEGR, thermal
%   (c) solver        - solver configuration
%
% Usage:
%   simCase = routeA_simCase_template();
%   simCase.caseId = 'my_case';
%   simCase.controls.electrical.mode = 'Power';
%   simCase.controls.electrical.profile = 40;
%   simCase = routeA_validate_case(simCase);  % fill defaults + validate
%
% See also: routeA_validate_case

%#ok<*NASGU>  % template file, intentional unused assignments

%% Derive defaults from platform parameter file (single source of truth)
params = routeA_platform_default_parameters();
pCtrl = params.controls;
pEnv  = params.environment;
pCath = params.cathode;
pAnode = params.anode;
pTherm = params.thermal;
pNum = params.numerics;
pStack = params.stack;

%% (a) 初始状态
initialState = struct();
initialState.mode = 'cold';                              % active Route A policy: cold-start-only
initialState.source = 'model_default_cold';              % active cold provenance
initialState.temperature_C = pEnv.ambient_T_C.value;     % 冷态初始温度 [degC]
initialState.pressure_MPa_abs = pEnv.ambient_p_MPa_abs.value;  % 冷态初始压力 [MPa(abs)]
initialState.o2MoleFraction = pEnv.o2_mole_fraction.value;     % 冷态初始 O2 分数
initialState.h2oMoleFraction = pEnv.h2o_mole_fraction.value;   % 冷态初始 H2O 分数
initialState.h2MoleFraction = pAnode.tank.yH2.value;           % 冷态初始 H2 分数

%% (b) 控制设置
% 电边界控制
electrical = struct();
electrical.mode = 'Current';           % 'Current' | 'Power' | 'Voltage'
electrical.profile = [];               % 标量或 Nx2 矩阵 [t, value]
electrical.voltageController = [];     % Filled after the default PI struct is defined

% Voltage 模式 PI 控制器参数（默认值）
voltageController = struct();
voltageController.Kp_A_V = pCtrl.voltage_pi_Kp.value;        % 比例增益 [A/V]
voltageController.Ki_A_V_s = pCtrl.voltage_pi_Ki.value;      % 积分增益 [A/V/s]
voltageController.currentMin_A = pCtrl.voltage_current_min_A.value;  % 电流下限 [A]
voltageController.currentMax_A = pCtrl.voltage_current_max_A.value;  % 电流上限 [A]
electrical.voltageController = voltageController;

% 阴极气路控制
cathode = struct();
cathode.airControlMode = pCtrl.air_control_mode.value;       % 1=流量/2=OER/3=直接
cathode.targetOer = pCtrl.target_oer.value;                  % 目标 OER
cathode.targetMdot_kg_s = pCtrl.target_mdot_kg_s.value;      % 目标质量流量 [kg/s]
cathode.directCommand = pCtrl.air_direct_command.value;      % 空压机归一化执行命令 [0,1]，仍经过压缩机图谱
 cathode.airController = struct( ...
    'Kp', pCtrl.air_pid_Kp.value, ...
    'Ki', pCtrl.air_pid_Ki.value);
cathode.sourcePressure_MPa_abs = pCtrl.cathode_source_pressure_MPa_abs.value;  % 阴极源压力
cathode.sourceTemperature_C = pCtrl.cathode_source_temperature_C.value;        % 阴极源温度
cathode.o2MoleFraction = pEnv.o2_mole_fraction.value;        % 阴极 O2 分数 -> env_yO2
cathode.h2oMoleFraction = pEnv.h2o_mole_fraction.value;      % 阴极 H2O 分数 -> env_yH20
cathode.outletPressure_MPa_abs = pCtrl.backpressure_MPa_abs.value;             % 阴极出口压力/背压
cathode.humidifierRH = pCath.humidifier.default_rh.value;   % 加湿器设定 RH
cathode.humidifierEnabled = pCath.humidifier.enabled.value;  % 加湿器启用 [0/1]

% cEGR 控制
cegr = struct();
cegr.enabled = pCtrl.cegr_enabled.value;                     % cEGR 启用
cegr.targetRatio = pCtrl.cegr_target_ratio.value;            % 目标 cEGR 比
cegr.valveMode = pCtrl.cegr_valve_mode.value;                % 阀模式 [1=开度/2=压力]
cegr.controlMode = pCtrl.cegr_control_mode.value;            % 控制模式
cegr.targetInputMode = 1;                                    % 目标输入模式
cegr.controller = struct( ...
    'Kp_area', params.cegr.control.Kp_area.value, ...
    'Ki_area', params.cegr.control.Ki_area.value, ...
    'actuatorTau_s', params.cegr.actuator_tau_s.value);
cegr.directValveArea_m2 = pCtrl.cegr_direct_area_m2.value;
cegr.directTargetRatio = pCtrl.target_egr_ratio_comp_in.value;

% 阳极控制
anode = struct();
anode.sourcePressure_MPa_abs = pCtrl.anode_source_pressure_MPa_abs.value;   % 氢源压力
anode.sourceTemperature_C = pCtrl.anode_source_temperature_C.value;         % 氢源温度
anode.h2MoleFraction = pAnode.tank.yH2.value;                              % 阳极 H2 分数 -> tank_yH2
anode.inletPressure_MPa_abs = pAnode.default_pressure_MPa_abs.value;        % 阳极入口压力
anode.humidifierRH = pAnode.humidifier.default_rh.value;                   % 阳极加湿 RH
anode.recirculationBaseCommand = pCtrl.anode_recirc_base.value;            % 回流基础命令
anode.recirculationCurrentGain_A_inv = pCtrl.anode_recirc_gain_A_inv.value; % 回流电流增益
anode.purgeEnabled = pCtrl.anode_purge_enable.value;                       % 吹扫启用 [0/1]
anode.purgeOnN2MoleFraction = pCtrl.anode_purge_on_n2.value;               % 吹扫开启 N2 阈值
anode.purgeOffN2MoleFraction = pCtrl.anode_purge_off_n2.value;             % 吹扫关闭 N2 阈值

% 热管理控制
thermal = struct();
thermal.stackTemperatureSet_C = pTherm.stack_temperature_set_C.value;  % 堆温/加湿器TIn温度设定 [degC]

% 环境/边界条件
environment = struct();
environment.ambientPressure_MPa_abs = pEnv.ambient_p_MPa_abs.value;  % 固定标准大气压（只读追溯）
environment.ambientTemperature_C = pEnv.ambient_T_C.value;           % 环境温度
environment.o2MoleFraction = pEnv.o2_mole_fraction.value;            % 环境 O2 分数 -> env_yO2
environment.h2oMoleFraction = pEnv.h2o_mole_fraction.value;          % 环境 H2O 分数 -> env_yH20
environment.h2MoleFraction = pAnode.tank.yH2.value;                  % 阳极 H2 分数 -> tank_yH2

% 组合 controls
controls = struct();
controls.electrical = electrical;
controls.cathode = cathode;
controls.cegr = cegr;
controls.anode = anode;
controls.thermal = thermal;
controls.environment = environment;
controls.stack = struct( ...
    'numCells', pStack.num_cells.value, ...
    'area_cm2', pStack.area_cm2.value, ...
    'iL_A_cm2', pStack.iL_A_cm2.value, ...
    'io_A_cm2', pStack.io_A_cm2.value);

% Scalar equipment-performance inputs. These are deliberately separated
% from operating-condition controls so the panel can identify which values
% describe the selected hardware rather than the requested study point.
controls.devices = struct();
controls.devices.stack = struct( ...
    'alpha', pStack.alpha.value, ...
    'meaCp_J_kgK', pStack.mea_cp.value, ...
    'meaRho_kg_m3', pStack.mea_rho.value, ...
    'gdlThickness_um', pStack.t_gdl_um.value, ...
    'membraneThickness_um', pStack.t_membrane_um.value);
controls.devices.cathode = struct( ...
    'intercoolerMdotNominal_kg_s', ...
        pCath.intercooler.mdot_nominal_kg_s.value, ...
    'intercoolerDpNominal_MPa', ...
        pCath.intercooler.dp_nominal_MPa.value, ...
    'intercoolerArea_m2', pCath.intercooler.area_m2.value, ...
    'intercoolerLaminarFraction', ...
        pCath.intercooler.laminar_fraction.value, ...
    'separatorMdotNominal_kg_s', ...
        pCath.separator.mdot_nominal_kg_s.value, ...
    'separatorDpNominal_MPa', ...
        pCath.separator.dp_nominal_MPa.value, ...
    'separatorArea_m2', pCath.separator.area_m2.value, ...
    'separatorLaminarFraction', pCath.separator.laminar_fraction.value, ...
    'mixerVolume_L', pCath.mixer.volume_L.value, ...
    'outletChamberVolume_L', pCath.outlet_chamber.volume_L.value, ...
    'compressorMap', struct( ...
        'rpm_TLU', pCath.compressor.rpm_TLU.value, ...
        'p_ratio_TLU', pCath.compressor.p_ratio_TLU.value, ...
        'mdot_corr_TLU', pCath.compressor.mdot_corr_TLU.value, ...
        'source', string(pCath.compressor.rpm_TLU.source), ...
        'schemaVersion', "RouteA_CompressorMap_v01"));
controls.devices.cegr = struct( ...
    'valveMaxArea_m2', params.cegr.valve_max_area_m2.value, ...
    'pipeLength_m', params.cegr.pipe.length_m.value, ...
    'pipeDiameter_m', params.cegr.pipe.D_m.value, ...
    'pipeRoughness_m', params.cegr.pipe.roughness_m.value, ...
    'condensationTau_s', params.cegr.condensation_tau_s.value, ...
    'inletMixerPressure_MPa_abs', params.cegr.inlet_mixer_p0_MPa_abs.value, ...
    'outletChamberPressure_MPa_abs', params.cegr.outlet_chamber_p0_MPa_abs.value, ...
    'pipeExtraLength_m', params.cegr.pipe.extra_length_m.value, ...
    'pipePressure_MPa_abs', params.cegr.pipe.p0_MPa_abs.value, ...
    'valveOpenMinArea_m2', params.cegr.valve_open_min_area_m2.value);
controls.devices.anode = struct( ...
    'tankPressure_MPa', pAnode.tank.p_MPa.value, ...
    'tankVolume_L', pAnode.tank.V_L.value, ...
    'tankTemperature_C', pAnode.tank.T_C.value, ...
    'separatorMdotNominal_kg_s', pAnode.separator.mdot_nominal_kg_s.value, ...
    'separatorDpNominal_MPa', pAnode.separator.dp_nominal_MPa.value, ...
    'separatorArea_m2', pAnode.separator.area_m2.value, ...
    'separatorLaminarFraction', pAnode.separator.laminar_fraction.value);
controls.devices.thermal = struct();
controls.devices.thermal.coolantGeometry = struct( ...
    'channelWidth_cm', pTherm.coolant.w_channels_cm.value, ...
    'numLayers', pTherm.coolant.num_layers.value, ...
    'numPasses', pTherm.coolant.num_passes.value, ...
    'tubeDiameter_m', pTherm.coolant.tube_D_m.value);
controls.devices.thermal.radiatorCore = struct( ...
    'length_m', pTherm.radiator.L_m.value, ...
    'width_m', pTherm.radiator.W_m.value, ...
    'height_m', pTherm.radiator.H_m.value, ...
    'tubeCount', pTherm.radiator.N_tubes.value, ...
    'tubeHeight_m', pTherm.radiator.tube_H_m.value, ...
    'finSpacing_m', pTherm.radiator.fin_spacing_m.value, ...
    'finEfficiency', pTherm.radiator.eta_fin.value, ...
    'wallThickness_m', pTherm.radiator.t_wall_m.value, ...
    'density_kg_m3', pTherm.radiator.rho_kg_m3.value, ...
    'specificHeat_J_kgK', pTherm.radiator.cp_J_kgK.value);

%% (c) 求解器设置
solver = struct();
solver.stopTime_s = pNum.stopTime_s.value;        % 仿真时长 [s]
solver.solver = pNum.solver.value;                % 求解器类型
solver.relTol = pNum.relTol.value;                % 相对容差
solver.absTol = pNum.absTol.value;                % 绝对容差
solver.maxStep_s = pNum.maxStep_s.value;          % 最大步长 [s]
solver.signalLogging = 'on';                      % 信号日志
solver.signalLoggingName = 'logsout';             % 日志名称
solver.simscapeLogType = 'all';                   % Simscape 日志类型
solver.returnWorkspaceOutputs = 'on';             % 返回工作区输出
solver.saveOperatingPoint = 'off';                % active runs never save an operating point

%% 组合顶层 simCase
simCase = struct();
simCase.caseId = '';
simCase.description = '';
simCase.initialState = initialState;
simCase.controls = controls;
simCase.solver = solver;

end
