function registry = routeA_parameter_registry(paths)
% Return the Route A parameter registry for platform and study inputs.
%
% Active entries describe parameters that the current SimulationInput chain
% can set. Platform leaves are also inventoried, but remain closed to the UI
% until their range, model mapping, compile behavior, and response are known.

if nargin < 1 || isempty(paths)
    paths = routeA_project_paths();
end

params = routeA_platform_default_parameters();
entries = repmat(entryTemplate(), 0, 1);

% Study and runtime controls.
add("electrical.mode", "Electrical boundary mode", "electrical", "-", ...
    "Current", [], [], "simCase.controls.electrical", "", ...
    "input_type", "", "study", "no", "validated", "low", ...
    "Select exactly one Current, Power, or Voltage boundary.", "active");
add("electrical.current.profile", "Current command", "electrical", "A", ...
    params.controls.current_default_ref_A.value, 0, 392, ...
    "platform_default", "drive_cycle_current", "", "", "runtime", "no", ...
    "validated", "low", "Current-mode FromWorkspace data column.", "active");
add("electrical.power.profile", "Power command", "electrical", "kW", ...
    params.controls.power_default_ref_kW.value, 0, 150, ...
    "platform_default", "drive_cycle_power", "", "", "runtime", "no", ...
    "validated", "low", "Power-mode FromWorkspace data column.", "active");
add("electrical.voltage.profile", "Voltage command", "electrical", "V", ...
    params.controls.voltage_default_ref_V.value, 0, 500, ...
    "platform_default", "drive_cycle_voltage", "", "", "runtime", "no", ...
    "validated", "low", "Voltage-mode reference data column.", "active");
add("electrical.voltageController.Kp_A_V", "Voltage PI Kp", "electrical", "A/V", ...
    params.controls.voltage_pi_Kp.value, 0, Inf, "platform_default", ...
    "routeA_voltage_pi_Kp", "", "", "controller", "compile", ...
    "validated", "medium", "Voltage controller proportional gain.", "active");
add("electrical.voltageController.Ki_A_V_s", "Voltage PI Ki", "electrical", "A/V/s", ...
    params.controls.voltage_pi_Ki.value, 0, Inf, "platform_default", ...
    "routeA_voltage_pi_Ki", "", "", "controller", "compile", ...
    "validated", "medium", "Voltage controller integral gain.", "active");
add("electrical.voltageController.currentMin_A", "Voltage current lower limit", ...
    "electrical", "A", params.controls.voltage_current_min_A.value, 0, 392, ...
    "platform_default", "routeA_voltage_current_min_A", "", "", "controller", ...
    "compile", "validated", "medium", "Voltage controller lower saturation.", "active");
add("electrical.voltageController.currentMax_A", "Voltage current upper limit", ...
    "electrical", "A", params.controls.voltage_current_max_A.value, 0, 392, ...
    "platform_default", "routeA_voltage_current_max_A", "", "", "controller", ...
    "compile", "validated", "medium", "Voltage controller upper saturation.", "active");

add("cathode.airControlMode", "Air control mode", "cathode", "-", ...
    params.controls.air_control_mode.value, 1, 3, "platform_default", ...
    "routeA_air_control_mode_id", "", "", "controller", "compile", ...
    "validated", "medium", "1=mass flow, 2=OER, 3=direct command.", "active");
add("cathode.targetOer", "Target OER", "cathode", "-", ...
    params.controls.target_oer.value, 1.5, 5, "platform_default", ...
    "routeA_command_profile", "", "air_target_oer", "runtime", "no", ...
    "validated", "medium", "Fresh-air oxygen excess ratio target.", "active");
add("cathode.targetMdot_kg_s", "Target cathode mass flow", "cathode", "kg/s", ...
    params.controls.target_mdot_kg_s.value, 0, Inf, "platform_default", ...
    "routeA_command_profile", "", "air_target_mdot_kg_s", "runtime", "no", ...
    "validated", "medium", "Fresh-air mass-flow target.", "active");
add("cathode.directCommand", "Direct air command", "cathode", "-", ...
    params.controls.air_direct_command.value, 0, 1, "platform_default", ...
    "routeA_command_profile", "", "air_direct_command", "runtime", "no", ...
    "validated", "medium", ...
    "Normalized compressor execution command in [0,1]; mode 3 bypasses OER/target-flow conversion and flow PI but still drives the compressor map.", "active");
add("cathode.sourcePressure_MPa_abs", "Cathode source pressure", "cathode", ...
    "MPa(abs)", params.controls.cathode_source_pressure_MPa_abs.value, ...
    0.1, 0.5, "platform_default", "routeA_command_profile", "", ...
    "cathode_source_pressure_MPa_abs", "runtime", "no", "validated", "medium", ...
    "Fresh-air source pressure boundary.", "active");
add("cathode.sourceTemperature_C", "Cathode source temperature", "cathode", ...
    "degC", params.controls.cathode_source_temperature_C.value, 10, 60, ...
    "platform_default", "routeA_command_profile", "", ...
    "cathode_source_temperature_C", "runtime", "no", "validated", "medium", ...
    "Fresh-air source temperature boundary.", "active");
add("cathode.outletPressure_MPa_abs", "Cathode outlet pressure", "cathode", ...
    "MPa(abs)", params.controls.backpressure_MPa_abs.value, 0.1, 0.3, ...
    "platform_default", "routeA_command_profile", "", ...
    "cathode_outlet_pressure_MPa_abs", "runtime", "no", "validated", "medium", ...
    "Cathode exhaust backpressure setpoint.", "active");
add("cathode.humidifierRH", "Cathode humidifier RH", "cathode", "-", ...
    params.cathode.humidifier.default_rh.value, 0, 1, "platform_default", ...
    "routeA_command_profile", "", "cathode_humidifier_rh", "runtime", "no", ...
    "validated", "medium", ...
    "RH at humidifier outlet / cathode inlet; temperature reference is the current T_stack path.", "active");
add("cathode.humidifierEnabled", "Cathode humidifier enabled", "cathode", "-", ...
    params.cathode.humidifier.enabled.value, 0, 1, "platform_default", ...
    "routeA_command_profile", "", "cathode_humidifier_gain", "runtime", "no", ...
    "validated", "medium", "0=bypass, 1=humidifier enabled.", "active");
add("cathode.o2MoleFraction", "Cathode inlet O2 fraction", "cathode", "-", ...
    params.environment.o2_mole_fraction.value, 0.15, 0.21, "platform_default", ...
    "env_yO2", "", "", "compile", "compile", "validated", "medium", ...
    "Air Intake reservoir compile-time O2 composition.", "active");
add("cathode.h2oMoleFraction", "Cathode inlet H2O fraction", "cathode", "-", ...
    params.environment.h2o_mole_fraction.value, 0.005, 0.04, "platform_default", ...
    "env_yH20", "", "", "compile", "compile", "validated", "high", ...
    "Legacy model variable name env_yH20 is retained as an explicit mapping.", "active");

add("cegr.enabled", "cEGR enabled", "cegr", "-", ...
    params.controls.cegr_enabled.value, false, true, "platform_default", ...
    "routeA_cegr_enabled", "", "", "compile", "compile", "validated", "medium", ...
    "Keep the cEGR topology and select the valve operating mode.", "active");
add("cegr.targetRatio", "cEGR target ratio", "cegr", "-", ...
    params.controls.cegr_target_ratio.value, 0, 0.5, "platform_default", ...
    "routeA_command_profile", "", "cegr_ratio", "runtime", "no", ...
    "validated", "high", "Target cEGR ratio for the closed-loop mode.", "active");
add("cegr.valveMode", "cEGR valve mode", "cegr", "-", ...
    params.controls.cegr_valve_mode.value, 1, 1, "platform_default", ...
    "routeA_cegr_valve_mode_id", "", "", "compile", "compile", ...
    "validated", "high", ...
    "Fixed open-area variant; the active model has no pressure-mode branch.", "fixed");
add("cegr.controlMode", "cEGR control mode", "cegr", "-", ...
    params.controls.cegr_control_mode.value, 1, 2, "platform_default", ...
    "routeA_egr_control_mode_id", "", "", "compile", "compile", ...
    "validated", "medium", "1=target-ratio closed loop; 2=direct cEGR branch.", "active");
add("cegr.targetInputMode", "cEGR target input mode", "cegr", "-", 1, 1, 1, ...
    "platform_default", "routeA_egr_target_input_mode_id", "", "", "compile", ...
    "compile", "validated", "medium", "Current Route A cEGR target input mode.", "active");
add("cegr.controller.Kp_area", "cEGR PI Kp", "cegr", "m^2", ...
    params.cegr.control.Kp_area.value, eps, Inf, "platform_default", ...
    "routeA_egr_control_Kp_area", "", "", "controller", "compile", ...
    "validated", "medium", "cEGR target-ratio controller proportional gain.", "active");
add("cegr.controller.Ki_area", "cEGR PI Ki", "cegr", "m^2/s", ...
    params.cegr.control.Ki_area.value, eps, Inf, "platform_default", ...
    "routeA_egr_control_Ki_area", "", "", "controller", "compile", ...
    "validated", "medium", "cEGR target-ratio controller integral gain.", "active");
add("cegr.actuatorTau_s", "cEGR actuator time constant", "cegr", "s", ...
    params.cegr.actuator_tau_s.value, eps, Inf, "platform_default", ...
    "routeA_egr_valve_actuator_tau", "", "", "actuator", "compile", ...
    "validated", "medium", "cEGR valve actuator first-order time constant.", "active");

% Anode source pressure/temperature are explicit case-level overrides of
% the Fuel Tank initial boundary. The profile fields remain for schema
% compatibility, but the physical consumers are tank_p and tank_T.
add("anode.sourcePressure_MPa_abs", "Anode source pressure", "anode", ...
    "MPa(abs)", params.controls.anode_source_pressure_MPa_abs.value, ...
    0.2, 0.5, "platform_default", "tank_p", "", ...
    "anode_source_pressure_MPa_abs", "runtime", "no", "validated", "medium", ...
    "Case-level Fuel Tank pressure override; default releases to device setting.", "active");
add("anode.sourceTemperature_C", "Anode source temperature", "anode", ...
    "degC", params.controls.anode_source_temperature_C.value, 10, 60, ...
    "platform_default", "tank_T", "", ...
    "anode_source_temperature_C", "runtime", "no", "validated", "medium", ...
    "Case-level Fuel Tank temperature override; default releases to device setting.", "active");
add("anode.h2MoleFraction", "Anode H2 mole fraction", "anode", "-", ...
    params.anode.tank.yH2.value, 0.9, 1.0, "platform_default", "tank_yH2", ...
    "", "anode_source_h2_mole_fraction", "compile", "compile", "validated", ...
    "high", "Hydrogen tank composition; applied before simulation.", "active");
add("anode.inletPressure_MPa_abs", "Anode inlet pressure", "anode", ...
    "MPa(abs)", params.anode.default_pressure_MPa_abs.value, 0.1, 0.3, ...
    "platform_default", "routeA_command_profile", "", ...
    "anode_inlet_pressure_MPa_abs", "runtime", "no", "validated", "medium", ...
    "Anode inlet pressure setpoint.", "active");
add("anode.humidifierRH", "Anode humidifier RH", "anode", "-", ...
    params.anode.humidifier.default_rh.value, 0, 1, "platform_default", ...
    "routeA_command_profile", "", "anode_humidifier_rh", "runtime", "no", ...
    "validated", "medium", "Anode inlet relative humidity command.", "active");
add("anode.recirculationBaseCommand", "Anode recirculation base", ...
    "anode", "-", params.anode.recirculation.base_command.value, 0, 1, ...
    "platform_default", "routeA_command_profile", "", ...
    "anode_recirculation_base", "runtime", "no", "validated", "medium", ...
    "Anode recirculation base command.", "active");
add("anode.recirculationCurrentGain_A_inv", ...
    "Anode recirculation current gain", "anode", "1/A", ...
    params.anode.recirculation.current_gain_A_inv.value, 0, 1, ...
    "platform_default", "routeA_command_profile", "", ...
    "anode_recirculation_current_gain_A_inv", "runtime", "no", ...
    "validated", "medium", "Current-related anode recirculation compensation.", "active");
add("anode.purgeEnabled", "Anode purge enabled", "anode", "-", ...
    params.anode.purge.enabled.value, 0, 1, "platform_default", ...
    "routeA_command_profile", "", "anode_purge_enable", "runtime", "no", ...
    "validated", "medium", "Anode purge on/off command.", "active");
add("anode.purgeOnN2MoleFraction", "Anode purge-on N2 threshold", ...
    "anode", "-", params.anode.purge.on_n2_mole_fraction.value, 0, 1, ...
    "platform_default", "routeA_command_profile", "", ...
    "anode_purge_on_n2_mole_fraction", "runtime", "no", "validated", "medium", ...
    "N2 fraction that opens the purge path.", "active");
add("anode.purgeOffN2MoleFraction", "Anode purge-off N2 threshold", ...
    "anode", "-", params.anode.purge.off_n2_mole_fraction.value, 0, 1, ...
    "platform_default", "routeA_command_profile", "", ...
    "anode_purge_off_n2_mole_fraction", "runtime", "no", "validated", "medium", ...
    "N2 fraction that closes the purge path.", "active");

add("stack.numCells", "Stack cell count", "stack", "-", ...
    params.stack.num_cells.value, 1, 1000, "platform_default", ...
    "stack_num_cells", "", "", "stack", "compile", "validated", "high", ...
    "Number of cells used by the active stack model.", "active");
add("stack.area_cm2", "Stack active area", "stack", "cm^2", ...
    params.stack.area_cm2.value, 1, 1000, "platform_default", ...
    "stack_area", "", "", "stack", "compile", "validated", "high", ...
    "Active electrochemical area of each stack cell.", "active");
add("stack.iL_A_cm2", "Stack limiting current density", "stack", ...
    "A/cm^2", params.stack.iL_A_cm2.value, 1e-3, 5, "platform_default", ...
    "stack_iL", "", "", "stack", "compile", "validated", "high", ...
    "Limiting current density used by the active electrochemical model.", "active");
add("stack.io_A_cm2", "Stack exchange current density", "stack", ...
    "A/cm^2", params.stack.io_A_cm2.value, 1e-8, 0.1, "platform_default", ...
    "stack_io", "", "", "stack", "compile", "validated", "high", ...
    "Exchange current density used by the active electrochemical model.", "active");

% First-stage scalar equipment-performance inputs. Curve/table assets remain
% inventory-only and are intentionally deferred to the second-stage editor.
add("device.stack.alpha", "Stack charge-transfer coefficient", "stack", "-", ...
    params.stack.alpha.value, 0.1, 1.5, "platform_default", "stack_alpha", ...
    "", "", "stack", "compile", "validated", "high", ...
    "Charge-transfer coefficient of the selected MEA.", "active");
add("device.stack.meaCp_J_kgK", "MEA specific heat capacity", "stack", ...
    "J/(kg*K)", params.stack.mea_cp.value, 100, 5000, "platform_default", ...
    "stack_mea_cp", "", "", "stack", "compile", "validated", "medium", ...
    "Thermal capacity of the active MEA representation.", "active");
add("device.stack.meaRho_kg_m3", "MEA density", "stack", "kg/m^3", ...
    params.stack.mea_rho.value, 100, 5000, "platform_default", "stack_mea_rho", ...
    "", "", "stack", "compile", "validated", "medium", ...
    "Density used by the active MEA thermal representation.", "active");
add("device.stack.gdlThickness_um", "GDL thickness", "stack", "um", ...
    params.stack.t_gdl_um.value, 1, 2000, "platform_default", "stack_t_gdl", ...
    "", "", "stack", "compile", "validated", "medium", ...
    "Gas diffusion layer thickness.", "active");
add("device.stack.membraneThickness_um", "Membrane thickness", "stack", "um", ...
    params.stack.t_membrane_um.value, 1, 1000, "platform_default", ...
    "stack_t_membrane", "", "", "stack", "compile", "validated", "medium", ...
    "Membrane thickness.", "active");

add("device.cathode.intercoolerMdotNominal_kg_s", ...
    "Intercooler nominal mass flow", "cathode", "kg/s", ...
    params.cathode.intercooler.mdot_nominal_kg_s.value, eps, 1, ...
    "platform_default", "intercooler_mdot_nominal", "", "", "intercooler", ...
    "compile", "validated", "medium", "Intercooler nominal flow capacity.", "active");
add("device.cathode.intercoolerDpNominal_MPa", ...
    "Intercooler nominal pressure drop", "cathode", "MPa", ...
    params.cathode.intercooler.dp_nominal_MPa.value, 0, 0.1, ...
    "platform_default", "intercooler_dp_nominal", "", "", "intercooler", ...
    "compile", "validated", "medium", "Intercooler nominal pressure loss.", "active");
add("device.cathode.intercoolerArea_m2", "Intercooler flow area", ...
    "cathode", "m^2", params.cathode.intercooler.area_m2.value, ...
    1e-8, 0.1, "platform_default", "intercooler_area", "", "", ...
    "intercooler", "compile", "validated", "medium", ...
    "Active intercooler Flow Resistance (FC) area.", "active");
add("device.cathode.intercoolerLaminarFraction", ...
    "Intercooler laminar fraction", "cathode", "-", ...
    params.cathode.intercooler.laminar_fraction.value, 0, 1, ...
    "platform_default", "intercooler_laminar_fraction", "", "", ...
    "intercooler", "compile", "validated", "medium", ...
    "Laminar-loss fraction of the active intercooler resistance.", "active");
add("device.cathode.intercoolerCondTau_s", ...
    "Intercooler condensation time constant", "cathode", "s", 1, eps, 1000, ...
    "platform_default", "intercooler_cond_tau", "", "", "intercooler", ...
    "compile", "unresolved", "medium", ...
    "Current Route A has no block parameter bound to this workspace item.", "unresolved");
add("device.cathode.separatorMdotNominal_kg_s", ...
    "Cathode separator nominal mass flow", "cathode", "kg/s", ...
    params.cathode.separator.mdot_nominal_kg_s.value, eps, 1, ...
    "platform_default", "cathode_separator_mdot_nominal", "", "", "separator", ...
    "compile", "validated", "medium", "Cathode separator nominal flow capacity.", "active");
add("device.cathode.separatorDpNominal_MPa", ...
    "Cathode separator nominal pressure drop", "cathode", "MPa", ...
    params.cathode.separator.dp_nominal_MPa.value, 0, 0.1, ...
    "platform_default", "cathode_separator_dp_nominal", "", "", "separator", ...
    "compile", "validated", "medium", "Cathode separator nominal pressure loss.", "active");
add("device.cathode.separatorArea_m2", "Cathode separator flow area", ...
    "cathode", "m^2", params.cathode.separator.area_m2.value, 1e-8, 0.1, ...
    "platform_default", "cathode_separator_area", "", "", "separator", ...
    "compile", "validated", "medium", ...
    "Active Flow Resistance (FC) flow area; it is not a separator vessel diameter.", "active");
add("device.cathode.separatorLaminarFraction", ...
    "Cathode separator laminar fraction", "cathode", "-", ...
    params.cathode.separator.laminar_fraction.value, 0, 1, ...
    "platform_default", "cathode_separator_laminar_fraction", "", "", "separator", ...
    "compile", "validated", "medium", ...
    "Laminar-loss fraction of the active Flow Resistance (FC) block.", "active");
add("device.cathode.mixerVolume_L", "Compressor inlet mixer volume", ...
    "cathode", "L", params.cathode.mixer.volume_L.value, eps, 1000, ...
    "platform_default", "comp_inlet_mixer_V", "", "", "mixer", "compile", ...
    "validated", "medium", "Compressor inlet mixing volume.", "active");
add("device.cathode.outletChamberVolume_L", "Cathode outlet chamber volume", ...
    "cathode", "L", params.cathode.outlet_chamber.volume_L.value, eps, 1000, ...
    "platform_default", "cathode_outlet_chamber_V", "", "", "chamber", "compile", ...
    "validated", "medium", "Cathode outlet gas volume.", "active");

% The compressor map is one equipment dataset, but its three arrays remain
% independently visible for traceability. The panel editor applies all
% three arrays atomically after routeA_validate_compressor_map succeeds.
add("device.cathode.compressorMap.rpm_TLU", "Compressor speed breakpoints", ...
    "cathode", "rpm", params.cathode.compressor.rpm_TLU.value, [], [], ...
    "platform_default", "comp_rpm_TLU", "", "", "compressor_map", ...
    "compile", "validated", "high", ...
    "Strictly increasing compressor-speed axis edited in the compressor map editor.", "active");
add("device.cathode.compressorMap.p_ratio_TLU", "Compressor pressure-ratio breakpoints", ...
    "cathode", "-", params.cathode.compressor.p_ratio_TLU.value, [], [], ...
    "platform_default", "comp_p_ratio_TLU", "", "", "compressor_map", ...
    "compile", "validated", "high", ...
    "Strictly increasing pressure-ratio axis (minimum 1) edited in the compressor map editor.", "active");
add("device.cathode.compressorMap.mdot_corr_TLU", "Compressor corrected mass-flow table", ...
    "cathode", "kg/s", params.cathode.compressor.mdot_corr_TLU.value, [], [], ...
    "platform_default", "comp_mdot_corr_TLU", "", "", "compressor_map", ...
    "compile", "validated", "high", ...
    "Nonnegative M-by-N lookup table matched to pressure-ratio and speed axes.", "active");

add("device.cegr.valveMaxArea_m2", "cEGR valve maximum opening area", ...
    "cegr", "m^2", params.cegr.valve_max_area_m2.value, eps, 1, ...
    "platform_default", "cegr_valve_max_area", "", "", "valve", "compile", ...
    "validated", "high", "Maximum physical cEGR valve opening area.", "active");
add("device.cegr.pipeLength_m", "cEGR pipe length", "cegr", "m", ...
    params.cegr.pipe.length_m.value, 1e-4, 100, "platform_default", ...
    "cegr_pipe_length", "", "", "pipe", "compile", "validated", "medium", ...
    "cEGR pipe flow length.", "active");
add("device.cegr.pipeDiameter_m", "cEGR pipe diameter", "cegr", "m", ...
    params.cegr.pipe.D_m.value, 1e-4, 1, "platform_default", "cegr_pipe_D", ...
    "", "", "pipe", "compile", "validated", "medium", ...
    "Canonical cEGR pipe diameter; SimulationInput derives cegr_pipe_area from this value.", "active");
add("device.cegr.pipeRoughness_m", "cEGR pipe roughness", "cegr", "m", ...
    params.cegr.pipe.roughness_m.value, 0, 0.01, "platform_default", ...
    "cegr_pipe_roughness", "", "", "pipe", "compile", "validated", "medium", ...
    "cEGR pipe wall roughness.", "active");
add("device.cegr.condensationTau_s", "cEGR condensation time constant", ...
    "cegr", "s", params.cegr.condensation_tau_s.value, eps, 1000, ...
    "platform_default", "cegr_cond_tau", "", "", "cegr_branch", ...
    "compile", "validated", "medium", ...
    "Time constant used by the active cEGR condensation dynamics.", "active");
add("device.cegr.inletMixerPressure_MPa_abs", ...
    "cEGR inlet mixer reference pressure", "cegr", "MPa(abs)", ...
    params.cegr.inlet_mixer_p0_MPa_abs.value, 0.01, 1, ...
    "platform_default", "cegr_inlet_mixer_p0", "", "", "cegr_branch", ...
    "compile", "validated", "medium", ...
    "Reference pressure of the cEGR compressor inlet mixer.", "active");
add("device.cegr.outletChamberPressure_MPa_abs", ...
    "cEGR outlet chamber reference pressure", "cegr", "MPa(abs)", ...
    params.cegr.outlet_chamber_p0_MPa_abs.value, 0.01, 1, ...
    "platform_default", "cegr_outlet_chamber_p0", "", "", "cegr_branch", ...
    "compile", "validated", "medium", ...
    "Reference pressure of the cathode outlet chamber used by cEGR.", "active");
add("device.cegr.pipeExtraLength_m", "cEGR pipe extra length", "cegr", "m", ...
    params.cegr.pipe.extra_length_m.value, 0, 100, "platform_default", ...
    "cegr_pipe_extra_length", "", "", "cegr_branch", "compile", "validated", "medium", ...
    "Additional equivalent flow length of the cEGR pipe.", "active");
add("device.cegr.pipePressure_MPa_abs", "cEGR pipe reference pressure", ...
    "cegr", "MPa(abs)", params.cegr.pipe.p0_MPa_abs.value, 0.01, 1, ...
    "platform_default", "cegr_pipe_p0", "", "", "cegr_branch", ...
    "compile", "validated", "medium", ...
    "Reference pressure used by the cEGR pipe model.", "active");
add("device.cegr.valveOpenMinArea_m2", "cEGR valve minimum opening area", ...
    "cegr", "m^2", params.cegr.valve_open_min_area_m2.value, 1e-12, 1, ...
    "platform_default", "cegr_valve_open_min_area", "", "", "valve", ...
    "compile", "validated", "medium", ...
    "Lower numerical/physical opening limit of the cEGR valve.", "active");

add("device.anode.tankPressure_MPa", "Hydrogen tank pressure", "anode", ...
    "MPa", params.anode.tank.p_MPa.value, 0.1, 100, "platform_default", ...
    "tank_p", "", "", "tank", "compile", "validated", "medium", ...
    "Hydrogen storage tank pressure.", "active");
add("device.anode.tankVolume_L", "Hydrogen tank volume", "anode", "L", ...
    params.anode.tank.V_L.value, eps, 1e5, "platform_default", "tank_V", ...
    "", "", "tank", "compile", "validated", "medium", ...
    "Hydrogen storage tank volume.", "active");
add("device.anode.tankTemperature_C", "Hydrogen tank temperature", "anode", ...
    "degC", params.anode.tank.T_C.value, -50, 150, "platform_default", "tank_T", ...
    "", "", "tank", "compile", "validated", "medium", ...
    "Hydrogen storage tank temperature.", "active");
add("device.anode.separatorArea_m2", "Anode separator flow area", ...
    "anode", "m^2", params.anode.separator.area_m2.value, 1e-8, 0.1, ...
    "platform_default", "anode_separator_area", "", "", "separator", ...
    "compile", "validated", "medium", ...
    "Active Flow Resistance (FC) flow area; it is not a separator vessel diameter.", "active");
add("device.anode.separatorLaminarFraction", ...
    "Anode separator laminar fraction", "anode", "-", ...
    params.anode.separator.laminar_fraction.value, 0, 1, ...
    "platform_default", "anode_separator_laminar_fraction", "", "", "separator", ...
    "compile", "validated", "medium", ...
    "Laminar-loss fraction of the active Flow Resistance (FC) block.", "active");
add("device.anode.separatorMdotNominal_kg_s", ...
    "Anode separator nominal mass flow", "anode", "kg/s", ...
    params.anode.separator.mdot_nominal_kg_s.value, eps, 1, ...
    "platform_default", "anode_separator_mdot_nominal", "", "", ...
    "separator", "compile", "validated", "medium", ...
    "Nominal flow capacity of the active anode separator resistance.", "active");
add("device.anode.separatorDpNominal_MPa", ...
    "Anode separator nominal pressure drop", "anode", "MPa", ...
    params.anode.separator.dp_nominal_MPa.value, 0, 0.1, ...
    "platform_default", "anode_separator_dp_nominal", "", "", ...
    "separator", "compile", "validated", "medium", ...
    "Nominal pressure loss of the active anode separator resistance.", "active");

% Advanced research-boundary and controller parameters.
add("environment.ambientTemperature_C", "Ambient temperature", ...
    "environment", "degC", params.environment.ambient_T_C.value, -50, 100, ...
    "platform_default", "env_T", "", "", "environment", "compile", ...
    "validated", "medium", "Ambient temperature used by active environment blocks.", "active");
add("environment.ambientPressure_MPa_abs", "Ambient pressure", ...
    "environment", "MPa(abs)", params.environment.ambient_p_MPa_abs.value, ...
    params.environment.ambient_p_MPa_abs.value, params.environment.ambient_p_MPa_abs.value, ...
    "platform_default", "env_p", "", "", "environment", ...
    "compile", "validated", "medium", ...
    "Fixed platform standard-atmosphere boundary; only ambient temperature is user-settable.", "active");
add("cathode.airController.Kp", "Air compressor PID Kp", "cathode", "-", ...
    params.controls.air_pid_Kp.value, eps, Inf, "platform_default", ...
    "routeA_air_pid_Kp", "", "", "air_controller", "compile", ...
    "validated", "medium", "Proportional gain of the active air compressor controller.", "active");
add("cathode.airController.Ki", "Air compressor PID Ki", "cathode", "1/s", ...
    params.controls.air_pid_Ki.value, eps, Inf, "platform_default", ...
    "routeA_air_pid_Ki", "", "", "air_controller", "compile", ...
    "validated", "medium", "Integral gain of the active air compressor controller.", "active");
add("cegr.directValveArea_m2", "Direct cEGR valve area", "cegr", "m^2", ...
    params.controls.cegr_direct_area_m2.value, 1e-12, 1, ...
    "platform_default", "routeA_egr_valve_area_direct", "", "", ...
    "cegr_direct", "compile", "validated", "medium", ...
    "Direct cEGR valve area, applied only in direct control mode.", "active");
add("cegr.directTargetRatio", "Direct cEGR compressor-inlet target ratio", ...
    "cegr", "-", params.controls.target_egr_ratio_comp_in.value, 0, 0.5, ...
    "platform_default", "routeA_target_egr_ratio_comp_in", "", "", ...
    "cegr_direct", "compile", "validated", "medium", ...
    "Direct-mode cEGR target ratio at compressor inlet.", "active");

% Thermal-management BOP groups. Height and fin spacing are source fields;
% their model-facing area/gap quantities are derived atomically at assembly.
add("device.thermal.coolantGeometry.channelWidth_cm", ...
    "Coolant channel width", "thermal", "cm", ...
    params.thermal.coolant.w_channels_cm.value, 0.2, 2, "platform_default", ...
    "coolant_w_channels", "", "", "coolant_channels", "compile", ...
    "validated", "medium", "Coolant channel width and hydraulic diameter.", "active");
add("device.thermal.coolantGeometry.numLayers", "Coolant channel layers", ...
    "thermal", "-", params.thermal.coolant.num_layers.value, 1, 100, ...
    "platform_default", "coolant_num_layers", "", "", "coolant_channels", ...
    "compile", "validated", "medium", "Number of coolant layers.", "active");
add("device.thermal.coolantGeometry.numPasses", "Coolant channel passes", ...
    "thermal", "-", params.thermal.coolant.num_passes.value, 1, 50, ...
    "platform_default", "coolant_num_passes", "", "", "coolant_channels", ...
    "compile", "validated", "medium", "Number of coolant passes per layer.", "active");
add("device.thermal.coolantGeometry.tubeDiameter_m", "Coolant tube diameter", ...
    "thermal", "m", params.thermal.coolant.tube_D_m.value, 0.01, 0.10, ...
    "platform_default", "coolant_tube_D", "", "", "coolant_loop", "compile", ...
    "validated", "medium", "Coolant-loop tube diameter used by pump and resistance.", "active");
add("device.thermal.radiatorCore.length_m", "Radiator core length", ...
    "thermal", "m", params.thermal.radiator.L_m.value, 0.2, 2, ...
    "platform_default", "radiator_L", "", "", "radiator_core", "compile", ...
    "validated", "medium", "Radiator tube flow length.", "active");
add("device.thermal.radiatorCore.width_m", "Radiator tube width", ...
    "thermal", "m", params.thermal.radiator.W_m.value, 0.005, 0.10, ...
    "platform_default", "radiator_W", "", "", "radiator_core", "compile", ...
    "validated", "medium", "Radiator tube width.", "active");
add("device.thermal.radiatorCore.height_m", "Radiator core height", ...
    "thermal", "m", params.thermal.radiator.H_m.value, 0.10, 1.0, ...
    "platform_default", "radiator_air_area_primary", "", "", "radiator_core", "compile", ...
    "validated", "medium", "Core height; derives tube gap and air areas.", "active");
add("device.thermal.radiatorCore.tubeCount", "Radiator tube count", ...
    "thermal", "-", params.thermal.radiator.N_tubes.value, 2, 100, ...
    "platform_default", "radiator_N_tubes", "", "", "radiator_core", "compile", ...
    "validated", "medium", "Number of coolant tubes in the radiator core.", "active");
add("device.thermal.radiatorCore.tubeHeight_m", "Radiator tube height", ...
    "thermal", "m", params.thermal.radiator.tube_H_m.value, 5e-4, 1e-2, ...
    "platform_default", "radiator_tube_H", "", "", "radiator_core", "compile", ...
    "validated", "medium", "Radiator tube height.", "active");
add("device.thermal.radiatorCore.finSpacing_m", "Radiator fin spacing", ...
    "thermal", "m", params.thermal.radiator.fin_spacing_m.value, 5e-4, 1e-2, ...
    "platform_default", "radiator_air_area_fins", "", "", "radiator_core", ...
    "compile", "validated", "medium", "Fin spacing; derives fin count and fin area.", "active");
add("device.thermal.radiatorCore.finEfficiency", "Radiator fin efficiency", ...
    "thermal", "-", params.thermal.radiator.eta_fin.value, 0.3, 1, ...
    "platform_default", "radiator_eta_fin", "", "", "radiator_core", "compile", ...
    "validated", "medium", "Effective fin efficiency in convective area.", "active");
add("device.thermal.radiatorCore.wallThickness_m", "Radiator wall thickness", ...
    "thermal", "m", params.thermal.radiator.t_wall_m.value, 1e-5, 1e-3, ...
    "platform_default", "radiator_t_wall", "", "", "radiator_core", "compile", ...
    "validated", "medium", "Radiator wall thickness used by thermal mass.", "active");
add("device.thermal.radiatorCore.density_kg_m3", "Radiator wall density", ...
    "thermal", "kg/m^3", params.thermal.radiator.rho_kg_m3.value, 500, 5000, ...
    "platform_default", "radiator_rho", "", "", "radiator_core", "compile", ...
    "validated", "medium", "Radiator wall density used by thermal mass.", "active");
add("device.thermal.radiatorCore.specificHeat_J_kgK", ...
    "Radiator wall specific heat", "thermal", "J/(kg*K)", ...
    params.thermal.radiator.cp_J_kgK.value, 300, 1500, "platform_default", ...
    "radiator_cp", "", "", "radiator_core", "compile", "validated", ...
    "medium", "Radiator wall specific heat used by thermal mass.", "active");

add("thermal.stackTemperatureSet_C", "Stack temperature setpoint", "thermal", ...
    "degC", params.thermal.stack_temperature_set_C.value, 60, 100, ...
    "platform_default", "routeA_stack_temperature_set_C", "", ...
    "stack_temperature_set_C", "runtime", "no", "validated", "medium", ...
    "Cooling-system stack temperature setpoint; the current model uses the same T_stack path as cathode humidifier TIn/RH temperature reference.", "active");

add("solver.stopTime_s", "Simulation stop time", "solver", "s", ...
    params.numerics.stopTime_s.value, 0, Inf, "platform_default", "", "", "", ...
    "study", "no", "validated", "low", "Simulation stop time.", "active");
add("solver.solver", "Variable-step solver", "solver", "-", ...
    params.numerics.solver.value, [], [], "platform_default", "", "", "", ...
    "study", "no", "validated", "medium", "Active variable-step solver name.", "active");
add("solver.relTol", "Relative tolerance", "solver", "-", ...
    params.numerics.relTol.value, eps, 1, "platform_default", "", "", "", ...
    "study", "no", "validated", "medium", "Variable-step solver relative tolerance.", "active");
add("solver.absTol", "Absolute tolerance", "solver", "-", ...
    params.numerics.absTol.value, eps, Inf, "platform_default", "", "", "", ...
    "study", "no", "validated", "medium", "Variable-step solver absolute tolerance.", "active");
add("solver.maxStep_s", "Maximum solver step", "solver", "s", ...
    params.numerics.maxStep_s.value, 0, Inf, "platform_default", "", "", "", ...
    "study", "no", "validated", "medium", "Maximum solver step size.", "active");

% Inventory every platform-default leaf that is not yet an active input.
entries = appendPlatformLeaves(entries, params, '');

registry = struct();
registry.schemaVersion = "RouteA_Parameter_Registry_v01";
registry.model = string(paths.modelName);
registry.sourceFunction = "routeA_platform_default_parameters";
registry.entries = entries;
registry.count = numel(entries);
registry.activeCount = sum(arrayfun(@(x) x.status == "active", entries));
registry.inventoryCount = sum(arrayfun(@(x) x.status == "inventory", entries));
registry.panelBasicCount = sum(arrayfun(@(x) x.panelExposure == "basic", entries));
registry.panelAdvancedCount = sum(arrayfun(@(x) x.panelExposure == "advanced", entries));
registry.generatedAt = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));

    function add(canonicalName, displayName, domain, unit, defaultValue, ...
            minimum, maximum, source, modelWorkspaceVariable, blockParameter, ...
            profileField, tunableClass, requiresCompile, validationLevel, ...
            riskLevel, description, status)
        entry = entryTemplate();
        entry.canonicalName = string(canonicalName);
        entry.displayName = string(displayName);
        entry.domain = string(domain);
        entry.unit = string(unit);
        entry.defaultValue = defaultValue;
        entry.minimum = minimum;
        entry.maximum = maximum;
        entry.source = string(source);
        entry.modelWorkspaceVariable = string(modelWorkspaceVariable);
        entry.blockParameter = string(blockParameter);
        entry.profileField = string(profileField);
        entry.tunableClass = string(tunableClass);
        entry.requiresCompile = string(requiresCompile);
        entry.validationLevel = string(validationLevel);
        entry.riskLevel = string(riskLevel);
        entry.description = string(description);
        entry.status = string(status);
        entry = applyPanelMetadata(entry);
        entries(end + 1) = entry;
    end
end

function entries = appendPlatformLeaves(entries, value, prefix)
if isstruct(value) && isscalar(value) && ...
        isfield(value, 'value') && isfield(value, 'unit') && ...
        isfield(value, 'source') && isfield(value, 'description')
    entry = entryTemplate();
    entry.canonicalName = "platform." + string(prefix);
    entry.displayName = entry.canonicalName;
    entry.domain = firstToken(prefix);
    entry.unit = string(value.unit);
    entry.defaultValue = value.value;
    entry.minimum = [];
    entry.maximum = [];
    entry.source = "routeA_platform_default_parameters." + string(prefix);
    entry.modelWorkspaceVariable = "";
    entry.blockParameter = "";
    entry.profileField = "";
    entry.tunableClass = "inventory";
    entry.requiresCompile = "unknown";
    entry.validationLevel = "inventory";
    entry.riskLevel = "unknown";
    entry.description = string(value.description);
    entry.status = "inventory";
    entry = applyPanelMetadata(entry);
    entries(end + 1) = entry;
    return;
end

if ~isstruct(value) || ~isscalar(value)
    return;
end
names = fieldnames(value);
for idx = 1:numel(names)
    field = names{idx};
    if isempty(prefix)
        childPrefix = field;
    else
        childPrefix = [prefix '.' field];
    end
    entries = appendPlatformLeaves(entries, value.(field), childPrefix);
end
end

function token = firstToken(value)
parts = split(string(value), '.');
token = parts(1);
end

function entry = applyPanelMetadata(entry)
% Keep panel exposure and application semantics in the same registry row.
if entry.status == "inventory"
    entry.panelExposure = "inventory";
    entry.applyAction = "read_only";
    entry.validationGate = "not_opened";
    entry.unsupportedReason = "Range, model mapping, compile behavior, or response is not closed.";
    return;
end
if entry.status == "unresolved"
    entry.panelExposure = "unresolved";
    entry.applyAction = "read_only";
    entry.validationGate = "not_opened";
    entry.unsupportedReason = "The model workspace item is not bound to an active block parameter in the current Route A model.";
    return;
end

if entry.canonicalName == "environment.ambientPressure_MPa_abs"
    entry.panelExposure = "read_only_catalog";
    entry.applyAction = "fixed_platform_default";
    entry.validationGate = "fixed_boundary";
    entry.unsupportedReason = ...
        "The active platform fixes ambient pressure at the standard-atmosphere default.";
    return;
end
if entry.canonicalName == "cegr.valveMode"
    entry.panelExposure = "read_only_catalog";
    entry.applyAction = "fixed_model_variant";
    entry.validationGate = "fixed_variant";
    entry.unsupportedReason = ...
        "The active model only implements the open-area cEGR valve variant.";
    return;
end

basicNames = [ ...
    "electrical.mode", "electrical.current.profile", ...
    "electrical.power.profile", "electrical.voltage.profile", ...
    "cathode.airControlMode", "cathode.targetOer", ...
    "cathode.targetMdot_kg_s", "cathode.directCommand", ...
    "cathode.outletPressure_MPa_abs", "cathode.humidifierRH", ...
    "cathode.humidifierEnabled", "cegr.enabled", "cegr.targetRatio", ...
    "solver.stopTime_s", "thermal.stackTemperatureSet_C"];
if any(entry.canonicalName == basicNames)
    entry.panelExposure = "basic";
elseif any(entry.canonicalName == [ ...
        "cegr.actuatorTau_s", "stack.numCells", "stack.area_cm2", ...
        "stack.iL_A_cm2", "stack.io_A_cm2"]) || ...
        startsWith(entry.canonicalName, "device.")
    entry.panelExposure = "device_settings";
else
    entry.panelExposure = "advanced";
end

if entry.requiresCompile == "compile"
    entry.applyAction = "compile_and_smoke";
    entry.validationGate = "compile_gate";
else
    entry.applyAction = "collect_and_validate";
    entry.validationGate = "case_validation";
end
entry.unsupportedReason = "";
end

function entry = entryTemplate()
entry = struct( ...
    'canonicalName', "", ...
    'displayName', "", ...
    'domain', "", ...
    'unit', "", ...
    'defaultValue', [], ...
    'minimum', [], ...
    'maximum', [], ...
    'source', "", ...
    'modelWorkspaceVariable', "", ...
    'blockParameter', "", ...
    'profileField', "", ...
    'tunableClass', "", ...
    'requiresCompile', "", ...
    'validationLevel', "", ...
    'riskLevel', "", ...
    'description', "", ...
    'status', "", ...
    'panelExposure', "", ...
    'applyAction', "", ...
    'validationGate', "", ...
    'unsupportedReason', "");
end
