function paths = routeA_project_paths(anchor)
% Return relocatable paths for the active Route A platform.
%
% The path graph is derived from this file location. It must not depend on
% the MATLAB current folder or on an agent-specific workspace.

if nargin < 1 || isempty(anchor)
    anchor = mfilename('fullpath');
end
anchor = char(anchor);

if isfolder(anchor)
    scriptDir = anchor;
else
    scriptDir = fileparts(anchor);
end

simulinkRoot = fullfile(scriptDir, '..', '..');
projectRoot = fullfile(simulinkRoot, '..');
modelDir = fullfile(simulinkRoot, '01_模型', 'RouteA_GasMixture_Derived');
modelName = 'PEMFuelCellSystem_GasMixture_cEGR_RouteA_v01';

paths = struct();
paths.schemaVersion = "RouteA_Project_Paths_v01";
paths.projectRoot = canonicalPath(projectRoot);
paths.simulinkRoot = canonicalPath(simulinkRoot);
paths.scriptDir = canonicalPath(scriptDir);
paths.modelDir = canonicalPath(modelDir);
paths.modelName = modelName;
paths.modelFile = fullfile(paths.modelDir, [modelName '.slx']);
paths.modelWorkspaceSource = fullfile(paths.modelDir, ...
    'PEMFuelCellSystemWithACustomLibraryParameters.m');
paths.modelWorkspaceData = fullfile(paths.modelDir, ...
    'PEMFuelCellSystemWithACustomLibraryParameters.mat');
paths.retiredHotStartRoot = fullfile(paths.projectRoot, '99_历史归档', ...
    '2026-07-29_RouteA_hot_start_retired');
paths.retiredHotStartBundle = fullfile(paths.retiredHotStartRoot, ...
    'RouteA_platform_default_initial_state.mat');
paths.resultRoot = fullfile(paths.simulinkRoot, '02_结果', ...
    'RouteA_GasMixture_Derived');
paths.panelResultRoot = fullfile(paths.resultRoot, 'outputs', 'RouteA_Panel');
paths.fuelCellLibraryName = 'FuelCell_lib';
paths.satkReuseLibrariesFile = fullfile(paths.projectRoot, '.satk', ...
    'reuse-libraries.json');

paths.requiredFiles = { ...
    fullfile(paths.scriptDir, 'routeA_project_paths.m'), ...
    fullfile(paths.scriptDir, 'routeA_check_dependencies.m'), ...
    fullfile(paths.scriptDir, 'routeA_model_contract.m'), ...
    fullfile(paths.scriptDir, 'routeA_parameter_registry.m'), ...
    fullfile(paths.scriptDir, 'routeA_observation_registry.m'), ...
    fullfile(paths.scriptDir, 'routeA_validate_observation_output.m'), ...
    fullfile(paths.scriptDir, 'launch_routeA_panel.m'), ...
    paths.modelFile, ...
    paths.modelWorkspaceSource, ...
    fullfile(paths.scriptDir, 'routeA_platform_default_parameters.m'), ...
    fullfile(paths.scriptDir, 'routeA_simCase_template.m'), ...
    fullfile(paths.scriptDir, 'routeA_validate_case.m'), ...
    fullfile(paths.scriptDir, 'routeA_command_profile_schema.m'), ...
    fullfile(paths.scriptDir, 'routeA_assemble_command_profile.m'), ...
    fullfile(paths.scriptDir, 'routeA_block_paths.m'), ...
    fullfile(paths.scriptDir, 'routeA_panel_build_simulation_input.m'), ...
    fullfile(paths.scriptDir, 'routeA_panel_extract_results.m'), ...
    fullfile(paths.scriptDir, 'routeA_p1_panel_capability_matrix.m'), ...
    fullfile(paths.scriptDir, 'routeA_panel_failure_result.m'), ...
    fullfile(paths.scriptDir, 'routeA_panel_export_result.m'), ...
    fullfile(paths.scriptDir, 'run_routeA_p1_panel_contract_tests.m'), ...
    fullfile(paths.scriptDir, 'run_routeA_p1_panel_acceptance.m'), ...
    fullfile(paths.scriptDir, 'run_routeA_p1_panel_single_case.m'), ...
    fullfile(paths.scriptDir, 'run_routeA_p0_acceptance.m'), ...
    fullfile(paths.scriptDir, 'RouteA_Panel_v01.m')};

paths.requiredFunctions = { ...
    'sim', ...
    'parsim', ...
    'Simulink.SimulationInput', ...
    'routeA_platform_default_parameters', ...
    'routeA_simCase_template', ...
    'routeA_validate_case', ...
    'routeA_command_profile_schema', ...
    'routeA_assemble_command_profile', ...
    'routeA_block_paths', ...
    'routeA_panel_build_simulation_input', ...
    'routeA_panel_extract_results', ...
    'routeA_p1_panel_capability_matrix', ...
    'routeA_panel_failure_result', ...
    'routeA_panel_export_result', ...
    'run_routeA_p1_panel_contract_tests', ...
    'run_routeA_p1_panel_acceptance', ...
    'run_routeA_p1_panel_single_case', ...
    'run_routeA_p0_acceptance', ...
    'routeA_project_paths', ...
    'routeA_check_dependencies', ...
    'routeA_model_contract', ...
    'routeA_parameter_registry', ...
    'routeA_observation_registry', ...
    'routeA_validate_observation_output'};
end

function value = canonicalPath(value)
% Keep the path absolute when the directory exists, including after a move.
[ok, attributes] = fileattrib(value);
if ok
    value = attributes.Name;
end
end
