%% Route A cEGR-PEMFC Panel Bootstrap Script
% This script creates the initial App Designer .mlapp file structure
% for the Route A simulation panel (Phase D, Step D1).
%
% Run this script, then open the generated .mlapp in App Designer
% to complete the UI layout manually.

% Create a new App Designer app programmatically
app = matlab.apps.AppBase;

% Define the main figure
app.UIFigure = uifigure('Name', 'Route A cEGR-PEMFC 仿真平台', ...
    'Position', [100, 100, 1200, 700], ...
    'Color', [0.94 0.94 0.94]);

% Status bar at bottom
app.StatusLabel = uilabel(app.UIFigure, ...
    'Position', [10, 10, 1180, 25], ...
    'Text', '状态: 就绪 | 模型: PEMFuelCellSystem_GasMixture_cEGR_RouteA_v01 | 参数源: platform_default', ...
    'FontSize', 11, ...
    'BackgroundColor', [0.9 0.9 0.9]);

% Main layout: left panel (parameters) + right panel (results)
app.LeftPanel = uipanel(app.UIFigure, ...
    'Title', '参数设置', ...
    'Position', [10, 50, 480, 620], ...
    'BackgroundColor', [0.94 0.94 0.94]);

app.RightPanel = uipanel(app.UIFigure, ...
    'Title', '结果展示', ...
    'Position', [500, 50, 690, 620], ...
    'BackgroundColor', [0.94 0.94 0.94]);

% Mode toggle (Basic/Advanced) at top-right of left panel
app.ModeButtonGroup = uibuttongroup(app.LeftPanel, ...
    'Position', [320, 580, 140, 30], ...
    'BorderType', 'none', ...
    'BackgroundColor', [0.94 0.94 0.94]);
app.BasicModeButton = uitogglebutton(app.ModeButtonGroup, ...
    'Text', '基础', ...
    'Position', [0, 0, 70, 30], ...
    'Value', true);
app.AdvancedModeButton = uitogglebutton(app.ModeButtonGroup, ...
    'Text', '高级', ...
    'Position', [70, 0, 70, 30]);

%% Left Panel - Parameter Input Area
yPos = 540;  % Start from top

% --- Electrical Boundary Panel ---
app.ElectricalPanel = uipanel(app.LeftPanel, ...
    'Title', '电边界', ...
    'Position', [10, yPos-100, 450, 100], ...
    'BackgroundColor', [1 1 1]);

app.BoundaryModeLabel = uilabel(app.ElectricalPanel, ...
    'Position', [10, 55, 80, 22], ...
    'Text', '模式:');
app.BoundaryModeDropDown = uidropdown(app.ElectricalPanel, ...
    'Position', [90, 55, 120, 22], ...
    'Items', {'Current', 'Power', 'Voltage'}, ...
    'Value', 'Current');

app.BoundaryCommandLabel = uilabel(app.ElectricalPanel, ...
    'Position', [220, 55, 80, 22], ...
    'Text', '命令值:');
app.BoundaryCommandEditField = uieditfield(app.ElectricalPanel, 'numeric', ...
    'Position', [300, 55, 80, 22], ...
    'Value', 100);
app.BoundaryUnitLabel = uilabel(app.ElectricalPanel, ...
    'Position', [385, 55, 40, 22], ...
    'Text', 'A');

app.RampDurationLabel = uilabel(app.ElectricalPanel, ...
    'Position', [10, 20, 80, 22], ...
    'Text', '斜坡时间:');
app.RampDurationEditField = uieditfield(app.ElectricalPanel, 'numeric', ...
    'Position', [90, 20, 80, 22], ...
    'Value', 60);
app.RampUnitLabel = uilabel(app.ElectricalPanel, ...
    'Position', [175, 20, 20, 22], ...
    'Text', 's');

yPos = yPos - 110;

% --- Air Path Panel ---
app.AirPathPanel = uipanel(app.LeftPanel, ...
    'Title', '气路', ...
    'Position', [10, yPos-110, 450, 110], ...
    'BackgroundColor', [1 1 1]);

app.OerLabel = uilabel(app.AirPathPanel, ...
    'Position', [10, 65, 100, 22], ...
    'Text', 'OER:');
app.OerEditField = uieditfield(app.AirPathPanel, 'numeric', ...
    'Position', [110, 65, 100, 22], ...
    'Value', 3.0);

app.BackpressureLabel = uilabel(app.AirPathPanel, ...
    'Position', [10, 35, 100, 22], ...
    'Text', '背压 (MPa):');
app.BackpressureEditField = uieditfield(app.AirPathPanel, 'numeric', ...
    'Position', [110, 35, 100, 22], ...
    'Value', 0.1613);

app.HumidifierRHLabel = uilabel(app.AirPathPanel, ...
    'Position', [10, 5, 100, 22], ...
    'Text', '加湿器 RH:');
app.HumidifierRHEditField = uieditfield(app.AirPathPanel, 'numeric', ...
    'Position', [110, 5, 100, 22], ...
    'Value', 0.9);

yPos = yPos - 120;

% --- cEGR Panel ---
app.CegrPanel = uipanel(app.LeftPanel, ...
    'Title', 'cEGR', ...
    'Position', [10, yPos-80, 450, 80], ...
    'BackgroundColor', [1 1 1]);

app.CegrRatioLabel = uilabel(app.CegrPanel, ...
    'Position', [10, 35, 100, 22], ...
    'Text', '目标比例:');
app.CegrRatioEditField = uieditfield(app.CegrPanel, 'numeric', ...
    'Position', [110, 35, 100, 22], ...
    'Value', 0);

app.CegrEnabledCheckBox = uicheckbox(app.CegrPanel, ...
    'Position', [10, 5, 100, 22], ...
    'Text', '启用 cEGR', ...
    'Value', false);

yPos = yPos - 90;

% --- Solver Panel ---
app.SolverPanel = uipanel(app.LeftPanel, ...
    'Title', '求解器', ...
    'Position', [10, yPos-60, 450, 60], ...
    'BackgroundColor', [1 1 1]);

app.StopTimeLabel = uilabel(app.SolverPanel, ...
    'Position', [10, 15, 100, 22], ...
    'Text', '仿真时长 (s):');
app.StopTimeEditField = uieditfield(app.SolverPanel, 'numeric', ...
    'Position', [110, 15, 100, 22], ...
    'Value', 600);

yPos = yPos - 70;

% --- Case ID ---
app.CaseIdLabel = uilabel(app.LeftPanel, ...
    'Position', [10, yPos-5, 100, 22], ...
    'Text', 'Case ID:');
app.CaseIdEditField = uieditfield(app.LeftPanel, 'text', ...
    'Position', [110, yPos-5, 200, 22], ...
    'Value', 'case1');

yPos = yPos - 40;

% --- Action Buttons ---
app.RunButton = uibutton(app.LeftPanel, 'push', ...
    'Position', [10, yPos-5, 150, 30], ...
    'Text', '运行单工况', ...
    'FontSize', 12, ...
    'FontWeight', 'bold', ...
    'BackgroundColor', [0.2 0.6 0.2], ...
    'FontColor', [1 1 1]);

app.MatrixButton = uibutton(app.LeftPanel, 'push', ...
    'Position', [170, yPos-5, 100, 30], ...
    'Text', '矩阵...', ...
    'FontSize', 12);

%% Right Panel - Results Display Area

% KPI Table at top
app.KpiTable = uitable(app.RightPanel, ...
    'Position', [10, 400, 670, 200], ...
    'ColumnName', {'caseId', 'V (V)', 'I (A)', 'P (kW)', 'OER', 'cEGR'}, ...
    'ColumnWidth', {100, 80, 80, 80, 60, 60}, ...
    'Data', {});

% Time-series plot in middle
app.TimeSeriesAxes = uiaxes(app.RightPanel, ...
    'Position', [10, 180, 670, 200]);
title(app.TimeSeriesAxes, '时序曲线');
xlabel(app.TimeSeriesAxes, '时间 (s)');
ylabel(app.TimeSeriesAxes, '电压 (V) / 电流 (A) / 功率 (kW)');
grid(app.TimeSeriesAxes, 'on');

% Log text area at bottom
app.LogLabel = uilabel(app.RightPanel, ...
    'Position', [10, 150, 100, 22], ...
    'Text', '运行日志:');
app.LogTextArea = uitextarea(app.RightPanel, ...
    'Position', [10, 10, 670, 130], ...
    'Value', {' > 面板已就绪，请设置参数并点击"运行单工况"'}, ...
    'Editable', 'off', ...
    'FontName', 'Consolas');

disp('Bootstrap structure created. Now save this as RouteA_Panel_v01.mlapp manually in App Designer.');
disp('Open App Designer, create a new blank app, then copy this structure.');
