function [simIn, context] = routeA_panel_build_simulation_input(simCase, rampDuration_s)
% Build a panel SimulationInput through the shared cold-start-only path.

if nargin < 2 || isempty(rampDuration_s)
    params = routeA_platform_default_parameters();
    rampDuration_s = min(params.numerics.startupRampDuration_s.value, ...
        0.1 * simCase.solver.stopTime_s);
end
validateattributes(rampDuration_s, {'numeric'}, ...
    {'scalar', 'real', 'nonnegative', 'finite'});
simCase = routeA_validate_case(simCase);
if lower(string(simCase.initialState.mode)) ~= "cold"
    error('RouteA:PanelColdStartOnly', ...
        'The active Route A panel supports cold-start-only execution.');
end
paths = routeA_project_paths();
model = char(paths.modelName);
if ~bdIsLoaded(model)
    load_system(paths.modelFile);
end
if rampDuration_s >= simCase.solver.stopTime_s
    error('RouteA:PanelRampDuration', ...
        'Ramp duration must be less than the simulation stop time.');
end

study = struct( ...
    'calculationType', calculationType(simCase.solver.stopTime_s), ...
    'researchDuration_s', simCase.solver.stopTime_s, ...
    'tailLogicalWindow_s', tailWindow(simCase.solver.stopTime_s), ...
    'steadyWindowDuration_s', min(60, max(simCase.solver.stopTime_s / 2, 1)), ...
    'steadyRelativeVariationLimit', 0.005, ...
    'engineeringSteadyRelativeVariationLimit', 0.01, ...
    'solver', string(simCase.solver.solver), ...
    'relativeTolerance', simCase.solver.relTol, ...
    'absoluteTolerance', simCase.solver.absTol, ...
    'studyMaxStep_s', simCase.solver.maxStep_s, ...
    'commandStartOffset_s', 0.5, ...
    'startupRampDuration_s', rampDuration_s);

caseCfg = panelCaseToRunnerCase(simCase);
[simIn, context] = routeA_prepare_electrical_boundary_input( ...
    model, paths.modelDir, caseCfg, study);
context.panelCase = simCase;
context.requestedCegrEnabled = logical(simCase.controls.cegr.enabled);
context.requestedCegrRatio = simCase.controls.cegr.targetRatio * ...
    double(context.requestedCegrEnabled);
context.panelAcceptance = panelAcceptance(simCase, study);
end

function caseCfg = panelCaseToRunnerCase(simCase)
caseCfg = struct();
caseCfg.caseId = string(simCase.caseId);
caseCfg.boundary = struct( ...
    'type', string(simCase.controls.electrical.mode), ...
    'profile', simCase.controls.electrical.profile);
caseCfg.cegr = struct( ...
    'profile', simCase.controls.cegr.targetRatio * ...
        double(logical(simCase.controls.cegr.enabled)), ...
    'enabled', logical(simCase.controls.cegr.enabled), ...
    'valveMode', simCase.controls.cegr.valveMode, ...
    'controlMode', simCase.controls.cegr.controlMode, ...
    'targetInputMode', simCase.controls.cegr.targetInputMode, ...
    'controller', simCase.controls.cegr.controller, ...
    'directValveArea_m2', simCase.controls.cegr.directValveArea_m2, ...
    'directTargetRatio', simCase.controls.cegr.directTargetRatio);
caseCfg.air = struct( ...
    'modeId', simCase.controls.cathode.airControlMode, ...
    'targetOer', simCase.controls.cathode.targetOer, ...
    'targetMdot_kg_s', simCase.controls.cathode.targetMdot_kg_s, ...
    'directCommand', simCase.controls.cathode.directCommand, ...
    'pid', simCase.controls.cathode.airController);
caseCfg.cathode = struct( ...
    'sourcePressure_MPa_abs', simCase.controls.cathode.sourcePressure_MPa_abs, ...
    'sourceTemperature_C', simCase.controls.cathode.sourceTemperature_C, ...
    'freshAirO2MoleFraction', simCase.controls.cathode.o2MoleFraction, ...
    'freshAirWaterMoleFraction', simCase.controls.cathode.h2oMoleFraction, ...
    'outletPressure_MPa_abs', simCase.controls.cathode.outletPressure_MPa_abs, ...
    'humidifierRelativeHumidity', simCase.controls.cathode.humidifierRH, ...
    'humidifierEnabled', simCase.controls.cathode.humidifierEnabled);
caseCfg.anode = struct( ...
    'tankPressure_MPa_abs', simCase.controls.anode.sourcePressure_MPa_abs, ...
    'sourceTemperature_C', simCase.controls.anode.sourceTemperature_C, ...
    'hydrogenMoleFraction', simCase.controls.anode.h2MoleFraction, ...
    'inletPressure_MPa_abs', simCase.controls.anode.inletPressure_MPa_abs, ...
    'humidifierRelativeHumidity', simCase.controls.anode.humidifierRH, ...
    'recirculationBaseCommand', simCase.controls.anode.recirculationBaseCommand, ...
    'recirculationCurrentGain_A_inv', simCase.controls.anode.recirculationCurrentGain_A_inv, ...
    'purgeEnabled', simCase.controls.anode.purgeEnabled, ...
    'purgeOnN2MoleFraction', simCase.controls.anode.purgeOnN2MoleFraction, ...
    'purgeOffN2MoleFraction', simCase.controls.anode.purgeOffN2MoleFraction);
caseCfg.thermal = struct('stackTemperatureSet_C', ...
    simCase.controls.thermal.stackTemperatureSet_C);
caseCfg.environment = simCase.controls.environment;
caseCfg.stack = simCase.controls.stack;
caseCfg.devices = simCase.controls.devices;
caseCfg.controller = simCase.controls.electrical.voltageController;
caseCfg.acceptance = struct();
end

function type = calculationType(stopTime_s)
if stopTime_s < 120
    type = "transient";
else
    type = "steady";
end
end

function window = tailWindow(stopTime_s)
window = [max(0, stopTime_s - min(60, stopTime_s / 2)), stopTime_s];
end

function acceptance = panelAcceptance(simCase, study)
acceptance = struct( ...
    'calculationType', string(study.calculationType), ...
    'tailLogicalWindow_s', study.tailLogicalWindow_s, ...
    'steadyWindowDuration_s', study.steadyWindowDuration_s, ...
    'steadyRelativeVariationLimit', study.steadyRelativeVariationLimit, ...
    'engineeringSteadyRelativeVariationLimit', ...
        study.engineeringSteadyRelativeVariationLimit, ...
    'liquidWaterInventoryClosed', false, ...
    'liquidWaterTransportClosed', false, ...
    'liquidDrainClosed', false, ...
    'separatorEfficiencyClosed', false, ...
    'fullWaterBalanceClosed', false, ...
    'liquidWaterStatus', "L2_not_closed", ...
    'liquidWaterConclusionAllowed', false, ...
    'caseDescription', string(simCase.description));
end
