function audit = routeA_stage1_water_ledger_from_outputs(caseOutputs, cfg)
% Audit WM-L1+ directly from already-completed mode-1 SimulationOutputs.
%
% caseOutputs must contain one struct per matrix case with targetRatio, out,
% initialState, and modeId fields. Multi-load callers additionally provide
% loadId, currentDensity_A_cm2, targetCurrentA, and
% targetAirEquivalentOer. This helper deliberately never calls sim.

requiredCfg = {'model', 'targetRatios', 'initialStateMetadata', ...
    'researchStartTime_s', 'researchDuration_s', 'modelStopTime_s', ...
    'tailLogicalWindow_s', 'tailWindow_s', 'targetAirEquivalentOer', ...
    'meaClosureTolerance_kg_s', 'localGasBalanceAbsTolerance_kg', ...
    'localGasBalanceRelativeTolerance', 'systemGasBalanceAbsTolerance_kg', ...
    'systemGasBalanceRelativeTolerance', 'species'};
if ~isstruct(cfg) || ~builtin('all', isfield(cfg, requiredCfg))
    error('RouteA:WaterLedgerConfig', ...
        'The shared-output water-ledger configuration is incomplete.');
end
cfg = normalizeLoadTrackingConfig(cfg);
requiredCaseFields = {'targetRatio', 'out', 'initialState', 'modeId'};
multiLoad = isfield(cfg, 'loadIds');
if multiLoad
    requiredCaseFields = [requiredCaseFields, {'loadId', ...
        'currentDensity_A_cm2', 'targetCurrentA', 'targetAirEquivalentOer'}];
end
if ~isstruct(caseOutputs) || ...
        ~builtin('all', isfield(caseOutputs, requiredCaseFields))
    error('RouteA:WaterLedgerCaseOutputs', ...
        'The shared-output water ledger received incomplete case outputs.');
end
if any([caseOutputs.modeId] ~= 1)
    error('RouteA:WaterLedgerModeMismatch', ...
        'WM-L1+ regression accepts only mode-1 shared-output cases.');
end

cases = [];
if multiLoad
    loadIds = string(cfg.loadIds);
    outputLoadIds = string({caseOutputs.loadId});
    for loadIdx = 1:numel(loadIds)
        loadId = loadIds(loadIdx);
        for ratioIdx = 1:numel(cfg.targetRatios)
            targetRatio = cfg.targetRatios(ratioIdx);
            matches = find(outputLoadIds == loadId & ...
                abs([caseOutputs.targetRatio] - targetRatio) < eps);
            if numel(matches) ~= 1
                error('RouteA:WaterLedgerMissingMultiLoadCase', ...
                    ['Expected exactly one shared SimulationOutput for load %s ', ...
                    'and target %.16g; found %d.'], ...
                    loadId, targetRatio, numel(matches));
            end
            source = caseOutputs(matches);
            result = collectSelectedCase(source, cfg, targetRatio);
            result.loadId = source.loadId;
            result.currentDensity_A_cm2 = source.currentDensity_A_cm2;
            result.targetCurrentA = source.targetCurrentA;
            result.targetAirEquivalentOer = source.targetAirEquivalentOer;
            if isempty(cases)
                cases = result;
            else
                cases(end + 1) = result; %#ok<AGROW>
            end
        end
    end
else
    for idx = 1:numel(cfg.targetRatios)
        targetRatio = cfg.targetRatios(idx);
        matches = find(abs([caseOutputs.targetRatio] - targetRatio) < eps);
        if numel(matches) ~= 1
            error('RouteA:WaterLedgerMissingCase', ...
                'Expected exactly one shared SimulationOutput for target %.16g.', ...
                targetRatio);
        end
        result = collectSelectedCase(caseOutputs(matches), cfg, targetRatio);
        if isempty(cases)
            cases = result;
        else
            cases(end + 1) = result; %#ok<AGROW>
        end
    end
end

audit = summarizeWaterAudit(cases, cfg);
displayWaterAudit(audit);
end

function result = collectSelectedCase(source, cfg, targetRatio)
if ~isa(source.out, 'Simulink.SimulationOutput')
    error('RouteA:WaterLedgerOutputType', ...
        'The shared water-ledger case output is not a SimulationOutput.');
end
caseCfg = cfg;
if isfield(source, 'targetCurrentA')
    caseCfg.targetCurrentA = source.targetCurrentA;
end
if isfield(source, 'targetAirEquivalentOer')
    caseCfg.targetAirEquivalentOer = source.targetAirEquivalentOer;
end
result = collectWaterCase(source.out, cfg.model, caseCfg, targetRatio);
result.initialState = source.initialState;
result.modeId = source.modeId;
end

function result = collectWaterCase(out, model, cfg, targetRatio)
logsout = out.logsout;
egrRatio = loggedTimeseries(logsout, 'routeA_egr_ratio_comp_in');
waterSepL2 = outputTimeseries(out, logsout, 'routeA_m_water_sep', ...
    'routeA_m_water_sep_ts');

simlog = out.get(get_param(model, 'SimscapeLogName'));
meaStack = routeA_simscape_log_mea(simlog);
stackCurrent = timeseries(meaStack.Icell.series.values('A'), ...
    meaStack.Icell.series.time);
stackVoltage = timeseries(meaStack.Vstack.series.values('V'), ...
    meaStack.Vstack.series.time);
stackPower = timeseries(meaStack.power_elec.series.values('kW'), ...
    meaStack.power_elec.series.time);
paths = routeA_block_paths(model);
mea = simscape.logging.findNode(simlog, ...
    [paths.stack '/Membrane Electrode Assembly']);
mixer = simscape.logging.findNode(simlog, ...
    [paths.oxygen '/CompressorInletMixer']);
outlet = simscape.logging.findNode(simlog, paths.outletChamber);
compressorVolume = simscape.logging.findNode(simlog, ...
    [paths.oxygen '/Compressor Volume']);
humidifierPipe = simscape.logging.findNode(simlog, ...
    [paths.cathodeHumidifier '/Pipe (FC)']);
cathodeGas = simscape.logging.findNode(simlog, ...
    [paths.cathodeGas '/Cathode']);
egrPipe = simscape.logging.findNode(simlog, paths.egrPipe);
exhaustPipe = simscape.logging.findNode(simlog, ...
    [paths.cathodeExhaustBlock '/Pipe (N Gas)1']);
egrSensor = simscape.logging.findNode(simlog, paths.egrMassFlowSensor);
exhaustSensor = simscape.logging.findNode(simlog, paths.exhaustMassFlowSensor);
preHumidifierSensor = simscape.logging.findNode(simlog, ...
    paths.oxygenMassFlowSensor);
humidifierGain = simscape.logging.findNode(simlog, ...
    [paths.cathodeHumidifier '/PS Gain1']);

meaWaterProduced = logSeries(mea, 'H2O_produced', 'kg/s', ...
    'MEA H2O_produced');
meaMdotCa = logSeries(mea, 'mdot_ca', 'kg/s', 'MEA mdot_ca');
meaMdotAn = logSeries(mea, 'mdot_an', 'kg/s', 'MEA mdot_an');
mixerPorts = struct( ...
    'A', logSeries(mixer, 'mdot_A_i', 'kg/s', 'CompressorInletMixer mdot_A_i'), ...
    'B', logSeries(mixer, 'mdot_B_i', 'kg/s', 'CompressorInletMixer mdot_B_i'), ...
    'C', logSeries(mixer, 'mdot_C_i', 'kg/s', 'CompressorInletMixer mdot_C_i'));
mixerCond = logSeries(mixer, 'mdot_cond', 'kg/s', ...
    'CompressorInletMixer mdot_cond');
mixerInventory = logSeries(mixer, 'm_I_i', 'kg', ...
    'CompressorInletMixer m_I_i');
compressorVolumeCond = logSeries(compressorVolume, 'mdot_cond', 'kg/s', ...
    'Compressor Volume mdot_cond');
compressorVolumeInventory = logSeries(compressorVolume, 'm_I_i', 'kg', ...
    'Compressor Volume m_I_i');
humidifierPipeInventory = logSeries(humidifierPipe, 'm_I_i', 'kg', ...
    'Cathode Humidifier Pipe m_I_i');
humidifierPipeCond = logSeries(humidifierPipe, 'mdot_c', 'kg/s', ...
    'Cathode Humidifier Pipe mdot_c');
cathodeGasCond = logSeries(cathodeGas, 'mdot_cond', 'kg/s', ...
    'Cathode Gas Channels mdot_cond');
cathodeGasInventory = logSeries(cathodeGas, 'm_I_i', 'kg', ...
    'Cathode Gas Channels m_I_i');
egrPipeInventory = logSeries(egrPipe, 'm_I_i', 'kg', 'EGR Pipe m_I_i');
egrPipeCond = logSeries(egrPipe, 'mdot_c', 'kg/s', 'EGR Pipe mdot_c');
exhaustPipeInventory = logSeries(exhaustPipe, 'm_I_i', 'kg', ...
    'Cathode Exhaust Pipe m_I_i');
exhaustPipeCond = logSeries(exhaustPipe, 'mdot_c', 'kg/s', ...
    'Cathode Exhaust Pipe mdot_c');
exhaustPipeOutSpecies = logSeries(exhaustPipe, 'mdot_B_i', 'kg/s', ...
    'Cathode Exhaust Pipe mdot_B_i');
outletPorts = struct( ...
    'A', logSeries(outlet, 'mdot_A_i', 'kg/s', 'CathodeOutletChamber mdot_A_i'), ...
    'B', logSeries(outlet, 'mdot_B_i', 'kg/s', 'CathodeOutletChamber mdot_B_i'), ...
    'C', logSeries(outlet, 'mdot_C_i', 'kg/s', 'CathodeOutletChamber mdot_C_i'));
outletCond = logSeries(outlet, 'mdot_cond', 'kg/s', ...
    'CathodeOutletChamber mdot_cond');
outletInventory = logSeries(outlet, 'm_I_i', 'kg', ...
    'CathodeOutletChamber m_I_i');
egrMdot = logSeries(egrSensor, 'M', 'kg/s', 'EGRMassFlowSensor M');
egrSpecies = logSeries(egrSensor, 'M_i', 'kg/s', 'EGRMassFlowSensor M_i');
exhaustMdot = logSeries(exhaustSensor, 'M', 'kg/s', ...
    'ExhaustMassFlowSensor M');
exhaustSpecies = logSeries(exhaustSensor, 'M_i', 'kg/s', ...
    'ExhaustMassFlowSensor M_i');
preHumidifierMdot = logSeries(preHumidifierSensor, 'M', 'kg/s', ...
    'Prehumidifier M');
preHumidifierSpecies = logSeries(preHumidifierSensor, 'M_i', 'kg/s', ...
    'Prehumidifier M_i');
humidifierMIn = logSeries(humidifierGain, 'O', 'kg/s', ...
    'Cathode humidifier MIn');

tail = struct();
tail.actualEgrRatio = scalarStats(egrRatio.Time, egrRatio.Data, ...
    cfg.tailWindow_s);
tail.stackCurrent_A = scalarStats(stackCurrent.Time, stackCurrent.Data, ...
    cfg.tailWindow_s);
tail.stackVoltage_V = scalarStats(stackVoltage.Time, stackVoltage.Data, ...
    cfg.tailWindow_s);
tail.stackPower_kW = scalarStats(stackPower.Time, stackPower.Data, ...
    cfg.tailWindow_s);
tail.meaH2OProduced_kg_s = scalarStats(meaWaterProduced.time, ...
    meaWaterProduced.data, cfg.tailWindow_s);
tail.meaMdotCaSpecies_kg_s = vectorStats(meaMdotCa.time, meaMdotCa.data, ...
    cfg.tailWindow_s);
tail.meaMdotAnSpecies_kg_s = vectorStats(meaMdotAn.time, meaMdotAn.data, ...
    cfg.tailWindow_s);
tail.mixerPortSpecies_kg_s = struct( ...
    'A', vectorStats(mixerPorts.A.time, mixerPorts.A.data, cfg.tailWindow_s), ...
    'B', vectorStats(mixerPorts.B.time, mixerPorts.B.data, cfg.tailWindow_s), ...
    'C', vectorStats(mixerPorts.C.time, mixerPorts.C.data, cfg.tailWindow_s));
tail.mixerCondSpecies_kg_s = vectorStats(mixerCond.time, mixerCond.data, ...
    cfg.tailWindow_s);
tail.mixerInventorySpecies_kg = vectorStats(mixerInventory.time, ...
    mixerInventory.data, cfg.tailWindow_s);
tail.mixerInventoryRateSpecies_kg_s = inventoryRate(mixerInventory.time, ...
    mixerInventory.data, cfg.tailWindow_s);
tail.outletPortSpecies_kg_s = struct( ...
    'A', vectorStats(outletPorts.A.time, outletPorts.A.data, cfg.tailWindow_s), ...
    'B', vectorStats(outletPorts.B.time, outletPorts.B.data, cfg.tailWindow_s), ...
    'C', vectorStats(outletPorts.C.time, outletPorts.C.data, cfg.tailWindow_s));
tail.outletCondSpecies_kg_s = vectorStats(outletCond.time, outletCond.data, ...
    cfg.tailWindow_s);
tail.outletInventorySpecies_kg = vectorStats(outletInventory.time, ...
    outletInventory.data, cfg.tailWindow_s);
tail.outletInventoryRateSpecies_kg_s = inventoryRate(outletInventory.time, ...
    outletInventory.data, cfg.tailWindow_s);
tail.humidifierPipeCondSpecies_kg_s = vectorStats(humidifierPipeCond.time, ...
    humidifierPipeCond.data, cfg.tailWindow_s);
tail.cathodeGasCondSpecies_kg_s = vectorStats(cathodeGasCond.time, ...
    cathodeGasCond.data, cfg.tailWindow_s);
tail.egrPipeCondSpecies_kg_s = vectorStats(egrPipeCond.time, ...
    egrPipeCond.data, cfg.tailWindow_s);
tail.exhaustPipeCondSpecies_kg_s = vectorStats(exhaustPipeCond.time, ...
    exhaustPipeCond.data, cfg.tailWindow_s);
tail.finalExhaustSpecies_kg_s = vectorStats(exhaustPipeOutSpecies.time, ...
    exhaustPipeOutSpecies.data, cfg.tailWindow_s);
tail.egrMdot_kg_s = scalarStats(egrMdot.time, egrMdot.data, cfg.tailWindow_s);
tail.egrSpecies_kg_s = vectorStats(egrSpecies.time, egrSpecies.data, ...
    cfg.tailWindow_s);
tail.exhaustMdot_kg_s = scalarStats(exhaustMdot.time, exhaustMdot.data, ...
    cfg.tailWindow_s);
tail.exhaustSpecies_kg_s = vectorStats(exhaustSpecies.time, ...
    exhaustSpecies.data, cfg.tailWindow_s);
tail.preHumidifierMdot_kg_s = scalarStats(preHumidifierMdot.time, ...
    preHumidifierMdot.data, cfg.tailWindow_s);
tail.preHumidifierSpecies_kg_s = vectorStats(preHumidifierSpecies.time, ...
    preHumidifierSpecies.data, cfg.tailWindow_s);
tail.humidifierMInSpecies_kg_s = vectorStats(humidifierMIn.time, ...
    humidifierMIn.data, cfg.tailWindow_s);
tail.waterSepL2Raw = l2ObserverStats(waterSepL2.Time, waterSepL2.Data, ...
    cfg.tailWindow_s);

h2o = cfg.species.h2o;
meaClosure = tail.meaH2OProduced_kg_s.mean - ...
    tail.meaMdotCaSpecies_kg_s.mean(h2o) - ...
    tail.meaMdotAnSpecies_kg_s.mean(h2o);
mixerGasPhaseBalance = localGasPhaseBalance(mixerPorts, mixerCond, ...
    mixerInventory, h2o, [cfg.researchStartTime_s, cfg.modelStopTime_s], ...
    cfg, 'CompressorInletMixer');
outletGasPhaseBalance = localGasPhaseBalance(outletPorts, outletCond, ...
    outletInventory, h2o, [cfg.researchStartTime_s, cfg.modelStopTime_s], ...
    cfg, 'CathodeOutletChamber');
systemGasPhaseBalance = cathodeSystemGasPhaseBalance( ...
    mixerPorts.A, humidifierMIn, meaMdotCa, exhaustPipeOutSpecies, ...
    [mixerCond, compressorVolumeCond, humidifierPipeCond, cathodeGasCond, ...
    outletCond, egrPipeCond, exhaustPipeCond], ...
    [mixerInventory, compressorVolumeInventory, humidifierPipeInventory, ...
    cathodeGasInventory, outletInventory, egrPipeInventory, ...
    exhaustPipeInventory], h2o, ...
    [cfg.researchStartTime_s, cfg.modelStopTime_s], cfg);
saturation = struct( ...
    'mixer', saturationRatioStats(mixer, cfg, 'CompressorInletMixer'), ...
    'compressorVolume', saturationRatioStats(compressorVolume, cfg, ...
        'Compressor Volume'), ...
    'humidifierPipe', saturationRatioStats(humidifierPipe, cfg, ...
        'Cathode Humidifier Pipe'), ...
    'cathodeGas', saturationRatioStats(cathodeGas, cfg, ...
        'Cathode Gas Channels'), ...
    'outletChamber', saturationRatioStats(outlet, cfg, ...
        'CathodeOutletChamber'), ...
    'egrPipe', saturationRatioStats(egrPipe, cfg, 'EGR Pipe'), ...
    'exhaustPipe', saturationRatioStats(exhaustPipe, cfg, ...
        'Cathode Exhaust Pipe'));
tracking = assessLoadTracking(stackCurrent, stackPower, stackVoltage, cfg);

result = struct();
result.targetRatio = targetRatio;
result.researchStartModelTime_s = cfg.researchStartTime_s;
result.researchDuration_s = cfg.researchDuration_s;
result.tailLogicalWindow_s = cfg.tailLogicalWindow_s;
result.tailModelWindow_s = cfg.tailWindow_s;
result.loadTrackingMode = tracking.mode;
result.loadTrackingWindow_s = tracking.window_s;
result.loadTrackingPassed = tracking.passed;
result.currentTrackingWindow_s = tracking.currentWindow_s;
result.powerTrackingWindow_s = tracking.powerWindow_s;
result.voltageTrackingWindow_s = tracking.voltageWindow_s;
result.tail = tail;
result.meaWaterClosure_kg_s = meaClosure;
result.meaWaterClosurePassed = abs(meaClosure) <= ...
    cfg.meaClosureTolerance_kg_s;
% In the official MEA element, mdot_an(H2O) equals -mdot_w.  Positive
% mdot_w denotes anode-to-cathode transport, so this signed quantity is
% positive for anode-to-cathode and negative for cathode-to-anode transfer.
result.netMembraneWaterAnodeToCathode_kg_s = ...
    -tail.meaMdotAnSpecies_kg_s.mean(h2o);
result.mixerGasPhaseBalance = mixerGasPhaseBalance;
result.outletGasPhaseBalance = outletGasPhaseBalance;
result.localGasPhaseBalancePassed = mixerGasPhaseBalance.passed && ...
    outletGasPhaseBalance.passed;
result.systemGasPhaseBalance = systemGasPhaseBalance;
result.systemGasPhaseBalancePassed = systemGasPhaseBalance.passed;
result.saturation = saturation;
result.currentTrackingMaxError_A = tracking.currentMaxError_A;
result.currentPassed = tracking.currentPassed;
result.powerTrackingMaxRelativeError = tracking.powerMaxRelativeError;
result.powerTrackingPassed = tracking.powerPassed;
result.finite = tailFinite(tail);
result.evidencePassed = result.finite && result.loadTrackingPassed && ...
    result.meaWaterClosurePassed && result.localGasPhaseBalancePassed && ...
    result.systemGasPhaseBalancePassed;
end

function cfg = normalizeLoadTrackingConfig(cfg)
if ~isfield(cfg, 'loadTrackingMode') || isempty(cfg.loadTrackingMode)
    cfg.loadTrackingMode = "constant_current";
end
mode = string(cfg.loadTrackingMode);
if ~isscalar(mode) || ~any(mode == ["constant_current", "constant_power", ...
        "constant_voltage"])
    error('RouteA:WaterLedgerLoadTrackingMode', ...
        ['loadTrackingMode must be constant_current, constant_power, ', ...
        'or constant_voltage.']);
end
cfg.loadTrackingMode = mode;

if mode == "constant_current"
    required = {'targetCurrentA', 'currentTrackingTolerance_A'};
    if ~builtin('all', isfield(cfg, required))
        error('RouteA:WaterLedgerCurrentTrackingConfig', ...
            'The constant-current tracking configuration is incomplete.');
    end
    validateattributes(cfg.targetCurrentA, {'numeric'}, ...
        {'scalar', 'finite'});
    validateattributes(cfg.currentTrackingTolerance_A, {'numeric'}, ...
        {'scalar', 'nonnegative', 'finite'});
    if ~isfield(cfg, 'currentTrackingWindow_s')
        cfg.currentTrackingWindow_s = [cfg.researchStartTime_s, ...
            cfg.modelStopTime_s];
    end
    validateTrackingWindow(cfg.currentTrackingWindow_s, ...
        cfg.researchStartTime_s, cfg.modelStopTime_s, 'currentTrackingWindow_s');
elseif mode == "constant_power"
    required = {'targetPower_kW', 'powerTrackingRelativeTolerance', ...
        'powerTrackingWindow_s'};
    if ~builtin('all', isfield(cfg, required))
        error('RouteA:WaterLedgerPowerTrackingConfig', ...
            'The constant-power tracking configuration is incomplete.');
    end
    validateattributes(cfg.targetPower_kW, {'numeric'}, ...
        {'scalar', 'positive', 'finite'});
    validateattributes(cfg.powerTrackingRelativeTolerance, {'numeric'}, ...
        {'scalar', 'nonnegative', 'finite'});
    validateTrackingWindow(cfg.powerTrackingWindow_s, ...
        cfg.researchStartTime_s, cfg.modelStopTime_s, 'powerTrackingWindow_s');
else
    required = {'targetVoltage_V', 'voltageTrackingRelativeTolerance', ...
        'voltageTrackingWindow_s'};
    if ~builtin('all', isfield(cfg, required))
        error('RouteA:WaterLedgerVoltageTrackingConfig', ...
            'The constant-voltage tracking configuration is incomplete.');
    end
    validateattributes(cfg.targetVoltage_V, {'numeric'}, ...
        {'scalar', 'positive', 'finite'});
    validateattributes(cfg.voltageTrackingRelativeTolerance, {'numeric'}, ...
        {'scalar', 'nonnegative', 'finite'});
    validateTrackingWindow(cfg.voltageTrackingWindow_s, ...
        cfg.researchStartTime_s, cfg.modelStopTime_s, 'voltageTrackingWindow_s');
end
end

function validateTrackingWindow(window, lowerBound, upperBound, name)
validateattributes(window, {'numeric'}, {'vector', 'numel', 2, 'finite'});
window = window(:).';
if window(1) < lowerBound || window(2) > upperBound || ...
        window(2) <= window(1)
    error('RouteA:WaterLedgerTrackingWindow', ...
        '%s must be increasing and within the research window.', name);
end
end

function tracking = assessLoadTracking(stackCurrent, stackPower, stackVoltage, cfg)
tracking = struct( ...
    'mode', cfg.loadTrackingMode, ...
    'window_s', NaN(1, 2), ...
    'currentWindow_s', NaN(1, 2), ...
    'powerWindow_s', NaN(1, 2), ...
    'voltageWindow_s', NaN(1, 2), ...
    'currentMaxError_A', NaN, ...
    'currentPassed', NaN, ...
    'powerMaxRelativeError', NaN, ...
    'powerPassed', NaN, ...
    'voltageMaxRelativeError', NaN, ...
    'voltageTailMeanRelativeError', NaN, ...
    'voltagePassed', NaN, ...
    'passed', false);
if cfg.loadTrackingMode == "constant_current"
    currentData = normalizeScalarData(stackCurrent.Time, stackCurrent.Data, ...
        'stack current');
    values = windowData(stackCurrent.Time, currentData, ...
        cfg.currentTrackingWindow_s);
    tracking.window_s = cfg.currentTrackingWindow_s;
    tracking.currentWindow_s = cfg.currentTrackingWindow_s;
    tracking.currentMaxError_A = max(abs(values - cfg.targetCurrentA));
    tracking.currentPassed = tracking.currentMaxError_A <= ...
        cfg.currentTrackingTolerance_A;
    tracking.passed = tracking.currentPassed;
elseif cfg.loadTrackingMode == "constant_power"
    powerData = normalizeScalarData(stackPower.Time, stackPower.Data, ...
        'stack power');
    values = windowData(stackPower.Time, powerData, ...
        cfg.powerTrackingWindow_s);
    tracking.window_s = cfg.powerTrackingWindow_s;
    tracking.powerWindow_s = cfg.powerTrackingWindow_s;
    tracking.powerMaxRelativeError = max(abs(values - cfg.targetPower_kW)) / ...
        max(abs(cfg.targetPower_kW), 1e-6);
    tracking.powerPassed = tracking.powerMaxRelativeError <= ...
        cfg.powerTrackingRelativeTolerance;
    tracking.passed = tracking.powerPassed;
else
    voltageData = normalizeScalarData(stackVoltage.Time, stackVoltage.Data, ...
        'stack voltage');
    values = windowData(stackVoltage.Time, voltageData, ...
        cfg.voltageTrackingWindow_s);
    tracking.window_s = cfg.voltageTrackingWindow_s;
    tracking.voltageWindow_s = cfg.voltageTrackingWindow_s;
    tracking.voltageMaxRelativeError = ...
        max(abs(values - cfg.targetVoltage_V)) / ...
        max(abs(cfg.targetVoltage_V), 1e-6);
    tracking.voltageTailMeanRelativeError = ...
        abs(mean(values) - cfg.targetVoltage_V) / ...
        max(abs(cfg.targetVoltage_V), 1e-6);
    tracking.voltagePassed = tracking.voltageTailMeanRelativeError <= ...
        cfg.voltageTrackingRelativeTolerance;
    tracking.passed = tracking.voltagePassed;
end
end

function audit = summarizeWaterAudit(cases, cfg)
audit = struct();
audit.timestamp = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));
audit.model = string(cfg.initialStateMetadata.model);
audit.initialState = cfg.initialStateMetadata;
audit.targetRatios = cfg.targetRatios;
if isfield(cases, 'loadId')
    audit.loadIds = unique(string({cases.loadId}), 'stable');
else
    audit.loadIds = string.empty(1, 0);
end
audit.researchDuration_s = cfg.researchDuration_s;
audit.tailLogicalWindow_s = cfg.tailLogicalWindow_s;
audit.scope = 'cathode-cEGR water side only';
audit.cases = cases;
audit.observability = observabilityMap();
audit.localGasPhaseClosurePassed = ...
    builtin('all', [cases.localGasPhaseBalancePassed]);
audit.systemGasPhaseClosurePassed = ...
    builtin('all', [cases.systemGasPhaseBalancePassed]);
audit.gasVaporAndPhaseFluxEvidencePassed = ...
    builtin('all', [cases.evidencePassed]);
audit.liquidWaterInventoryClosed = false;
audit.liquidWaterTransportClosed = false;
audit.liquidDrainClosed = false;
audit.separatorEfficiencyClosed = false;
audit.fullWaterBalanceClosed = false;
audit.liquidGapReason = [ ...
    "No explicit liquid-water port, liquid transport branch, drain flow, ", ...
    "or separator efficiency model is currently exposed by the cathode-cEGR ", ...
    "physical network. Enabled Constant Volume Chamber (FC) blocks remove ", ...
    "condensed species from the gas chamber immediately; m_I_i is the ", ...
    "remaining gas-species inventory, not a liquid-water inventory."];
audit.auditPassed = audit.gasVaporAndPhaseFluxEvidencePassed;
end

function observability = observabilityMap()
observability = struct( ...
    'externalAirWater', ...
        'direct: fresh-air branch at CompressorInletMixer port-A species flow', ...
    'cathodeHumidifierWaterInput', ...
        'direct gas-phase source: Pipe (FC) MIn water component; external liquid or vapor mechanism is L2', ...
    'reactionWater', ...
        'direct: MEA H2O_produced', ...
    'meaCathodeAndAnodeWaterFlux', ...
        'direct: MEA mdot_ca and mdot_an species flows', ...
    'membraneWaterPartition', ...
        'derived: -MEA mdot_an(H2O), positive for anode-to-cathode; drag and diffusion are not split', ...
    'cathodeInletAndOutletVapor', ...
        'direct: prehumidifier, EGR, and exhaust Mass Flow Rate Sensor M_i', ...
    'condensationFlux', ...
        'direct gas-phase sink: Chamber mdot_cond and Pipe mdot_c across all gas volumes', ...
    'chamberComponentInventory', ...
        'direct gas-species chamber inventory: m_I_i; condensed water is not stored', ...
    'cathodeSystemGasInventory', ...
        'derived direct: sum m_I_i across seven cathode-cEGR gas volumes', ...
    'saturationRatio', ...
        'derived direct: water partial pressure divided by saturation pressure at each gas volume', ...
    'liquidInventory', ...
        'unobservable: no explicit liquid state is exposed; condensation is immediately removed', ...
    'liquidTransportAndDrain', ...
        'unobservable: no liquid port or drain branch exists', ...
    'separatorObserver', ...
        'L2 only: saturation-excess KPI; not a physical separator mass flow', ...
    'separatorEfficiency', ...
        'unobservable: no component performance evidence');
end

function displayWaterAudit(audit)
fprintf('\nRoute A Stage 1 cathode-cEGR water capability audit\n');
fprintf('  initial phase: %s | t0=%.6f s | initial-state target I=%.6g A | tail=[%.0f,%.0f) s\n', ...
    audit.initialState.normalOperationPhase, ...
    audit.initialState.snapshotTimeS, ...
    audit.initialState.targetCurrentA, ...
    audit.tailLogicalWindow_s(1), audit.tailLogicalWindow_s(2));
for idx = 1:numel(audit.cases)
    value = audit.cases(idx);
    h2o = 4;
    if isfield(value, 'loadId')
        fprintf('\n  load=%s j=%.6g A/cm^2 I=%.6g A OER=%.6g ', ...
            string(value.loadId), value.currentDensity_A_cm2, ...
            value.targetCurrentA, value.targetAirEquivalentOer);
    else
        fprintf('\n  ');
    end
    fprintf('target=%.2f actual=%.9g evidencePassed=%d\n', ...
        value.targetRatio, value.tail.actualEgrRatio.mean, ...
        value.evidencePassed);
    fprintf(['    MEA H2O: produced=%.9g kg/s cathode=%.9g anode=%.9g ', ...
        'closure=%.3g kg/s net-membrane(AtoC)=%.9g kg/s\n'], ...
        value.tail.meaH2OProduced_kg_s.mean, ...
        value.tail.meaMdotCaSpecies_kg_s.mean(h2o), ...
        value.tail.meaMdotAnSpecies_kg_s.mean(h2o), ...
        value.meaWaterClosure_kg_s, ...
        value.netMembraneWaterAnodeToCathode_kg_s);
    fprintf(['    mixer H2O ports[A B C]=[%s] cond=%.9g kg/s ', ...
        'full-window gas residual=%.3g kg\n'], ...
        num2str([value.tail.mixerPortSpecies_kg_s.A.mean(h2o), ...
        value.tail.mixerPortSpecies_kg_s.B.mean(h2o), ...
        value.tail.mixerPortSpecies_kg_s.C.mean(h2o)], ' %.9g'), ...
        value.tail.mixerCondSpecies_kg_s.mean(h2o), ...
        value.mixerGasPhaseBalance.residual_kg);
    fprintf(['    outlet H2O ports[A B C]=[%s] cond=%.9g kg/s ', ...
        'full-window gas residual=%.3g kg\n'], ...
        num2str([value.tail.outletPortSpecies_kg_s.A.mean(h2o), ...
        value.tail.outletPortSpecies_kg_s.B.mean(h2o), ...
        value.tail.outletPortSpecies_kg_s.C.mean(h2o)], ' %.9g'), ...
        value.tail.outletCondSpecies_kg_s.mean(h2o), ...
        value.outletGasPhaseBalance.residual_kg);
    fprintf(['    branch H2O: egr=%.9g pre-exhaust=%.9g final-exhaust=%.9g ', ...
        'preHum=%.9g humidifier-gas-source=%.9g kg/s %s\n'], ...
        value.tail.egrSpecies_kg_s.mean(h2o), ...
        value.tail.exhaustSpecies_kg_s.mean(h2o), ...
        -value.tail.finalExhaustSpecies_kg_s.mean(h2o), ...
        value.tail.preHumidifierSpecies_kg_s.mean(h2o), ...
        value.tail.humidifierMInSpecies_kg_s.mean(h2o), ...
        l2ObserverText(value.tail.waterSepL2Raw));
    fprintf(['    tail condensation H2O: humidifier-pipe=%.9g cathode-gas=%.9g ', ...
        'EGR-pipe=%.9g exhaust-pipe=%.9g kg/s\n'], ...
        value.tail.humidifierPipeCondSpecies_kg_s.mean(h2o), ...
        value.tail.cathodeGasCondSpecies_kg_s.mean(h2o), ...
        value.tail.egrPipeCondSpecies_kg_s.mean(h2o), ...
        value.tail.exhaustPipeCondSpecies_kg_s.mean(h2o));
    fprintf(['    saturation ratio max-full/tail-mean: mixer=%.6g/%.6g ', ...
        'comp=%.6g/%.6g humid=%.6g/%.6g cathode=%.6g/%.6g ', ...
        'outlet=%.6g/%.6g egr=%.6g/%.6g exhaust=%.6g/%.6g\n'], ...
        value.saturation.mixer.fullMaximum, value.saturation.mixer.tailMean, ...
        value.saturation.compressorVolume.fullMaximum, ...
        value.saturation.compressorVolume.tailMean, ...
        value.saturation.humidifierPipe.fullMaximum, ...
        value.saturation.humidifierPipe.tailMean, ...
        value.saturation.cathodeGas.fullMaximum, ...
        value.saturation.cathodeGas.tailMean, ...
        value.saturation.outletChamber.fullMaximum, ...
        value.saturation.outletChamber.tailMean, ...
        value.saturation.egrPipe.fullMaximum, value.saturation.egrPipe.tailMean, ...
        value.saturation.exhaustPipe.fullMaximum, ...
        value.saturation.exhaustPipe.tailMean);
    fprintf(['    system H2O full-window: fresh=%.9g humidifier=%.9g ', ...
        'MEA=%.9g exhaust=%.9g cond=%.9g delta-gas=%.9g residual=%.3g kg\n'], ...
        value.systemGasPhaseBalance.integratedFreshAir_kg, ...
        value.systemGasPhaseBalance.integratedHumidifier_kg, ...
        value.systemGasPhaseBalance.integratedMeaCathode_kg, ...
        value.systemGasPhaseBalance.integratedExhaust_kg, ...
        value.systemGasPhaseBalance.integratedCondensation_kg, ...
        value.systemGasPhaseBalance.deltaGasInventory_kg, ...
        value.systemGasPhaseBalance.residual_kg);
end
fprintf('\n  gas-vapor and phase-flux evidence passed=%d\n', ...
    audit.gasVaporAndPhaseFluxEvidencePassed);
fprintf('  liquid inventory/transport/drain/efficiency closed=[%d %d %d %d]\n', ...
    audit.liquidWaterInventoryClosed, audit.liquidWaterTransportClosed, ...
    audit.liquidDrainClosed, audit.separatorEfficiencyClosed);
end

function signal = logSeries(node, propertyName, unit, label)
if ~isprop(node, propertyName)
    error('RouteA:WaterAuditMissingSimscapeQuantity', ...
        'The required Simscape quantity is unavailable: %s.', label);
end
series = node.(propertyName).series;
signal = struct();
signal.time = series.time;
signal.time = signal.time(:);
signal.data = normalizeSeriesData(series.values(unit), signal.time, label);
end

function data = normalizeSeriesData(data, time, label)
data = squeeze(data);
if isvector(data)
    data = data(:);
end
if size(data, 1) ~= numel(time)
    data = data.';
end
if size(data, 1) ~= numel(time)
    error('RouteA:WaterAuditSeriesShape', ...
        'Unexpected Simscape data shape for %s.', label);
end
end

function signal = loggedTimeseries(logsout, name)
element = logsout.get(name);
if isempty(element) || isempty(element.Values)
    error('RouteA:WaterAuditMissingLoggedSignal', ...
        'The required logged signal is unavailable: %s.', name);
end
signal = element.Values;
end

function signal = outputTimeseries(out, logsout, logName, outputName)
if datasetHasElement(logsout, logName)
    element = logsout.get(logName);
    if ~isempty(element) && ~isempty(element.Values)
        signal = element.Values;
        return;
    end
end
signal = out.get(outputName);
end

function present = datasetHasElement(dataset, name)
names = dataset.getElementNames;
present = any(strcmp(names, name));
end

function stats = scalarStats(time, data, window)
data = normalizeScalarData(time, data, 'scalar statistic');
values = windowData(time, data, window);
stats = struct();
stats.start_s = window(1);
stats.end_s = window(2);
stats.sampleCount = numel(values);
stats.nonfiniteCount = sum(~isfinite(values));
finiteValues = values(isfinite(values));
if isempty(finiteValues)
    stats.mean = NaN;
    stats.std = NaN;
    stats.span = Inf;
    stats.minimum = NaN;
    stats.maximum = NaN;
    return;
end
stats.mean = mean(finiteValues);
stats.std = std(finiteValues);
stats.span = max(finiteValues) - min(finiteValues);
stats.minimum = min(finiteValues);
stats.maximum = max(finiteValues);
end

function data = normalizeScalarData(time, data, label)
data = squeeze(data);
if ~isvector(data)
    error('RouteA:WaterAuditScalarSeriesShape', ...
        'Expected a scalar timeseries for %s.', label);
end
data = data(:);
if numel(data) ~= numel(time)
    error('RouteA:WaterAuditScalarSeriesTime', ...
        'The scalar timeseries time base is inconsistent for %s.', label);
end
end

function stats = l2ObserverStats(time, data, window)
data = squeeze(data);
if isvector(data)
    stats = scalarStats(time, data, window);
    stats.kind = "scalar";
    stats.componentCount = 1;
    return;
end
if size(data, 1) ~= numel(time)
    data = data.';
end
if size(data, 1) ~= numel(time)
    error('RouteA:WaterAuditL2ObserverSeriesTime', ...
        'The L2 observer time base is inconsistent.');
end
values = windowData(time, data, window);
stats = struct( ...
    'kind', "vector", ...
    'componentCount', size(values, 2), ...
    'componentMean', mean(values, 1), ...
    'mean', NaN, ...
    'std', NaN, ...
    'span', NaN, ...
    'minimum', NaN, ...
    'maximum', NaN, ...
    'sampleCount', size(values, 1), ...
    'nonfiniteCount', sum(~isfinite(values), 'all'));
end

function text = l2ObserverText(stats)
if stats.kind == "scalar"
    text = sprintf('L2observer=%.9g', stats.mean);
else
    text = sprintf('L2observer=%d-component', stats.componentCount);
end
end

function stats = vectorStats(time, data, window)
values = windowData(time, data, window);
stats = struct();
stats.start_s = window(1);
stats.end_s = window(2);
stats.sampleCount = size(values, 1);
stats.nonfiniteCount = sum(~isfinite(values), 1);
stats.mean = mean(values, 1);
stats.std = std(values, 0, 1);
stats.span = max(values, [], 1) - min(values, [], 1);
stats.minimum = min(values, [], 1);
stats.maximum = max(values, [], 1);
end

function rate = inventoryRate(time, data, window)
mask = time >= window(1) & time < window(2);
time = time(mask);
data = data(mask, :);
if numel(time) < 2 || time(end) <= time(1)
    rate = NaN(1, size(data, 2));
    return;
end
rate = (data(end, :) - data(1, :)) / (time(end) - time(1));
end

function balance = localGasPhaseBalance(ports, condensate, inventory, ...
    speciesIndex, window, cfg, label)
time = inventory.time;
mask = time >= window(1) & time <= window(2);
time = time(mask);
inventoryData = inventory.data(mask, speciesIndex);
balance = struct();
balance.label = label;
balance.window_s = window;
balance.sampleCount = numel(time);
if numel(time) < 2 || time(end) <= time(1)
    balance.integratedPortAndCondensation_kg = NaN;
    balance.deltaGasInventory_kg = NaN;
    balance.residual_kg = NaN;
    balance.tolerance_kg = NaN;
    balance.passed = false;
    return;
end

portA = resampleSpecies(ports.A, time, speciesIndex, label);
portB = resampleSpecies(ports.B, time, speciesIndex, label);
portC = resampleSpecies(ports.C, time, speciesIndex, label);
condRate = resampleSpecies(condensate, time, speciesIndex, label);
netGasRate = portA + portB + portC - condRate;
integratedNet = trapz(time, netGasRate);
deltaInventory = inventoryData(end) - inventoryData(1);
residual = integratedNet - deltaInventory;
throughput = trapz(time, abs(portA) + abs(portB) + abs(portC) + abs(condRate));
tolerance = cfg.localGasBalanceAbsTolerance_kg + ...
    cfg.localGasBalanceRelativeTolerance * max(throughput, 1e-12);
balance.integratedPortAndCondensation_kg = integratedNet;
balance.deltaGasInventory_kg = deltaInventory;
balance.residual_kg = residual;
balance.tolerance_kg = tolerance;
balance.passed = isfinite(residual) && abs(residual) <= tolerance;
end

function balance = cathodeSystemGasPhaseBalance(freshAir, humidifier, ...
    meaCathode, exhaustPortB, condensateSignals, inventorySignals, speciesIndex, ...
    window, cfg)
time = inventorySignals(1).time;
mask = time >= window(1) & time <= window(2);
time = time(mask);
balance = struct();
balance.window_s = window;
balance.sampleCount = numel(time);
if numel(time) < 2 || time(end) <= time(1)
    balance.integratedFreshAir_kg = NaN;
    balance.integratedHumidifier_kg = NaN;
    balance.integratedMeaCathode_kg = NaN;
    balance.integratedExhaust_kg = NaN;
    balance.integratedCondensation_kg = NaN;
    balance.deltaGasInventory_kg = NaN;
    balance.residual_kg = NaN;
    balance.tolerance_kg = NaN;
    balance.passed = false;
    return;
end

freshRate = resampleSpecies(freshAir, time, speciesIndex, 'fresh-air water');
humidifierRate = resampleSpecies(humidifier, time, speciesIndex, ...
    'humidifier water source');
meaRate = resampleSpecies(meaCathode, time, speciesIndex, ...
    'MEA cathode water source');
exhaustRate = -resampleSpecies(exhaustPortB, time, speciesIndex, ...
    'final exhaust water flow');
condensationRate = zeros(size(time));
for idx = 1:numel(condensateSignals)
    condensationRate = condensationRate + resampleSpecies( ...
        condensateSignals(idx), time, speciesIndex, 'condensation flow');
end
gasInventory = zeros(size(time));
for idx = 1:numel(inventorySignals)
    gasInventory = gasInventory + resampleSpecies( ...
        inventorySignals(idx), time, speciesIndex, 'gas water inventory');
end

integratedFreshAir = trapz(time, freshRate);
integratedHumidifier = trapz(time, humidifierRate);
integratedMeaCathode = trapz(time, meaRate);
integratedExhaust = trapz(time, exhaustRate);
integratedCondensation = trapz(time, condensationRate);
deltaGasInventory = gasInventory(end) - gasInventory(1);
integratedNet = integratedFreshAir + integratedHumidifier + ...
    integratedMeaCathode - integratedExhaust - integratedCondensation;
residual = integratedNet - deltaGasInventory;
throughput = trapz(time, abs(freshRate) + abs(humidifierRate) + ...
    abs(meaRate) + abs(exhaustRate) + abs(condensationRate));
tolerance = cfg.systemGasBalanceAbsTolerance_kg + ...
    cfg.systemGasBalanceRelativeTolerance * max(throughput, 1e-12);
balance.integratedFreshAir_kg = integratedFreshAir;
balance.integratedHumidifier_kg = integratedHumidifier;
balance.integratedMeaCathode_kg = integratedMeaCathode;
balance.integratedExhaust_kg = integratedExhaust;
balance.integratedCondensation_kg = integratedCondensation;
balance.deltaGasInventory_kg = deltaGasInventory;
balance.integratedNet_kg = integratedNet;
balance.residual_kg = residual;
balance.tolerance_kg = tolerance;
balance.passed = isfinite(residual) && abs(residual) <= tolerance;
end

function stats = saturationRatioStats(node, cfg, label)
pressure = logSeries(node, 'p_I', 'Pa', [label ' p_I']);
temperature = logSeries(node, 'T_I', 'K', [label ' T_I']);
moleFraction = logSeries(node, 'y_I_i', '1', [label ' y_I_i']);
time = pressure.time;
p = resampleSpecies(pressure, time, 1, label);
T = resampleSpecies(temperature, time, 1, label);
yH2O = resampleSpecies(moleFraction, time, cfg.species.h2o, label);
temperatureC = T - 273.15;
pSatPa = 611.21 .* exp((18.678 - temperatureC ./ 234.5) .* ...
    (temperatureC ./ (257.14 + temperatureC)));
ratio = yH2O .* p ./ pSatPa;
fullMask = time >= cfg.researchStartTime_s & time <= cfg.modelStopTime_s;
tailMask = time >= cfg.tailWindow_s(1) & time < cfg.tailWindow_s(2);
if ~any(fullMask) || ~any(tailMask) || any(~isfinite(ratio))
    error('RouteA:WaterAuditSaturation', ...
        'Could not evaluate water saturation ratio for %s.', label);
end
stats = struct();
stats.fullMaximum = max(ratio(fullMask));
stats.tailMaximum = max(ratio(tailMask));
stats.tailMean = mean(ratio(tailMask));
stats.tailMinimum = min(ratio(tailMask));
end

function values = resampleSpecies(signal, targetTime, speciesIndex, label)
if size(signal.data, 2) < speciesIndex
    error('RouteA:WaterAuditMissingSpecies', ...
        'Water species is unavailable in %s.', label);
end
sourceTime = signal.time;
sourceData = signal.data(:, speciesIndex);
if numel(sourceTime) == numel(targetTime) && isequal(sourceTime, targetTime)
    values = sourceData;
    return;
end
values = interp1(sourceTime, sourceData, targetTime, 'linear');
if any(~isfinite(values))
    error('RouteA:WaterAuditResample', ...
        'Could not align the water flow time base for %s.', label);
end
end

function values = windowData(time, data, window)
mask = time >= window(1) & time < window(2);
values = data(mask, :);
if isempty(values)
    error('RouteA:WaterAuditEmptyWindow', ...
        'No samples were found in the requested statistics window.');
end
end

function passed = tailFinite(tail)
h2o = 4;
checks = [ ...
    tail.actualEgrRatio.nonfiniteCount == 0; ...
    tail.stackCurrent_A.nonfiniteCount == 0; ...
    tail.meaH2OProduced_kg_s.nonfiniteCount == 0; ...
    tail.meaMdotCaSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.meaMdotAnSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.mixerCondSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.outletCondSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.humidifierPipeCondSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.cathodeGasCondSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.egrPipeCondSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.exhaustPipeCondSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.finalExhaustSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.egrSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.exhaustSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.preHumidifierSpecies_kg_s.nonfiniteCount(h2o) == 0; ...
    tail.humidifierMInSpecies_kg_s.nonfiniteCount(h2o) == 0];
passed = builtin('all', checks);
end
