% Route A platform demo compatibility wrapper.
%
% This entry keeps the historical routeA_platform_demo_summary base
% variable, while all case assembly, SimulationInput creation, simulation,
% signal collection, and KPI assessment remain in the shared runner.

scriptDir = fileparts(mfilename('fullpath'));
addpath(scriptDir);
cfg = demoConfig();
caseSpec = struct( ...
    'caseId', cfg.caseId, ...
    'profile', [0, 0; 5, cfg.targetPowerKW; ...
        cfg.stopTime, cfg.targetPowerKW], ...
    'targetRatio', cfg.targetEgrRatio, ...
    'air', struct( ...
        'modeId', cfg.airMode, ...
        'targetMdot_kg_s', cfg.targetMdot, ...
        'targetOer', cfg.targetOer, ...
        'directCommand', cfg.directCompressorCmd), ...
    'cathode', struct( ...
        'outletPressure_MPa_abs', cfg.targetPCaOutMPa, ...
        'humidifierRelativeHumidity', cfg.humidifierGain, ...
        'humidifierEnabled', cfg.humidifierGain), ...
    'acceptance', struct('cegrRatioTolerance', 0.01), ...
    'thermal', struct( ...
        'stackTemperatureSet_C', cfg.stackTemperatureSetC));
cases = routeA_build_electrical_boundary_cases("Power", caseSpec);
studyCfg = struct( ...
    'calculationType', "transient", ...
    'researchDuration_s', cfg.stopTime, ...
    'tailLogicalWindow_s', [5, cfg.stopTime], ...
    'commandStartOffset_s', 0, ...
    'startupRampDuration_s', 0, ...
    'studyMaxStep_s', 0.1, ...
    'runWaterLedger', false, ...
    'executionMode', "serial", ...
    'parallelWorkers', 1, ...
    'showProgress', true, ...
    'retainSimulationOutputs', true, ...
    'resultFile', "", ...
    'cases', cases);

fprintf('\nRoute A platform demo compatibility wrapper\n');
study = run_routeA_electrical_boundary_study(studyCfg);
summary = legacySummary(study, cfg);
assignin('base', 'routeA_platform_demo_summary', summary);
displaySummary(summary);

function cfg = demoConfig()
cfg = struct( ...
    'caseId', "nominal_50p96kW_platform_demo", ...
    'stopTime', 10, ...
    'targetPowerKW', 50.96, ...
    'airMode', 1, ...
    'targetMdot', 0.045, ...
    'targetOer', 2.5, ...
    'directCompressorCmd', 0.5, ...
    'targetEgrRatio', 0.02, ...
    'targetPCaOutMPa', 0.101325 + 0.06, ...
    'humidifierGain', 1, ...
    'stackTemperatureSetC', 80);
end

function summary = legacySummary(study, cfg)
summary = emptySummary(cfg);
if ~isfield(study, 'cases') || isempty(study.cases)
    summary.errorId = "RouteA:DemoNoCase";
    summary.errorMessage = "The shared runner returned no demo case.";
    return;
end
result = study.cases(1);
summary.simCompleted = isfield(result, 'simCompleted') && ...
    logical(result.simCompleted);
summary.targetPowerKW = valueOrFallback(result, ...
    'targetPower_kW', cfg.targetPowerKW);
summary.targetEgrRatio = valueOrFallback(result, ...
    'targetRatio', cfg.targetEgrRatio);
summary.actualPowerKW = tailMean(result, 'stackPower_kW');
summary.compressorCmd = tailMean(result, 'compressorCommand');
summary.compressorRpmCmd = tailMean(result, 'compressorRpm');
summary.compInletMdotKgS = tailMean(result, 'compressorMdot_kg_s');
summary.egrRatioCompIn = tailMean(result, 'egrRatio');
summary.egrValveAreaCmd = tailMean(result, 'egrValveArea_m2');
summary.pCaOutMPa = tailMean(result, 'cathodeOutletPressure_MPa');
summary.RHCaIn = tailMean(result, 'rhCaIn');
summary.RHCaOut = tailMean(result, 'rhCaOut');
summary.mWaterSep = tailMean(result, 'waterSeparator');
summary.kpiFiniteOk = all(isfinite([summary.actualPowerKW, ...
    summary.compressorCmd, summary.compressorRpmCmd, ...
    summary.compInletMdotKgS, summary.egrRatioCompIn, ...
    summary.egrValveAreaCmd, summary.pCaOutMPa, ...
    summary.RHCaIn, summary.RHCaOut, summary.mWaterSep]));
summary.runnerPassed = isfield(study, 'passed') && logical(study.passed);
summary.passed = summary.simCompleted && summary.kpiFiniteOk;
if isfield(result, 'errorId')
    summary.errorId = string(result.errorId);
end
if isfield(result, 'errorMessage')
    summary.errorMessage = string(result.errorMessage);
end
end

function summary = emptySummary(cfg)
summary = struct( ...
    'caseId', cfg.caseId, 'passed', false, 'runnerPassed', false, ...
    'simCompleted', false, ...
    'errorId', "", 'errorMessage', "", 'stopTime', cfg.stopTime, ...
    'targetPowerKW', cfg.targetPowerKW, ...
    'targetMdotKgS', cfg.targetMdot, 'targetOer', cfg.targetOer, ...
    'targetEgrRatio', cfg.targetEgrRatio, ...
    'targetPCaOutMPa', cfg.targetPCaOutMPa, ...
    'actualPowerKW', NaN, 'compressorCmd', NaN, ...
    'compressorRpmCmd', NaN, 'compInletMdotKgS', NaN, ...
    'egrRatioCompIn', NaN, 'egrValveAreaCmd', NaN, ...
    'pCaOutMPa', NaN, 'RHCaIn', NaN, 'RHCaOut', NaN, ...
    'mWaterSep', NaN, 'kpiFiniteOk', false);
end

function value = valueOrFallback(result, fieldName, fallback)
value = fallback;
if isfield(result, fieldName) && isscalar(result.(fieldName)) && ...
        isfinite(result.(fieldName))
    value = result.(fieldName);
end
end

function value = tailMean(result, fieldName)
value = NaN;
if ~isfield(result, 'tail') || ~isfield(result.tail, fieldName)
    return;
end
stats = result.tail.(fieldName);
if isstruct(stats) && isfield(stats, 'mean')
    value = stats.mean;
end
end

function displaySummary(summary)
fprintf('\nRoute A platform demo result\n');
fprintf('  passed=%d runnerPassed=%d simCompleted=%d finite=%d\n', ...
    summary.passed, summary.runnerPassed, summary.simCompleted, ...
    summary.kpiFiniteOk);
if summary.passed
    fprintf('  P=%.4g kW cmd=%.4g rpm=%.4g mdot=%.4g kg/s\n', ...
        summary.actualPowerKW, summary.compressorCmd, ...
        summary.compressorRpmCmd, summary.compInletMdotKgS);
    fprintf(['  egr=%.4g area=%.4g pCaOut=%.4g MPa RHin=%.4g ', ...
        'RHout=%.4g water=%.4g\n'], ...
        summary.egrRatioCompIn, summary.egrValveAreaCmd, ...
        summary.pCaOutMPa, summary.RHCaIn, summary.RHCaOut, ...
        summary.mWaterSep);
else
    fprintf('  error=%s %s\n', summary.errorId, summary.errorMessage);
end
end
