function report = run_routeA_p1_panel_contract_tests()
% Optional P1 development wiring smoke; no simulation and no completion gate.

base = routeA_simCase_template();
base.caseId = "p1_contract_valid";
base.controls.electrical.profile = 100;
matrix = routeA_p1_panel_capability_matrix();
registry = routeA_observation_registry();
expectedResultCount = sum(arrayfun(@(entry) entry.panelExposure == "result", ...
    registry.entries));
expectedStatusOnlyCount = sum(arrayfun(@(entry) entry.panelExposure == "status_only", ...
    registry.entries));
assert(matrix.counts.resultObservationCount == expectedResultCount, ...
    'Result observation count is inconsistent with the observation registry.');
assert(matrix.counts.statusOnlyObservationCount == expectedStatusOnlyCount, ...
    'Status-only observation count is inconsistent with the observation registry.');
assert(all(arrayfun(@(entry) strlength(entry.uiProperty) > 0, ...
    matrix.parameters)), 'An active parameter has no UI mapping.');
assert(all(arrayfun(@(entry) strlength(entry.simCasePath) > 0, ...
    matrix.parameters)), 'An active parameter has no simCase path.');
assert(all(arrayfun(@(entry) strlength(entry.writePath) > 0, ...
    matrix.parameters)), 'An active parameter has no write point.');
registry = routeA_parameter_registry();
parameterAudit = routeA_audit_parameter_inventory(false);
assert(parameterAudit.counts.panelWriteTargetMismatchCount == 0, ...
    'An active panel parameter writes to a target not referenced by the model.');
deviceNames = ["cegr.actuatorTau_s", "stack.numCells", "stack.area_cm2", ...
    "stack.iL_A_cm2", "stack.io_A_cm2", ...
    "device.stack.alpha", "device.stack.meaCp_J_kgK", ...
    "device.stack.meaRho_kg_m3", "device.stack.gdlThickness_um", ...
    "device.stack.membraneThickness_um", ...
    "device.cathode.intercoolerMdotNominal_kg_s", ...
    "device.cathode.intercoolerDpNominal_MPa", ...
    "device.cathode.intercoolerArea_m2", ...
    "device.cathode.intercoolerLaminarFraction", ...
    "device.cathode.separatorMdotNominal_kg_s", ...
    "device.cathode.separatorDpNominal_MPa", ...
    "device.cathode.separatorArea_m2", ...
    "device.cathode.separatorLaminarFraction", ...
    "device.cathode.mixerVolume_L", ...
    "device.cathode.outletChamberVolume_L", ...
    "device.cathode.compressorMap.rpm_TLU", ...
    "device.cathode.compressorMap.p_ratio_TLU", ...
    "device.cathode.compressorMap.mdot_corr_TLU", ...
    "device.cegr.valveMaxArea_m2", ...
    "device.cegr.pipeLength_m", "device.cegr.pipeDiameter_m", ...
    "device.cegr.pipeRoughness_m", "device.cegr.condensationTau_s", ...
    "device.cegr.inletMixerPressure_MPa_abs", ...
    "device.cegr.outletChamberPressure_MPa_abs", ...
    "device.cegr.pipeExtraLength_m", "device.cegr.pipePressure_MPa_abs", ...
    "device.cegr.valveOpenMinArea_m2", "device.anode.tankPressure_MPa", ...
    "device.anode.tankVolume_L", "device.anode.tankTemperature_C"];
deviceNames = [deviceNames, "device.anode.separatorArea_m2", ...
    "device.anode.separatorLaminarFraction", ...
    "device.anode.separatorMdotNominal_kg_s", ...
    "device.anode.separatorDpNominal_MPa"];
deviceMask = ismember(string({registry.entries.canonicalName}), deviceNames);
deviceEntries = registry.entries(deviceMask);
assert(numel(deviceEntries) == numel(deviceNames), ...
    'Expected first-stage active device-settings entries.');
assert(all(string({deviceEntries.panelExposure}) == "device_settings"), ...
    'Every editable device parameter must belong to the device-settings page.');

names = { ...
    'airControlMode', 'targetOer', 'targetMdot_kg_s', 'directCommand', ...
    'sourcePressure_MPa_abs', 'sourceTemperature_C', 'humidifierRH', ...
    'o2MoleFraction', 'h2oMoleFraction', 'outletPressure_MPa_abs', ...
    'cegrRatio', 'valveMode', 'controlMode', 'targetInputMode', ...
    'stackTemperatureSet_C', 'stopTime_s', 'solver', 'relTol', ...
    'absTol', 'maxStep_s', 'voltageController'};
values = { ...
    4, 1, 0, -0.1, 0.05, 5, 1.1, 0.1, 0.001, 0.05, ...
    0.6, 3, 3, 2, 120, 0, 'ode1', 0, 0, -1, 'bad'};
tests = repmat(struct('name', "", 'passed', false, 'errorId', "", ...
    'message', ""), numel(names), 1);
for idx = 1:numel(names)
    candidate = setValue(base, names{idx}, values{idx});
    tests(idx).name = string(names{idx});
    try
        routeA_validate_case(candidate);
        error('RouteA:P1ContractTestNotRejected', ...
            'Invalid input %s was not rejected.', names{idx});
    catch ME
        tests(idx).passed = ~strcmp(ME.identifier, ...
            'RouteA:P1ContractTestNotRejected');
        tests(idx).errorId = string(ME.identifier);
        tests(idx).message = string(ME.message);
        assert(tests(idx).passed, '%s', ME.message);
    end
end

valid = base;
valid.controls.cegr.enabled = false;
valid.controls.cegr.targetRatio = 0.3;
valid = routeA_validate_case(valid);
assert(valid.controls.cegr.targetRatio == 0, ...
    'Disabled cEGR must normalize targetRatio to zero.');
fixedPressure_MPa_abs = ...
    routeA_platform_default_parameters().environment.ambient_p_MPa_abs.value;
fixedPressureCase = valid;
fixedPressureCase.controls.environment.ambientPressure_MPa_abs = 0.095;
assertRejectedFixedAmbientPressure(fixedPressureCase);

unsupportedValveCase = valid;
unsupportedValveCase.controls.cegr.valveMode = 2;
assertRejectedCegrValveMode(unsupportedValveCase);

rampRejected = false;
try
    routeA_panel_build_simulation_input(valid, valid.solver.stopTime_s);
catch ME
    rampRejected = strcmp(ME.identifier, 'RouteA:PanelRampDuration') || ...
        contains(string(ME.identifier), "RampDuration");
end
assert(rampRejected, 'Ramp duration equal to stop time was not rejected.');

[~, context] = routeA_panel_build_simulation_input(valid, ...
    min(60, 0.1 * valid.solver.stopTime_s));
assert(~context.requestedCegrEnabled && context.requestedCegrRatio == 0, ...
    'Disabled cEGR was not propagated through the panel builder.');
assert(~context.cegrControls.enabled && context.cegrControls.valveMode == ...
    valid.controls.cegr.valveMode, ...
    'cEGR compile-time controls were not propagated through the builder.');
[defaultRampInput, defaultRampContext] = ...
    routeA_panel_build_simulation_input(valid);
assert(defaultRampContext.startupRampDuration_s == ...
    min(routeA_platform_default_parameters().numerics.startupRampDuration_s.value, ...
    0.1 * valid.solver.stopTime_s) && ~isempty(defaultRampInput.Variables), ...
    'The panel builder did not supply its default cold-start ramp duration.');

badSeparatorCase = valid;
badSeparatorCase.controls.devices.cathode.separatorArea_m2 = 0;
assertRejectedDeviceValue(badSeparatorCase, 'controls.devices.cathode.separatorArea_m2');
badSeparatorCase = valid;
badSeparatorCase.controls.devices.anode.separatorLaminarFraction = 1.1;
assertRejectedDeviceValue(badSeparatorCase, ...
    'controls.devices.anode.separatorLaminarFraction');

% Compressor map is one atomic device dataset. Confirm normalisation,
% dimension/order rejection, and the runner context hand-off.
mapCase = valid;
mapCase.controls.devices.cathode.compressorMap.rpm_TLU = [0, 2000, 4000];
mapCase.controls.devices.cathode.compressorMap.p_ratio_TLU = [1; 1.4; 1.8; 2.2];
mapCase.controls.devices.cathode.compressorMap.mdot_corr_TLU = ...
    [0, 0.22, 0.44; 0, 0.16, 0.32; 0, 0.09, 0.18; 0, 0.02, 0.04];
[~, mapContext] = routeA_panel_build_simulation_input(mapCase, ...
    min(60, 0.1 * mapCase.solver.stopTime_s));
assert(isequal(mapContext.devices.cathode.compressorMap.rpm_TLU, [0, 2000, 4000]) && ...
    isequal(size(mapContext.devices.cathode.compressorMap.mdot_corr_TLU), [4, 3]), ...
    'Validated compressor map did not reach the shared SimulationInput builder.');
geometryCase = valid;
geometryCase.controls.devices.cegr.pipeDiameter_m = 0.06;
[geometryInput, ~] = routeA_panel_build_simulation_input(geometryCase, ...
    min(60, 0.1 * geometryCase.solver.stopTime_s));
geometryVariables = geometryInput.Variables;
geometryNames = string({geometryVariables.Name});
pipeDiameter = geometryVariables(geometryNames == "cegr_pipe_D").Value;
pipeArea = geometryVariables(geometryNames == "cegr_pipe_area").Value;
assert(pipeDiameter == 0.06 && abs(pipeArea - pi * 0.06^2 / 4) < 1e-15, ...
    'cEGR pipe diameter did not synchronise the derived flow area.');
badMapCase = mapCase;
badMapCase.controls.devices.cathode.compressorMap.rpm_TLU = [0, 2000, 2000];
assertRejectedCompressorMap(badMapCase, 'RouteA:CompressorMapRpmOrder');
badMapCase = mapCase;
badMapCase.controls.devices.cathode.compressorMap.mdot_corr_TLU = zeros(3, 3);
assertRejectedCompressorMap(badMapCase, 'RouteA:CompressorMapSize');

% Exercise every electrical boundary and every mutually exclusive air mode
% through the same panel builder. These are wiring checks only; no sim() is
% started here.
electricalTypes = ["Current", "Power", "Voltage"];
electricalCommands = [100, 40, 410];
for idx = 1:numel(electricalTypes)
    modeCase = valid;
    modeCase.controls.electrical.mode = char(electricalTypes(idx));
    modeCase.controls.electrical.profile = electricalCommands(idx);
    [~, modeContext] = routeA_panel_build_simulation_input(modeCase, ...
        min(60, 0.1 * modeCase.solver.stopTime_s));
    assert(modeContext.boundaryType == electricalTypes(idx), ...
        'Electrical boundary %s did not reach the builder.', ...
        electricalTypes(idx));
end

for modeId = 1:3
    modeCase = valid;
    modeCase.controls.cathode.airControlMode = modeId;
    modeCase.controls.cathode.targetOer = 3;
    modeCase.controls.cathode.targetMdot_kg_s = 0.045;
    modeCase.controls.cathode.directCommand = 0.45;
    [~, modeContext] = routeA_panel_build_simulation_input(modeCase, ...
        min(60, 0.1 * modeCase.solver.stopTime_s));
    assert(modeContext.air.modeId == modeId, ...
        'Air control mode %d did not reach the builder.', modeId);
end

directRampCase = valid;
directRampCase.controls.cathode.airControlMode = 3;
directRampCase.controls.cathode.directCommand = 0.45;
[directRampInput, ~] = routeA_panel_build_simulation_input(directRampCase, ...
    min(60, 0.1 * directRampCase.solver.stopTime_s));
directRampVariables = directRampInput.Variables;
directRampNames = string({directRampVariables.Name});
profileValue = directRampVariables( ...
    directRampNames == "routeA_command_profile").Value;
schema = routeA_command_profile_schema();
directColumn = find(schema.names == "air_direct_command", 1) + 1;
assert(profileValue(1, directColumn) == 0 && ...
    interp1(profileValue(:, 1), profileValue(:, directColumn), 0.5, ...
    'linear') > 0 && ...
    abs(profileValue(end, directColumn) - 0.45) < 1e-12, ...
    'Direct-air command must ramp from the cold-start baseline to the requested value.');

advancedCase = valid;
advancedCase.controls.electrical.mode = 'Voltage';
advancedCase.controls.electrical.profile = 410;
advancedCase.controls.cathode.airControlMode = 3;
advancedCase.controls.cathode.directCommand = 0.45;
advancedCase.controls.cathode.sourcePressure_MPa_abs = 0.17;
advancedCase.controls.cathode.sourceTemperature_C = 35;
advancedCase.controls.cathode.o2MoleFraction = 0.19;
advancedCase.controls.cathode.h2oMoleFraction = 0.012;
advancedCase.controls.cathode.humidifierEnabled = true;
advancedCase.controls.cegr.enabled = true;
advancedCase.controls.cegr.targetRatio = 0.3;
advancedCase.controls.cegr.valveMode = 1;
[~, advancedContext] = routeA_panel_build_simulation_input(advancedCase, ...
    min(60, 0.1 * advancedCase.solver.stopTime_s));
assert(advancedContext.air.modeId == 3 && ...
    advancedContext.cathode.sourcePressure_MPa_abs == 0.17 && ...
    advancedContext.cathode.sourceTemperature_C == 35 && ...
    advancedContext.requestedCegrRatio == 0.3 && ...
    advancedContext.cegrControls.valveMode == 1, ...
    'Advanced panel controls did not reach the unified builder.');

% UI page integration: all pages write through the same draft simCase.
app = RouteA_Panel_v01();
cleanupApp = onCleanup(@() delete(app));
drawnow;
assert(~isprop(app, 'AdvancedAmbientPressureEditField'), ...
    'Ambient pressure must not be exposed as an editable advanced control.');
app.CaseIdEditField.Value = 'p1_device_contract';
app.BoundaryCommandEditField.Value = 111;
app.ModeButtonGroup.SelectionChangedFcn(app.ModeButtonGroup, ...
    struct('NewValue', app.DeviceParameterModeButton));
drawnow;
assert(strcmp(app.DeviceSettingsPanel.Visible, 'on'), ...
    'Device settings page did not become visible.');
app.DeviceStackNumCellsEditField.Value = 405;
app.DeviceStackAreaEditField.Value = 270;
app.DeviceStackIEditField.Value = 1.5;
app.DeviceStackIoEditField.Value = 1.2e-4;
app.DeviceCegrActuatorTauEditField.Value = 0.8;
app.DeviceStackAlphaEditField.Value = 0.8;
app.DeviceStackMcpEditField.Value = 900;
app.DeviceStackMrhoEditField.Value = 1900;
app.DeviceStackGdlEditField.Value = 300;
app.DeviceStackMembraneEditField.Value = 140;
app.DeviceIntercoolerMdotEditField.Value = 0.12;
app.DeviceIntercoolerDpEditField.Value = 0.002;
app.DeviceIntercoolerAreaEditField.Value = 0.0021;
app.DeviceIntercoolerLaminarEditField.Value = 0.02;
app.DeviceCathodeSeparatorMdotEditField.Value = 0.12;
app.DeviceCathodeSeparatorDpEditField.Value = 0.001;
app.DeviceCathodeSeparatorAreaEditField.Value = 0.0022;
app.DeviceCathodeSeparatorLaminarEditField.Value = 0.02;
app.DeviceCathodeMixerVolumeEditField.Value = 0.15;
app.DeviceCathodeOutletVolumeEditField.Value = 0.3;
app.DeviceCegrValveMaxAreaEditField.Value = 2.1e-4;
app.DeviceCegrPipeLengthEditField.Value = 0.6;
app.DeviceCegrPipeDEditField.Value = 0.06;
app.DeviceCegrPipeRoughnessEditField.Value = 2e-5;
app.DeviceCegrCondTauEditField.Value = 1.2;
app.DeviceCegrInletMixerP0EditField.Value = 0.11;
app.DeviceCegrOutletP0EditField.Value = 0.12;
app.DeviceCegrPipeExtraLengthEditField.Value = 0.15;
app.DeviceCegrPipeP0EditField.Value = 0.11;
app.DeviceCegrValveMinAreaEditField.Value = 2e-10;
app.DeviceAnodeTankPressureEditField.Value = 65;
app.DeviceAnodeTankVolumeEditField.Value = 130;
app.DeviceAnodeTankTemperatureEditField.Value = 25;
app.DeviceAnodeSeparatorMdotEditField.Value = 0.012;
app.DeviceAnodeSeparatorDpEditField.Value = 0.0007;
app.DeviceAnodeSeparatorAreaEditField.Value = 0.0004;
app.DeviceAnodeSeparatorLaminarEditField.Value = 0.02;
app.DeviceCoolantChannelWidthEditField.Value = 1.2;
app.DeviceCoolantNumLayersEditField.Value = 24;
app.DeviceCoolantNumPassesEditField.Value = 14;
app.DeviceCoolantTubeDEditField.Value = 0.055;
app.DeviceRadiatorLengthEditField.Value = 1.2;
app.DeviceRadiatorWidthEditField.Value = 0.03;
app.DeviceRadiatorHeightEditField.Value = 0.55;
app.DeviceRadiatorTubeCountEditField.Value = 27;
app.DeviceRadiatorTubeHeightEditField.Value = 0.0016;
app.DeviceRadiatorFinSpacingEditField.Value = 0.0022;
app.DeviceRadiatorFinEfficiencyEditField.Value = 0.75;
app.DeviceRadiatorWallThicknessEditField.Value = 1.2e-4;
app.DeviceRadiatorDensityEditField.Value = 2800;
app.DeviceRadiatorSpecificHeatEditField.Value = 920;
[deviceCase, ~] = app.collectSimCaseFromUi();
assert(deviceCase.controls.stack.numCells == 405 && ...
    deviceCase.controls.stack.area_cm2 == 270 && ...
    deviceCase.controls.stack.iL_A_cm2 == 1.5 && ...
    deviceCase.controls.stack.io_A_cm2 == 1.2e-4 && ...
    deviceCase.controls.cegr.controller.actuatorTau_s == 0.8 && ...
    deviceCase.controls.devices.stack.alpha == 0.8 && ...
    deviceCase.controls.devices.cathode.intercoolerDpNominal_MPa == 0.002 && ...
    deviceCase.controls.devices.cathode.intercoolerArea_m2 == 0.0021 && ...
    deviceCase.controls.devices.cathode.intercoolerLaminarFraction == 0.02 && ...
    deviceCase.controls.devices.cathode.separatorArea_m2 == 0.0022 && ...
    deviceCase.controls.devices.cathode.separatorLaminarFraction == 0.02 && ...
    isfield(deviceCase.controls.devices.cathode, 'compressorMap') && ...
    deviceCase.controls.devices.cegr.valveMaxArea_m2 == 2.1e-4 && ...
    deviceCase.controls.devices.cegr.condensationTau_s == 1.2 && ...
    deviceCase.controls.devices.cegr.pipeExtraLength_m == 0.15 && ...
    deviceCase.controls.devices.anode.tankVolume_L == 130 && ...
    deviceCase.controls.devices.anode.separatorMdotNominal_kg_s == 0.012 && ...
    deviceCase.controls.devices.anode.separatorDpNominal_MPa == 0.0007 && ...
    deviceCase.controls.devices.anode.separatorArea_m2 == 0.0004 && ...
    deviceCase.controls.devices.thermal.coolantGeometry.numLayers == 24 && ...
    deviceCase.controls.devices.thermal.coolantGeometry.numPasses == 14 && ...
    deviceCase.controls.devices.thermal.radiatorCore.height_m == 0.55 && ...
    deviceCase.controls.devices.thermal.radiatorCore.finEfficiency == 0.75 && ...
    deviceCase.controls.devices.anode.separatorLaminarFraction == 0.02, ...
    'Device settings did not reach the shared draft simCase.');
assert(deviceCase.controls.electrical.profile == 111, ...
    'Device page unexpectedly changed the basic operating condition.');
app.RestoreDeviceDefaultsButton.ButtonPushedFcn( ...
    app.RestoreDeviceDefaultsButton, []);
[restoredDeviceCase, ~] = app.collectSimCaseFromUi();
assert(restoredDeviceCase.controls.electrical.profile == 111, ...
    'Restoring device defaults must not reset the operating condition.');
defaults = routeA_simCase_template();
assert(restoredDeviceCase.controls.stack.numCells == defaults.controls.stack.numCells && ...
    restoredDeviceCase.controls.cegr.controller.actuatorTau_s == ...
    defaults.controls.cegr.controller.actuatorTau_s, ...
    'Device defaults were not restored from the platform template.');
assert(restoredDeviceCase.controls.devices.stack.alpha == defaults.controls.devices.stack.alpha && ...
    restoredDeviceCase.controls.devices.cathode.intercoolerDpNominal_MPa == ...
    defaults.controls.devices.cathode.intercoolerDpNominal_MPa && ...
    restoredDeviceCase.controls.devices.cathode.intercoolerArea_m2 == ...
    defaults.controls.devices.cathode.intercoolerArea_m2 && ...
    restoredDeviceCase.controls.devices.cathode.separatorArea_m2 == ...
    defaults.controls.devices.cathode.separatorArea_m2 && ...
    restoredDeviceCase.controls.devices.cegr.valveMaxArea_m2 == ...
    defaults.controls.devices.cegr.valveMaxArea_m2 && ...
    restoredDeviceCase.controls.devices.cegr.condensationTau_s == ...
    defaults.controls.devices.cegr.condensationTau_s && ...
    restoredDeviceCase.controls.devices.anode.tankVolume_L == ...
    defaults.controls.devices.anode.tankVolume_L && ...
    restoredDeviceCase.controls.devices.anode.separatorMdotNominal_kg_s == ...
    defaults.controls.devices.anode.separatorMdotNominal_kg_s && ...
    restoredDeviceCase.controls.devices.anode.separatorLaminarFraction == ...
    defaults.controls.devices.anode.separatorLaminarFraction && ...
    restoredDeviceCase.controls.devices.thermal.coolantGeometry.channelWidth_cm == ...
    defaults.controls.devices.thermal.coolantGeometry.channelWidth_cm && ...
    restoredDeviceCase.controls.devices.thermal.radiatorCore.specificHeat_J_kgK == ...
    defaults.controls.devices.thermal.radiatorCore.specificHeat_J_kgK && ...
    isequal(restoredDeviceCase.controls.devices.cathode.compressorMap.rpm_TLU, ...
        defaults.controls.devices.cathode.compressorMap.rpm_TLU), ...
    'First-stage device defaults were not restored.');
thermalCase = valid;
thermalCase.controls.devices.thermal.radiatorCore.height_m = 0.04;
thermalCase.controls.devices.thermal.radiatorCore.tubeCount = 30;
thermalCase.controls.devices.thermal.radiatorCore.tubeHeight_m = 0.002;
assertRejectedDeviceValue(thermalCase, ...
    'controls.devices.thermal.radiatorCore.height_m');
thermalCase = valid;
thermalCase.controls.devices.thermal.coolantGeometry.numLayers = 0;
assertRejectedDeviceValue(thermalCase, ...
    'controls.devices.thermal.coolantGeometry.numLayers');
geometryCase = valid;
geometryCase.controls.devices.thermal.radiatorCore.height_m = 0.6;
geometryCase.controls.devices.thermal.radiatorCore.finSpacing_m = 0.0025;
[thermalInput, ~] = routeA_panel_build_simulation_input(geometryCase, ...
    min(60, 0.1 * geometryCase.solver.stopTime_s));
thermalNames = string({thermalInput.Variables.Name});
thermalValues = thermalInput.Variables;
primaryAreaValue = thermalValues(thermalNames == "radiator_air_area_primary").Value;
finAreaValue = thermalValues(thermalNames == "radiator_air_area_fins").Value;
assert(primaryAreaValue > 0 && finAreaValue > 0, ...
    'Thermal geometry derivation did not reach SimulationInput.');
app.ModeButtonGroup.SelectionChangedFcn(app.ModeButtonGroup, ...
    struct('NewValue', app.AdvancedModeButton));
drawnow;
app.AdvancedCommandProfileEditField.Value = '0,0; 60,100; 180,100';
app.AdvancedAmbientTemperatureEditField.Value = 32;
app.AdvancedAirPidKpEditField.Value = 6;
app.AdvancedAirPidKiEditField.Value = 0.6;
app.AdvancedCegrControlModeDropDown.Value = 2;
app.AdvancedCegrDirectAreaEditField.Value = 4.5e-6;
app.AdvancedCegrDirectTargetEditField.Value = 0.03;
[profileCase, ~] = app.collectSimCaseFromUi();
assert(isequal(profileCase.controls.electrical.profile, [0 0; 60 100; 180 100]), ...
    'Explicit advanced command profile did not reach simCase.');
assert(profileCase.controls.environment.ambientTemperature_C == 32 && ...
    profileCase.controls.environment.ambientPressure_MPa_abs == fixedPressure_MPa_abs && ...
    profileCase.controls.cathode.airController.Kp == 6 && ...
    profileCase.controls.cathode.airController.Ki == 0.6 && ...
    profileCase.controls.cegr.controlMode == 2 && ...
    profileCase.controls.cegr.directValveArea_m2 == 4.5e-6 && ...
    profileCase.controls.cegr.directTargetRatio == 0.03, ...
    'Advanced pending variables did not reach the shared draft simCase.');
[directInput, directContext] = routeA_panel_build_simulation_input(profileCase, ...
    min(60, 0.1 * profileCase.solver.stopTime_s));
directNames = string({directInput.Variables.Name});
directValues = directInput.Variables;
assert(directContext.cegrControls.controlMode == 2 && ...
    directValues(directNames == "env_T").Value == 32 && ...
    directValues(directNames == "env_p").Value == fixedPressure_MPa_abs && ...
    directValues(directNames == "routeA_air_pid_Kp").Value == 6 && ...
    directValues(directNames == "routeA_air_pid_Ki").Value == 0.6 && ...
    directValues(directNames == "routeA_egr_valve_area_direct").Value == 4.5e-6 && ...
    directValues(directNames == "routeA_target_egr_ratio_comp_in").Value == 0.03, ...
    'Advanced pending variables did not reach SimulationInput.');
app.ModeButtonGroup.SelectionChangedFcn(app.ModeButtonGroup, ...
    struct('NewValue', app.ModelParameterModeButton));
drawnow;
assert(strcmp(app.FutureDomainsPanel.Visible, 'on') && ...
    size(app.RunSnapshotTable.Data, 1) == 5 && ...
    size(app.ParameterCatalogTable.Data, 1) == ...
        parameterAudit.counts.workspaceVariableCount, ...
    'Model-parameter snapshot is not available on the read-only page.');

report = struct( ...
    'schemaVersion', "RouteA_P1_Panel_Contract_Tests_v01", ...
    'passed', true, ...
    'simulationStarted', false, ...
    'invalidInputCount', numel(tests), ...
    'invalidInputs', tests, ...
    'disabledCegrTargetNormalized', valid.controls.cegr.targetRatio, ...
    'rampRejected', rampRejected, ...
    'electricalModesBuilt', numel(electricalTypes), ...
    'airModesBuilt', 3, ...
    'advancedMappingPassed', true, ...
    'devicePageMappingPassed', true, ...
    'modelPanelAuditPassed', true, ...
    'modelWorkspaceCatalogCount', parameterAudit.counts.workspaceVariableCount, ...
    'compressorMapContractPassed', true, ...
    'cegrGeometryContractPassed', true, ...
    'explicitProfileMappingPassed', true, ...
    'fixedAmbientPressure_MPa_abs', fixedPressure_MPa_abs, ...
    'unsupportedCegrValveModeRejected', true, ...
    'defaultRampDurationApplied', true, ...
    'directAirColdStartRampPassed', true, ...
    'capabilityCounts', matrix.counts, ...
    'generatedAt', string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss')));
end

function assertRejectedCompressorMap(simCase, expectedId)
try
    routeA_validate_case(simCase);
    error('RouteA:P1ContractTestNotRejected', ...
        'Invalid compressor map was not rejected.');
catch ME
    assert(strcmp(ME.identifier, expectedId), ...
        'Expected %s, got %s.', expectedId, ME.identifier);
end
end

function assertRejectedDeviceValue(simCase, expectedField)
try
    routeA_validate_case(simCase);
    error('RouteA:P1ContractTestNotRejected', ...
        'Invalid device input %s was not rejected.', expectedField);
catch ME
    assert(~strcmp(ME.identifier, 'RouteA:P1ContractTestNotRejected'), ...
        'Invalid device input %s was not rejected.', expectedField);
end
end

function assertRejectedFixedAmbientPressure(simCase)
try
    routeA_validate_case(simCase);
    error('RouteA:P1ContractTestNotRejected', ...
        'A non-default ambient pressure was not rejected.');
catch ME
    assert(strcmp(ME.identifier, 'RouteA:FixedAmbientPressure'), ...
        'Expected RouteA:FixedAmbientPressure, got %s.', ME.identifier);
end
end

function assertRejectedCegrValveMode(simCase)
try
    routeA_validate_case(simCase);
    error('RouteA:P1ContractTestNotRejected', ...
        'Unsupported cEGR valve mode was not rejected.');
catch ME
    assert(strcmp(ME.identifier, 'RouteA:CegRValveMode'), ...
        'Expected RouteA:CegRValveMode, got %s.', ME.identifier);
end
end

function simCase = setValue(simCase, name, value)
switch name
    case 'airControlMode'
        simCase.controls.cathode.airControlMode = value;
    case 'targetOer'
        simCase.controls.cathode.targetOer = value;
    case 'targetMdot_kg_s'
        simCase.controls.cathode.targetMdot_kg_s = value;
    case 'directCommand'
        simCase.controls.cathode.directCommand = value;
    case 'sourcePressure_MPa_abs'
        simCase.controls.cathode.sourcePressure_MPa_abs = value;
    case 'sourceTemperature_C'
        simCase.controls.cathode.sourceTemperature_C = value;
    case 'humidifierRH'
        simCase.controls.cathode.humidifierRH = value;
    case 'o2MoleFraction'
        simCase.controls.cathode.o2MoleFraction = value;
    case 'h2oMoleFraction'
        simCase.controls.cathode.h2oMoleFraction = value;
    case 'outletPressure_MPa_abs'
        simCase.controls.cathode.outletPressure_MPa_abs = value;
    case 'cegrRatio'
        simCase.controls.cegr.targetRatio = value;
    case 'valveMode'
        simCase.controls.cegr.valveMode = value;
    case 'controlMode'
        simCase.controls.cegr.controlMode = value;
    case 'targetInputMode'
        simCase.controls.cegr.targetInputMode = value;
    case 'stackTemperatureSet_C'
        simCase.controls.thermal.stackTemperatureSet_C = value;
    case 'stopTime_s'
        simCase.solver.stopTime_s = value;
    case 'solver'
        simCase.solver.solver = value;
    case 'relTol'
        simCase.solver.relTol = value;
    case 'absTol'
        simCase.solver.absTol = value;
    case 'maxStep_s'
        simCase.solver.maxStep_s = value;
    case 'voltageController'
        simCase.controls.electrical.mode = 'Voltage';
        simCase.controls.electrical.voltageController.currentMin_A = 200;
        simCase.controls.electrical.voltageController.currentMax_A = 100;
    otherwise
        error('RouteA:P1ContractTestField', 'Unsupported test field %s.', name);
end
end
