function report = run_routeA_p1_panel_acceptance()
% Optional P1 panel development smoke; this is not a completion gate.
%
% Each row is one independent panel case. No Cartesian matrix or parallel
% study is performed. The two rows are simple examples for checking the
% panel-to-model route at cEGR=0 and cEGR=0.3 when troubleshooting is needed.

paths = routeA_project_paths();
caseIds = {'p1PanelBasicCegr0', 'p1PanelAdvancedCegr03'};
boundaryTypes = {'Current', 'Voltage'};
commands = {100, 410};
options = { ...
    struct('stopTime_s', 600, 'airControlMode', 2, 'targetOer', 3, ...
        'cegrEnabled', false, 'cegrRatio', 0), ...
    struct('stopTime_s', 600, 'airControlMode', 3, ...
        'directCommand', 0.45, 'sourcePressure_MPa_abs', 0.17, ...
        'sourceTemperature_C', 35, 'outletPressure_MPa_abs', 0.1613, ...
        'humidifierRH', 0.8, 'humidifierEnabled', true, ...
        'o2MoleFraction', 0.19, 'h2oMoleFraction', 0.012, ...
        'stackTemperatureSet_C', 82, 'cegrEnabled', true, ...
        'cegrRatio', 0.3, 'valveMode', 2, 'controlMode', 1, ...
        'targetInputMode', 1, ...
        'voltageController', struct('Kp_A_V', 1, 'Ki_A_V_s', 0.05, ...
        'currentMin_A', 0, 'currentMax_A', 392))};

evidenceTemplate = struct( ...
    'caseId', "", 'status', "", 'passed', false, ...
    'failureCategory', "", 'errorId', "", 'errorMessage', "", ...
    'warnings', strings(0, 1), 'failureStack', strings(0, 1), ...
    'parameterSnapshot', struct(), 'modelAndTopology', struct(), ...
    'solverAndInitialization', struct(), 'signalManifest', struct(), ...
    'kpi', struct(), 'exportPath', "");
evidence = repmat(evidenceTemplate, numel(caseIds), 1);
for idx = 1:numel(caseIds)
    localOptions = options{idx};
    localOptions.caseId = caseIds{idx};
    if idx == numel(caseIds)
        localOptions.outputFile = fullfile(paths.panelResultRoot, ...
            'p1PanelAdvancedCegr03_RouteA_P1_result.mat');
    end
    try
        result = run_routeA_p1_panel_single_case( ...
            boundaryTypes{idx}, commands{idx}, localOptions);
    catch ME
        result = routeA_panel_failure_result(ME, ...
            routeA_simCase_template());
        result.caseId = string(caseIds{idx});
    end
    evidence(idx).caseId = string(caseIds{idx});
    evidence(idx).status = string(result.status);
    evidence(idx).passed = logical(result.passed);
    evidence(idx).failureCategory = string(result.failureCategory);
    evidence(idx).errorId = string(result.errorId);
    evidence(idx).errorMessage = string(result.errorMessage);
    evidence(idx).warnings = string(result.warnings(:));
    evidence(idx).failureStack = string(result.failureStack(:));
    evidence(idx).parameterSnapshot = getFieldOr(result, ...
        'parameterSnapshot', struct());
    evidence(idx).modelAndTopology = getFieldOr(result, ...
        'modelAndTopology', struct());
    evidence(idx).solverAndInitialization = getFieldOr(result, ...
        'solverAndInitialization', struct());
    evidence(idx).signalManifest = getFieldOr(result, ...
        'signalManifest', struct());
    evidence(idx).kpi = kpiSummary(result);
    evidence(idx).exportPath = getFieldOr(result, 'exportFile', "");
end

summaryFile = fullfile(paths.panelResultRoot, ...
    'RouteA_P1_panel_acceptance_summary.mat');
if ~isfolder(paths.panelResultRoot)
    mkdir(paths.panelResultRoot);
end
summary = struct( ...
    'schemaVersion', "RouteA_P1_Panel_Development_Smoke_v01", ...
    'purpose', "development_smoke_only", ...
    'isCompletionGate', false, ...
    'passed', all([evidence.passed]), ...
    'caseCount', numel(evidence), ...
    'cEGRVerificationSet', ["0", "0.3"], ...
    'matrixExecuted', false, ...
    'cases', evidence, ...
    'generatedAt', string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss')));
save(summaryFile, 'summary', '-v7.3');
loaded = load(summaryFile, 'summary');
assert(isfield(loaded, 'summary') && loaded.summary.caseCount == numel(evidence), ...
    'Acceptance summary readback failed.');
report = summary;
report.summaryFile = string(summaryFile);
end

function summary = kpiSummary(result)
summary = struct( ...
    'voltage_V', getFieldOr(result, 'voltage_V', NaN), ...
    'current_A', getFieldOr(result, 'current_A', NaN), ...
    'power_kW', getFieldOr(result, 'power_kW', NaN), ...
    'targetCegrRatio', getFieldOr(result, 'target_cegr_ratio', NaN), ...
    'actualCegrRatio', getFieldOr(result, 'actual_cegr_ratio', NaN), ...
    'waterStatus', getNestedFieldOr(result, ...
        {'waterCapability', 'status'}, "not_available"), ...
    'gasClosurePassed', getFieldOr(result, 'gasClosurePassed', false));
if isfield(result, 'domains') && isfield(result.domains, 'cegr') && ...
        isfield(result.domains.cegr, 'abilityStatus')
    summary.cegrAbilityStatus = string(result.domains.cegr.abilityStatus);
else
    summary.cegrAbilityStatus = "not_observable";
end
end

function value = getFieldOr(parent, fieldName, fallback)
value = fallback;
if isstruct(parent) && isscalar(parent) && isfield(parent, fieldName)
    value = parent.(fieldName);
end
end

function value = getNestedFieldOr(parent, names, fallback)
value = parent;
for idx = 1:numel(names)
    if isstruct(value) && isscalar(value) && isfield(value, names{idx})
        value = value.(names{idx});
    else
        value = fallback;
        return;
    end
end
end
