function report = run_routeA_p0_acceptance(options)
% Run the Route A P0 acceptance harness.
%
% The harness is the single compact entry point for the active cold-start
% contract. It checks relocatable dependencies and model interfaces, runs the
% short cold smoke, and optionally runs the canonical 3600 s Current/Power/
% Voltage convergence cases. Strict 0.5% and engineering 1% convergence are
% reported independently. Periodic anode inventory behavior is outside the
% electrical/cathode/thermal steady-signal scope and is reported separately.

if nargin < 1 || isempty(options)
    options = struct();
end
options = normalizeOptions(options);

paths = routeA_project_paths(mfilename('fullpath'));
addpath(paths.scriptDir);
addpath(paths.modelDir);

report = reportTemplate(paths, options);
report.dependencies = routeA_check_dependencies(paths, true);
[report.contract, report.contractReadBack] = routeA_model_contract(paths, ...
    struct('loadModel', true, 'readBack', true, 'strict', true));
report.preflightPassed = report.dependencies.passed && ...
    report.contractReadBack.passed;

if ~report.preflightPassed
    report.overallPassed = false;
    report = saveReport(report, options);
    displayReport(report);
    return;
end

if options.runSmoke
    smokeCases = buildSmokeCases();
    smokeCfg = studyConfig(options, 10, [5, 10], 1, 0.1, smokeCases, ...
        "transient");
    report.smoke = runAndSummarize(smokeCfg, paths);
else
    report.smoke = skippedSection("disabled_by_options");
end

if options.runLongCases
    longCases = buildLongCases(options.researchDuration_s);
    report.longCases = runLongCases(longCases, options, paths);
else
    report.longCases = skippedSection("disabled_by_options");
end

report.overallPassed = report.preflightPassed && ...
    sectionPassed(report.smoke, options.runSmoke) && ...
    sectionPassed(report.longCases, options.runLongCases);
report = saveReport(report, options);
displayReport(report);
end

function options = normalizeOptions(options)
defaults = struct( ...
    'runSmoke', true, ...
    'runLongCases', true, ...
    'researchDuration_s', 3600, ...
    'strictSteadyRelativeLimit', 0.005, ...
    'engineeringSteadyRelativeLimit', 0.01, ...
    'relativeTolerance', 1e-3, ...
    'absoluteTolerance', 1e-3, ...
    'maxStep_s', 5, ...
    'showProgress', true, ...
    'saveReport', true, ...
    'resultFile', "");
names = fieldnames(options);
for idx = 1:numel(names)
    if ~isfield(defaults, names{idx})
        error('RouteA:P0AcceptanceOption', ...
            'Unsupported P0 acceptance option: %s.', names{idx});
    end
    defaults.(names{idx}) = options.(names{idx});
end
options = defaults;
options.runSmoke = logical(options.runSmoke);
options.runLongCases = logical(options.runLongCases);
options.showProgress = logical(options.showProgress);
options.saveReport = logical(options.saveReport);
validateattributes(options.researchDuration_s, {'numeric'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(options.strictSteadyRelativeLimit, {'numeric'}, ...
    {'scalar', 'positive', 'finite', '<=', 1});
validateattributes(options.engineeringSteadyRelativeLimit, {'numeric'}, ...
    {'scalar', 'positive', 'finite', '<=', 1});
if options.engineeringSteadyRelativeLimit < options.strictSteadyRelativeLimit
    error('RouteA:P0AcceptanceSteadyLimits', ...
        'The engineering steady limit must be >= the strict steady limit.');
end
end

function cases = buildSmokeCases()
specs = { ...
    struct('caseId', "p0_cold_current_100A", ...
        'profile', [0, 0; 1, 100; 10, 100], 'targetRatio', 0), ...
    struct('caseId', "p0_cold_current_100A_cegr_010", ...
        'profile', [0, 0; 1, 100; 10, 100], 'targetRatio', 0.1)};
cases = routeA_build_electrical_boundary_cases("Current", specs);
end

function cases = buildLongCases(duration_s)
% These are canonical convergence probes, not new platform parameter sources.
specs = { ...
    struct('caseId', "p0_cold_current_28A_3600s", ...
        'profile', [0, 0; 60, 28; duration_s, 28], 'targetRatio', 0), ...
    struct('caseId', "p0_cold_power_P0_3600s", ...
        'profile', [0, 0; 60, 11.974169; duration_s, 11.974169], ...
        'targetRatio', 0), ...
    struct('caseId', "p0_cold_voltage_V0_3600s", ...
        'profile', [0, 427.6; 60, 427.648894; duration_s, 427.648894], ...
        'targetRatio', 0)};
cases = { ...
    routeA_build_electrical_boundary_cases("Current", specs(1)), ...
    routeA_build_electrical_boundary_cases("Power", specs(2)), ...
    routeA_build_electrical_boundary_cases("Voltage", specs(3))};
end

function cfg = studyConfig(options, duration_s, tailWindow_s, ...
        steadyWindow_s, maxStep_s, cases, calculationType)
cfg = struct( ...
    'calculationType', calculationType, ...
    'researchDuration_s', duration_s, ...
    'tailLogicalWindow_s', tailWindow_s, ...
    'steadyWindowDuration_s', steadyWindow_s, ...
    'steadyRelativeVariationLimit', options.strictSteadyRelativeLimit, ...
    'engineeringSteadyRelativeVariationLimit', ...
        options.engineeringSteadyRelativeLimit, ...
    'solver', "VariableStepAuto", ...
    'relativeTolerance', options.relativeTolerance, ...
    'absoluteTolerance', options.absoluteTolerance, ...
    'studyMaxStep_s', maxStep_s, ...
    'commandStartOffset_s', 0, ...
    'startupRampDuration_s', max(1, min(60, duration_s / 10)), ...
    'runWaterLedger', false, ...
    'executionMode', "serial", ...
    'parallelWorkers', 1, ...
    'showProgress', options.showProgress, ...
    'retainSimulationOutputs', true, ...
    'resultFile', "", ...
    'cases', cases);
end

function section = runLongCases(cases, options, paths)
section = sectionTemplate();
for idx = 1:numel(cases)
    cfg = studyConfig(options, options.researchDuration_s, ...
        [options.researchDuration_s - 60, options.researchDuration_s], ...
        60, options.maxStep_s, cases{idx}, "steady");
    part = runAndSummarize(cfg, paths);
    if idx == 1
        section.studyMetadata = part.studyMetadata;
    end
    if strlength(string(part.errorId)) > 0
        section.errorId = part.errorId;
        section.errorMessage = part.errorMessage;
    end
    section.cases = vertcat(section.cases, part.cases);
end
section.caseCount = numel(section.cases);
section.passed = section.caseCount > 0 && ...
    builtin('all', arrayfun(@(x) x.accepted, section.cases));
end

function section = runAndSummarize(config, paths)
% Keep full SimulationOutput only during assessment; the returned section is
% compact and contains no large time-series payload.
section = sectionTemplate();
try
    study = run_routeA_electrical_boundary_study(config);
catch ME
    section.passed = false;
    section.errorId = string(ME.identifier);
    section.errorMessage = string(ME.message);
    return;
end
section.studyMetadata = struct( ...
    'model', study.model, ...
    'parameterLayer', study.parameterLayer, ...
    'externalCaseEnabled', study.externalCaseEnabled, ...
    'initializationPolicy', study.initializationPolicy, ...
    'researchDuration_s', study.researchDuration_s, ...
    'solver', study.solver, ...
    'topologyHash', topologyHash(study));
section.caseCount = numel(study.cases);
section.cases = repmat(caseSummaryTemplate(), section.caseCount, 1);
for idx = 1:section.caseCount
    item = study.cases(idx);
    out = [];
    if isfield(study, 'caseOutputs') && numel(study.caseOutputs) >= idx
        out = study.caseOutputs(idx).out;
    end
    summary = caseSummaryTemplate();
    summary.caseId = string(item.caseId);
    summary.boundaryType = textField(item, 'boundaryType', "");
    summary.simCompleted = logicalField(item, 'simCompleted', false);
    summary.runnerStrictPassed = logicalField(item, 'passed', false);
    summary.failureCategory = textField(item, 'failureCategory', "");
    summary.errorId = textField(item, 'errorId', "");
    summary.errorMessage = textField(item, 'errorMessage', "");
    summary.nonSteadyOnly = nonSteadyOnly(item);
    if summary.simCompleted && isa(out, 'Simulink.SimulationOutput')
        summary.observation = routeA_validate_observation_output(out, ...
            routeA_observation_registry(paths));
    else
        summary.observation = emptyObservationSummary();
    end
    if isfield(item, 'steady')
        summary.strictSteadyPassed = logical(item.steady.strictPassed);
        summary.engineeringSteadyPassed = ...
            logical(item.steady.engineeringPassed);
        summary.steadyClassification = string(item.steady.classification);
        summary.maximumRelativeChange = item.steady.maximumRelativeChange;
    end
    if isfield(item, 'periodicAnode')
        summary.periodicAnode = item.periodicAnode;
    end
    summary.periodicResponseAccepted = periodicResponseAccepted(item);
    [summary.acceptanceStatus, summary.accepted] = classifyCase(summary);
    section.cases(idx) = summary;
end
section.passed = section.caseCount > 0 && ...
    builtin('all', arrayfun(@(x) x.accepted, section.cases));
end

function [status, accepted] = classifyCase(summary)
accepted = false;
if ~summary.simCompleted
    status = "simulation_failed";
elseif ~summary.observation.passed
    status = "observation_contract_failed";
elseif summary.runnerStrictPassed
    status = "strict_pass_0p5_percent";
    accepted = true;
elseif summary.steadyClassification == "not_applicable"
    status = "completed_transient";
    accepted = true;
elseif summary.engineeringSteadyPassed && summary.nonSteadyOnly
    status = "engineering_pass_1_percent";
    accepted = true;
elseif summary.periodicResponseAccepted
    status = "periodic_response_voltage_tracked";
    accepted = true;
else
    status = "completed_not_converged";
end
end

function accepted = periodicResponseAccepted(item)
% Accept purge-periodic Voltage behavior only after nonperiodic gates pass.
accepted = false;
if ~isfield(item, 'simCompleted') || ~item.simCompleted || ...
        ~isfield(item, 'boundaryType') || ...
        string(item.boundaryType) ~= "Voltage" || ...
        ~isfield(item, 'periodicAnode')
    return;
end
periodic = item.periodicAnode;
if ~isfield(periodic, 'classification') || ...
        string(periodic.classification) ~= "periodic_anode_inventory" || ...
        ~isfield(periodic, 'completeCycleCount') || ...
        periodic.completeCycleCount < 2 || ...
        ~isfield(periodic, 'cyclePeriodMean_s') || ...
        ~isfinite(periodic.cyclePeriodMean_s) || ...
        ~isfield(periodic, 'cyclePeriodStd_s') || ...
        ~isfinite(periodic.cyclePeriodStd_s) || ...
        periodic.cyclePeriodStd_s / max(periodic.cyclePeriodMean_s, eps) > 0.01
    return;
end
required = { ...
    'finiteTail', 'boundaryPassed', 'cegrPassed', 'saturationPassed', ...
    'lambdaPassed', 'pressureDirectionPassed', 'areaPassed', ...
    'compressorRpmLookupPassed', 'compressorMdotTrackingPassed', ...
    'gasClosurePassed', 'tailPurgeFree'};
for idx = 1:numel(required)
    name = required{idx};
    if ~isfield(item, name) || ~logical(item.(name))
        return;
    end
end
if ~isfield(item, 'steady') || ~isfield(item.steady, 'metrics')
    return;
end
excluded = ["stackCurrent_A", "stackPower_kW", "cathodeOxygenStoich"];
names = string(fieldnames(item.steady.metrics));
for idx = 1:numel(names)
    if any(names(idx) == excluded)
        continue;
    end
    metric = item.steady.metrics.(char(names(idx)));
    if ~isfield(metric, 'strictPassed') || ~logical(metric.strictPassed)
        return;
    end
end
accepted = true;
end

function value = nonSteadyOnly(item)
names = { ...
    'finiteTail', 'boundaryPassed', 'cegrPassed', 'saturationPassed', ...
    'lambdaPassed', 'pressureDirectionPassed', 'areaPassed', ...
    'compressorRpmLookupPassed', 'compressorMdotTrackingPassed', ...
    'gasClosurePassed', 'tailPurgeFree'};
value = true;
for idx = 1:numel(names)
    if ~isfield(item, names{idx}) || ~logical(item.(names{idx}))
        value = false;
        return;
    end
end
end

function passed = sectionPassed(section, required)
if ~required
    passed = true;
else
    passed = isfield(section, 'passed') && logical(section.passed);
end
end

function report = saveReport(report, options)
report.generatedAt = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss'));
if ~options.saveReport
    report.resultFile = "";
    return;
end
resultFile = string(options.resultFile);
if strlength(resultFile) == 0
    resultRoot = fullfile(report.paths.resultRoot, 'outputs', ...
        'RouteA_P0_acceptance');
    if ~isfolder(resultRoot)
        mkdir(resultRoot);
    end
    resultFile = fullfile(resultRoot, 'RouteA_P0_acceptance_latest.mat');
end
[folder, ~, extension] = fileparts(resultFile);
if ~isfolder(folder) || ~strcmpi(extension, '.mat')
    error('RouteA:P0AcceptanceResultFile', ...
        'resultFile must be an existing-folder .mat path.');
end
routeA_p0_acceptance_report = report;
save(char(resultFile), 'routeA_p0_acceptance_report', '-v7.3');
report.resultFile = resultFile;
end

function report = reportTemplate(paths, options)
report = struct( ...
    'schemaVersion', "RouteA_P0_Acceptance_Report_v01", ...
    'generatedAt', "", ...
    'paths', paths, ...
    'options', options, ...
    'convergencePolicy', struct( ...
        'strictRelativeLimit', options.strictSteadyRelativeLimit, ...
        'engineeringRelativeLimit', options.engineeringSteadyRelativeLimit, ...
        'scope', "voltage tracking, nonperiodic cathode gas, compressor, and thermal signals", ...
        'periodicSignalsExcluded', ["stackCurrent_A", "stackPower_kW", ...
            "cathodeOxygenStoich", "anode inventory", "purge state"], ...
         'periodicTreatment', "For purge-enabled Voltage cases, classify current/power/derived oxygen-stoich changes through a periodic-response gate after voltage and safety checks pass.", ...
         'periodicCycleCountMinimum', 2, ...
         'periodicCyclePeriodRelativeStdLimit', 0.01), ...
    'warningPolicy', struct( ...
        'blocking', ["new error", "unclassified warning", "failed required contract"], ...
        'nonBlocking', "classified warning with owner, impact, disposition, and evidence", ...
        'requiredLedgerFields', ["category", "owner", "impact", "disposition", "evidence"]), ...
    'dependencies', struct(), ...
    'contract', struct(), ...
    'contractReadBack', struct(), ...
    'preflightPassed', false, ...
    'smoke', struct(), ...
    'longCases', struct(), ...
    'overallPassed', false, ...
    'resultFile', "");
end

function section = sectionTemplate()
section = struct('passed', false, 'caseCount', 0, ...
    'cases', repmat(caseSummaryTemplate(), 0, 1), ...
    'studyMetadata', struct(), 'errorId', "", 'errorMessage', "");
end

function summary = caseSummaryTemplate()
summary = struct( ...
    'caseId', "", ...
    'boundaryType', "", ...
    'simCompleted', false, ...
    'runnerStrictPassed', false, ...
    'strictSteadyPassed', false, ...
    'engineeringSteadyPassed', false, ...
     'steadyClassification', "not_applicable", ...
     'maximumRelativeChange', NaN, ...
     'periodicAnode', struct(), ...
     'periodicResponseAccepted', false, ...
     'nonSteadyOnly', false, ...
    'failureCategory', "", ...
    'errorId', "", ...
    'errorMessage', "", ...
    'observation', emptyObservationSummary(), ...
    'acceptanceStatus', "not_run", ...
    'accepted', false);
end

function summary = emptyObservationSummary()
summary = struct('passed', false, 'errors', strings(0, 1), ...
    'warnings', strings(0, 1), 'presentCount', 0);
end

function value = logicalField(s, name, fallback)
if isfield(s, name)
    value = logical(s.(name));
else
    value = fallback;
end
end

function value = textField(s, name, fallback)
if isfield(s, name)
    value = string(s.(name));
else
    value = string(fallback);
end
end

function value = topologyHash(study)
value = "";
if isfield(study, 'cases') && ~isempty(study.cases) && ...
        isfield(study.cases(1), 'initialState') && ...
        isfield(study.cases(1).initialState, 'topologyHash')
    value = string(study.cases(1).initialState.topologyHash);
end
end

function section = skippedSection(reason)
section = sectionTemplate();
section.errorId = "RouteA:P0AcceptanceSkipped";
section.errorMessage = string(reason);
end

function displayReport(report)
fprintf('\nRoute A P0 acceptance\n');
fprintf('  preflight=%d smoke=%d long=%d overall=%d\n', ...
    report.preflightPassed, report.smoke.passed, report.longCases.passed, ...
    report.overallPassed);
if isfield(report, 'longCases') && isfield(report.longCases, 'cases')
    for idx = 1:numel(report.longCases.cases)
        item = report.longCases.cases(idx);
        fprintf('  %s: %s maxChange=%.6g\n', item.caseId, ...
            item.acceptanceStatus, item.maximumRelativeChange);
    end
end
if strlength(string(report.resultFile)) > 0
    fprintf('  report=%s\n', report.resultFile);
end
end
